import {useEffect,useState} from 'react';
import {api} from './api';
import {useLanguage,intlLocale} from './i18n';
import {useAppBack} from './navigation';
import {activityLabels,shortHash,statusLabels,type ActivityItem} from './production-types';
import './production.css';

const filters=[['ALL','Все'],['ACCOUNT','Аккаунт'],['DEPOSIT','Пополнения'],['WITHDRAWAL','Выводы'],['PURCHASE','Тарифы'],['ADJUSTMENT','Служебные пополнения'],['EPOCH','Epoch']] as const;
export default function Activity({onBack,onSupport}:{onBack:()=>void;onSupport:(reference:{referenceType:'DEPOSIT'|'WITHDRAWAL';referenceId:string})=>void}){
 const {t,language}=useLanguage(),locale=intlLocale(language);
 const [filter,setFilter]=useState<string>('ALL'),[rows,setRows]=useState<ActivityItem[]|null>(null),[selected,setSelected]=useState<ActivityItem|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;setRows(null);void api<{items:ActivityItem[]}>('/v1/activity?type='+filter).then(data=>{if(live)setRows(data.items)}).catch(e=>{if(live)setError((e as Error).message)});return()=>{live=false}},[filter]);
 useAppBack(Boolean(selected),()=>setSelected(null));
 return <section className="production-page" aria-labelledby="activity-title"><button className="secondary" onClick={onBack}>← {t('Профиль')}</button><div className="production-heading"><h2 id="activity-title">{t('История активности')}</h2><span>AETHERMIND</span></div><div className="production-filters" aria-label={t('Фильтр операций')}>{filters.map(([id,label])=><button key={id} className={filter===id?'active':''} aria-pressed={filter===id} onClick={()=>{setFilter(id);setSelected(null)}}>{t(label)}</button>)}</div>{error&&<p role="alert" className="owner-error">{error}</p>}
  {rows===null?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/><i/></div>:!rows.length?<div className="production-empty">{t('Операций пока нет')}</div>:<div className="production-list">{rows.map(row=><button className="production-row" key={row.id} aria-expanded={selected?.id===row.id} onClick={()=>setSelected(selected?.id===row.id?null:row)}><span><b>{t(activityLabels[row.type]||row.type)}{row.amount?' · '+row.amount+' USDT':''}</b><small>{row.network?row.network+' · ':''}{new Date(row.createdAt).toLocaleString(locale)}</small></span><span>{t(statusLabels[row.status]||row.status)}</span></button>)}</div>}
  {selected&&<article className="panel production-detail"><h3>{t('Детали операции')}</h3><dl><div><dt>{t('Тип')}</dt><dd>{t(activityLabels[selected.type]||selected.type)}</dd></div>{selected.amount&&<div><dt>{t('Сумма')}</dt><dd>{selected.amount} USDT</dd></div>}<div><dt>{t('Статус')}</dt><dd>{t(statusLabels[selected.status]||selected.status)}</dd></div>{selected.network&&<div><dt>{t('Сеть')}</dt><dd>{selected.network}</dd></div>}<div><dt>{t('Создан')}</dt><dd>{new Date(selected.createdAt).toLocaleString(locale)}</dd></div>{selected.details.invoiceId&&<div><dt>Invoice ID</dt><dd>{selected.details.invoiceId}</dd></div>}{selected.details.wallet&&<div><dt>{t('Кошелёк')}</dt><dd>{selected.details.wallet}</dd></div>}{selected.details.destination&&<div><dt>{t('Получатель')}</dt><dd>{selected.details.destination}</dd></div>}{selected.details.version&&<div><dt>{t('Редакция')}</dt><dd>{selected.details.version}</dd></div>}{selected.details.node&&<div><dt>{t('Нода')}</dt><dd>{selected.details.node}</dd></div>}{selected.details.confirmedAt&&<div><dt>{t('Подтверждён')}</dt><dd>{new Date(selected.details.confirmedAt).toLocaleString(locale)}</dd></div>}{selected.details.txHash&&<div><dt>Transaction hash</dt><dd><a href={'https://tonviewer.com/transaction/'+selected.details.txHash} target="_blank" rel="noopener noreferrer">{shortHash(selected.details.txHash)} ↗</a></dd></div>}{selected.details.rejectionReason&&<div><dt>{t('Причина отказа')}</dt><dd>{selected.details.rejectionReason}</dd></div>}</dl>{(selected.type==='DEPOSIT'||selected.type==='WITHDRAWAL')&&<button className="secondary" onClick={()=>onSupport({referenceType:selected.type as 'DEPOSIT'|'WITHDRAWAL',referenceId:selected.id.split(':')[1]})}>{t('Сообщить о проблеме')}</button>}</article>}
 </section>;
}
