import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {api} from './api';
import {useLanguage,intlLocale} from './i18n';
import {useAppBack} from './navigation';
import {activityLabels,shortHash,statusLabels,type ActivityItem} from './production-types';
import {PageHeader,ListRow,StatusPill,Money,EmptyState} from './UI';
import './production.css';
const filters=[['ALL','Все'],['ACCOUNT','Аккаунт'],['DEPOSIT','Пополнения'],['WITHDRAWAL','Выводы'],['PURCHASE','Тарифы'],['ADJUSTMENT','Служебные пополнения'],['EPOCH','Начисления']] as const;
const icons:Record<string,string>={REGISTERED:'user',AGREEMENT_ACCEPTED:'receipt',PUBLIC_OFFER_ACCEPTED:'documents',TARIFF_SELECTED:'node',WALLET_CONNECTED:'wallet',SUPPORT_CREATED:'help',SUPPORT_FOLLOW_UP:'help',DEPOSIT:'download',WITHDRAWAL:'send',PURCHASE:'node',ADMIN_CREDIT:'download',EPOCH:'bolt',DATA_EXPORT_REQUEST:'data',DATA_DELETION_REQUEST:'data'};
function signed(row:ActivityItem){const amount=row.amount;if(!amount)return null;if(amount.startsWith('-')||amount==='0')return amount;return ['WITHDRAWAL','PURCHASE'].includes(row.type)?'-'+amount:'+'+amount}
export default function Activity({onBack,onSupport,initialReference}:{initialReference?:{type:string;id:string}|null;onBack:()=>void;onSupport:(reference:{referenceType:'DEPOSIT'|'WITHDRAWAL';referenceId:string})=>void}){
 const {t,language}=useLanguage(),locale=intlLocale(language);
 const [filter,setFilter]=useState<string>('ALL'),[rows,setRows]=useState<ActivityItem[]|null>(null),[selected,setSelected]=useState<ActivityItem|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const focusIntent=useRef<{top:number;id:string}|null>(null),referenceHandled=useRef(false),position=useRef(0),opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{let live=true;setRows(null);setError('');void api<{items:ActivityItem[]}>('/v1/activity?type='+filter).then(data=>{if(live)setRows(data.items)}).catch(e=>{if(live)setError((e as Error).message)});return()=>{live=false}},[filter,retry]);
 useEffect(()=>{if(!rows||!initialReference||referenceHandled.current)return;referenceHandled.current=true;const match=rows.find(row=>row.type===initialReference.type&&(row.id===initialReference.id||row.id.split(':').slice(1).join(':')===initialReference.id));if(match)open(match)},[rows,initialReference]);
 function open(row:ActivityItem){position.current=window.scrollY;opener.current=document.getElementById('activity-item-'+row.id)||document.activeElement as HTMLElement;focusIntent.current={top:0,id:'activity-title'};setSelected(row)}
 function back(){focusIntent.current={top:position.current,id:opener.current?.id||'activity-title'};setSelected(null)}
 useLayoutEffect(()=>{const intent=focusIntent.current;if(intent){focusIntent.current=null;window.scrollTo({top:intent.top});document.getElementById(intent.id)?.focus({preventScroll:true})}},[selected]);
 useAppBack(Boolean(selected),back);
 return <section className="production-page" aria-labelledby="activity-title"><PageHeader id="activity-title" title={t(selected?'Детали операции':'История активности')} onBack={selected?back:onBack} backLabel={t(selected?'К списку':'Профиль')}/>
 {selected?<article className="panel production-detail"><StatusPill status={selected.status} label={t(statusLabels[selected.status]||selected.status)}/><dl><div><dt>{t('Тип')}</dt><dd>{t(activityLabels[selected.type]||selected.type)}</dd></div>{selected.amount&&<div><dt>{t('Сумма')}</dt><dd><Money value={signed(selected)!}/></dd></div>}<div><dt>{t('Создан')}</dt><dd>{new Date(selected.createdAt).toLocaleString(locale)}</dd></div>{selected.network&&<div><dt>{t('Сеть')}</dt><dd>{selected.network}</dd></div>}{selected.details.invoiceId&&<div><dt>Invoice ID</dt><dd>{selected.details.invoiceId}</dd></div>}{selected.details.wallet&&<div><dt>{t('Кошелёк')}</dt><dd>{selected.details.wallet}</dd></div>}{selected.details.destination&&<div><dt>{t('Получатель')}</dt><dd>{selected.details.destination}</dd></div>}{selected.details.version&&<div><dt>{t('Редакция')}</dt><dd>{selected.details.version}</dd></div>}{selected.details.node&&<div><dt>{t('Нода')}</dt><dd>{selected.details.node}</dd></div>}{selected.details.confirmedAt&&<div><dt>{t('Подтверждён')}</dt><dd>{new Date(selected.details.confirmedAt).toLocaleString(locale)}</dd></div>}{selected.details.fee&&<div><dt>{t('Комиссия')}</dt><dd><Money value={selected.details.fee}/></dd></div>}{selected.details.txHash&&<div><dt>Transaction hash</dt><dd><a href={'https://tonviewer.com/transaction/'+selected.details.txHash} target="_blank" rel="noopener noreferrer">{shortHash(selected.details.txHash)} ↗</a></dd></div>}{selected.details.rejectionReason&&<div><dt>{t('Причина отказа')}</dt><dd>{selected.details.rejectionReason}</dd></div>}</dl>{(selected.type==='DEPOSIT'||selected.type==='WITHDRAWAL')&&<button className="secondary" onClick={()=>onSupport({referenceType:selected.type as 'DEPOSIT'|'WITHDRAWAL',referenceId:selected.id.split(':')[1]})}>{t('Сообщить о проблеме')}</button>}</article>:<>
  <div className="production-filters" aria-label={t('Фильтр операций')}>{filters.map(([id,label])=><button key={id} className={filter===id?'active':''} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{t(label)}</button>)}</div>
  {error&&<div className="production-problem" role="alert"><p>{error}</p><button className="secondary" onClick={()=>setRetry(v=>v+1)}>{t('Повторить')}</button></div>}
  {rows===null&&!error?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/><i/></div>:rows&&!rows.length?<EmptyState icon="history" title={t('Операций пока нет')} description={t('Регистрация, тарифы и финансовые операции появятся здесь.')}/>:<div className="ui-list-group activity-list">{rows?.map(row=><ListRow key={row.id} id={'activity-item-'+row.id} icon={icons[row.type]||'receipt'} title={t(activityLabels[row.type]||row.type)} description={`${new Date(row.createdAt).toLocaleString(locale)}${row.network?' · '+row.network:''}`} value={<span className="activity-value">{signed(row)&&<Money value={signed(row)!}/>}<StatusPill status={row.status} label={t(statusLabels[row.status]||row.status)}/></span>} onClick={()=>open(row)}/>)}</div>}
 </>}
 </section>;
}
