declare global {interface Window{Telegram?:{WebApp:{initData:string;isExpanded?:boolean;isActive?:boolean;platform?:string;version?:string;ready:()=>void;expand:()=>void;onEvent?:(event:string,callback:()=>void)=>void;offEvent?:(event:string,callback:()=>void)=>void;setHeaderColor?:(s:string)=>void;setBackgroundColor?:(s:string)=>void;HapticFeedback?:{impactOccurred:(s:string)=>void};openTelegramLink?:(s:string)=>void}}}}
let token='';export const setToken=(v:string)=>{token=v;try{if(v)sessionStorage.setItem('aethermind.session',v);else sessionStorage.removeItem('aethermind.session');}catch{}};
export function savedToken(){try{return sessionStorage.getItem('aethermind.session')||'';}catch{return '';}}
export async function api<T=any>(path:string,body?:unknown,method=body?'POST':'GET'):Promise<T>{
  const response=await fetch('/api'+path,{method,signal:AbortSignal.timeout(15000),headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});
  const data=await response.json();if(!response.ok)throw Error(data.message||'Запрос не выполнен.');return data;
}
export function haptic(){try{window.Telegram?.WebApp.HapticFeedback?.impactOccurred('light');}catch{/* unsupported client */}}
export type NodeSpec={id:string;name:string;label:string;memory:string|null;compute:string|null;use:string;image:string;status:string;price:null};
export type RequestItem={id:string;nodeId:string;profile:string;workload:string;status:string;decision?:string|null;closureReason?:string|null;closedAt?:string|null;createdAt:string;user?:{name:string}};
export type Ticket={id:string;message:string;reply:string|null;category:string;subject:string;status:string;createdAt:string;updatedAt:string;user?:{name:string}};
export type OfferTariff={nodeId:string;id:string;name:string;depositUsdt:string;days:number;dailyPercent:string|null;dailyUsdt:string|null;compoundPercent:string|null;termPercent:string|null;termYieldUsdt:string|null;available:boolean;selectedAt?:string|null};
export type JourneyStep={id:'REGISTERED'|'TARIFF'|'FUNDED'|'ORDERED'|'WITHDRAW';title:string;description:string;state:'DONE'|'CURRENT'|'WAITING'|'LOCKED';available:boolean};
export type ReferralItem={id:string;label:string;stage:'REGISTERED'|'OFFER_ACCEPTED'|'TARIFF_SELECTED'|'ACTIVE';joinedAt:string};
export type Account={user:{id:string;name:string;username?:string|null;isOwner:boolean};agreement:{version:string;accepted:boolean;acceptedAt:string|null};offer:{number:string;version:string;documentSha256:string;accepted:boolean;acceptedAt:string|null};balance:string;earnedToday:null;selectedTariff:OfferTariff|null;journey:JourneyStep[];activeNodes:{id:string;status:string;createdAt:string;expiresAt:string;node:{name:string}}[];requests:RequestItem[];tickets:Ticket[];referrals:{total:number;active:number;rewardConfigured:boolean;items:ReferralItem[]};entries:{id:string;amount:string;kind:string;createdAt:string}[];paymentsEnabled:boolean;accrualEnabled:boolean;updatedAt:string};
