import {browserLanguage} from './i18n';
import {translations} from './translations';
import {productionTranslations} from './production-translations';
declare global {interface Window{Telegram?:{WebApp:{initData:string;isExpanded?:boolean;isActive?:boolean;platform?:string;version?:string;safeAreaInset?:{top:number;right:number;bottom:number;left:number};contentSafeAreaInset?:{top:number;right:number;bottom:number;left:number};BackButton?:{show:()=>void;hide:()=>void;onClick:(callback:()=>void)=>void;offClick:(callback:()=>void)=>void};SettingsButton?:{show:()=>void;hide:()=>void;onClick:(callback:()=>void)=>void;offClick:(callback:()=>void)=>void};ready:()=>void;expand:()=>void;onEvent?:(event:string,callback:()=>void)=>void;offEvent?:(event:string,callback:()=>void)=>void;setHeaderColor?:(s:string)=>void;setBackgroundColor?:(s:string)=>void;HapticFeedback?:{impactOccurred:(s:string)=>void};openTelegramLink?:(s:string)=>void}}}}
let token='';export const setToken=(v:string)=>{token=v;try{if(v)sessionStorage.setItem('aethermind.session',v);else sessionStorage.removeItem('aethermind.session');}catch{}};
const financialErrors:Record<string,string>={CURRENT_OFFER_REQUIRED:'Примите новую редакцию оферты для заказа.',PURCHASES_PAUSED:'Заказы временно приостановлены.',INSUFFICIENT_BALANCE:'Недостаточно доступного баланса. Средства активного Epoch не входят в доступный баланс.',SOLD_OUT:'Свободных слотов пока нет.',USER_LIMIT:'Лимит нод для пользователя достигнут.',ACTIVE_LEASE_EXISTS:'Дождитесь завершения текущего Epoch.',ORDER_ALREADY_EXISTS:'У вас уже есть открытый заказ.',LEASE_NOT_ACTIVE:'Epoch ещё не активен.',COMPOUND_LOCKED:'Досрочная расшнуровка недоступна: активирован Compound Boost.',EPOCH_COMPLETED:'Epoch завершён. Ожидайте окончательного расчёта.',EARLY_UNBONDING_DISABLED:'Досрочное завершение временно приостановлено.',ACCRUAL_PAUSED:'Начисления временно приостановлены.',LEGACY_TERMS_REVIEW:'Условия старой ноды требуют проверки оператором.',CATALOG_TERMS_MISMATCH:'Условия тарифа временно недоступны.',SUPPLY_RECONCILIATION_REQUIRED:'Заказ требует проверки оператором.'};
export function savedToken(){try{return sessionStorage.getItem('aethermind.session')||'';}catch{return '';}}
export async function api<T=any>(path:string,body?:unknown,method=body?'POST':'GET'):Promise<T>{
  let response:Response;
  try{response=await fetch('/api'+path,{method,signal:AbortSignal.timeout(15000),headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined})}
  catch{const language=browserLanguage()||'ru';throw Error(language==='en'?'Cannot connect to the server. Try again.':language==='ro'?'Nu ne putem conecta la server. Încearcă din nou.':'Нет связи с сервером. Повторите попытку.')}
  let data:Record<string,any>;try{data=await response.json()}catch{data={message:'Запрос не выполнен.'}}if(!response.ok){
    if(response.status===401&&token){setToken('');window.dispatchEvent(new Event('aethermind:session-expired'))}
    const language=browserLanguage()||'ru';
    const original=typeof data.code==='string'&&financialErrors[data.code]?financialErrors[data.code]:typeof data.message==='string'?data.message:'Запрос не выполнен.';
    const field=original.match(/^Проверьте поле ([a-zA-Z]+)\.$/);
    const translated=language==='ru'?original:field?(language==='en'?`Check the ${field[1]} field.`:`Verifică câmpul ${field[1]}.`):(translations[original]||productionTranslations[original])?.[language==='en'?0:1]||( /[А-Яа-яЁё]/.test(original)?translations['Запрос не выполнен.'][language==='en'?0:1]:original);
    throw Error(translated);
  }return data as T;
}
export function haptic(){try{window.Telegram?.WebApp.HapticFeedback?.impactOccurred('light');}catch{/* unsupported client */}}
export type NodeSpec={id:string;name:string;label:string;memory:string|null;compute:string|null;use:string;image:string;status:string;price:null};
export type RequestItem={id:string;nodeId:string;profile:string;workload:string;paymentStatus:'WAITING'|'PAID';userUnread:boolean;status:string;decision?:string|null;closureReason?:string|null;closedAt?:string|null;createdAt:string;updatedAt:string;equipment?:{id:string;name:string};user?:{id:string;name:string;username?:string|null}};
export type TicketMessage={id:string;authorType:'USER'|'OWNER';authorId?:string;body:string;createdAt:string};
export type Ticket={id:string;category:'QUESTION'|'PAYMENT'|'WITHDRAWAL'|'ACCOUNT'|'WALLET'|'NODE'|'TECHNICAL'|'OTHER'|'COMPLAINT';subject:string;referenceType?:string|null;referenceId?:string|null;status:'OPEN'|'IN_PROGRESS'|'ANSWERED'|'CLOSED';ownerUnread?:boolean;userUnread:boolean;lastMessageAt:string;createdAt:string;updatedAt:string;messages:TicketMessage[];_count?:{messages:number};user?:{id:string;name:string;username?:string|null}};
export type OfferTariff={nodeId:string;id:string;name:string;depositUsdt:string;days:number;dailyPercent:string|null;dailyUsdt:string|null;compoundPercent:string|null;termPercent:string|null;termYieldUsdt:string|null;available:boolean;selectedAt?:string|null};
export type JourneyStep={id:'REGISTERED'|'TARIFF'|'FUNDED'|'ORDERED'|'WITHDRAW';title:string;description:string;state:'DONE'|'CURRENT'|'WAITING'|'LOCKED';available:boolean};
export type ReferralItem={id:string;label:string;stage:'REGISTERED'|'OFFER_ACCEPTED'|'TARIFF_SELECTED'|'ACTIVE';joinedAt:string};
export type Lease={id:string;userId:string;nodeId:string;status:string;createdAt:string;expiresAt:string|null;activatedAt:string|null;epochEndsAt:string|null;completedAt:string|null;node?:{name:string};offerVersion:string|null;mode:'BASE'|'COMPOUND'|null;principal:string|null;baseDailyRateBps:number|null;compoundDailyRateBps:number|null;contractDays:number|null;settledDays:number;baseAccrued:string|null;compoundCapital:string|null;compoundProfit:string|null;currentCompoundBlock:number;compoundBlockEndsAt:string|null;unbondFee:string|null;legacyTermsReview:boolean};
export type FinancialOffer={version:string;sha256:string;publishedAt:string;documentUrl:string;accepted:boolean;acceptedAt:string|null};
export type Account={user:{id:string;name:string;username?:string|null;createdAt:string;isOwner:boolean;preferredLanguage?:'ru'|'en'|'ro'|null};agreement:{version:string;accepted:boolean;acceptedAt:string|null};offer:{number:string;version:string;documentSha256:string;accepted:boolean;acceptedAt:string|null};financialOffer:FinancialOffer|null;balance:string;lockedBase:string;lockedCompound:string;earnedToday:null;selectedTariff:OfferTariff|null;nextAction:{kind:'SELECT_TARIFF'|'ADD_FUNDS'|'REQUEST_PENDING'|'PROVISIONING'|'EPOCH_ACTIVE'|'EPOCH_COMPLETED'|'WITHDRAW_MANUAL'|'ORDER_UNAVAILABLE'|'ORDER_SOLD_OUT'|'ORDER_READY'|'CURRENT_OFFER_REQUIRED';tariff?:string;required?:string;missing?:string};journey:JourneyStep[];activeNodes:Lease[];requests:RequestItem[];tickets:Ticket[];notifications:{unreadSupport:number;unreadOrders:number;unread:number};referrals:{total:number;active:number;rewardConfigured:boolean;items:ReferralItem[]};entries:{id:string;amount:string;kind:string;createdAt:string}[];paymentsEnabled:boolean;accrualEnabled:boolean;compoundEnabled:boolean;purchasesEnabled:boolean;updatedAt:string};
