import {useLanguage,intlLocale} from './i18n';
import LanguagePicker from './LanguagePicker';
import {useEffect,useRef,useState} from 'react';
import {CountUp} from 'countup.js';
import lottie from 'lottie-web/build/player/lottie_light';
import {useAmbientMotion} from './motion';
import CoreVisual from './CoreVisual';
import OwnerPanel from './OwnerPanel';
import SupportPanel from './SupportPanel';
import Market from './Market';
import Profile from './Profile';
import Referrals from './Referrals';
import BrowserLogin from './BrowserLogin';
import {AGREEMENT_VERSION,AgreementDocument,AgreementGate} from './Agreement';
import {OFFER_DOCUMENT_SHA256,OFFER_VERSION,OfferDocument,OfferGate} from './Offer';
import {api,setToken,savedToken,haptic,type Account} from './api';
import {Icon} from './Icons';
import './owner.css';
import './entry.css';
import './agreement.css';
import './app-v2.css';

function Counter({value}:{value:string}){const {language}=useLanguage();const ref=useRef<HTMLSpanElement>(null);const whole=Math.floor(Number(value));useEffect(()=>{if(!ref.current)return;const n=new CountUp(ref.current,whole,{decimalPlaces:0,duration:.65,useEasing:true});if(matchMedia('(prefers-reduced-motion: reduce)').matches)ref.current.textContent=whole.toLocaleString(intlLocale(language));else n.start();return()=>n.reset()},[whole,language]);return <span ref={ref}>{whole.toLocaleString(intlLocale(language))}</span>}
function Splash(){const {t}=useLanguage();const el=useRef<HTMLDivElement>(null);useEffect(()=>{if(!el.current||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const anim=lottie.loadAnimation({container:el.current,renderer:'svg',loop:true,autoplay:true,path:'/assets/splash.json'});return()=>anim.destroy()},[]);return <div className="splash"><div ref={el} className="splash-ring"/><img src="/assets/core.webp" alt={t("Нейронное ядро")} draggable={false}/><p>{t("Соединяем с AetherMind…")}</p></div>}

export default function App(){
 useAmbientMotion();
 const {t,language,chosen}=useLanguage();
 const [tab,setTab]=useState('dashboard'),[entered,setEntered]=useState(false),[bot,setBot]=useState(''),[account,setAccount]=useState<Account|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[accepting,setAccepting]=useState(false),[ordering,setOrdering]=useState(false);
 const orderKey=useRef<string>('');
 const inTelegram=Boolean(window.Telegram?.WebApp.initData),returnModal=useRef(''),modalRef=useRef<HTMLDivElement>(null);
 async function loadCatalog(){try{const c=await api('/catalog');setBot(c.botUsername)}catch{setError(t('Нет связи с API. Проверьте соединение и повторите.'))}}
 async function refresh(){setAccount(await api<Account>('/me'))}
 async function login(){setError('');const raw=window.Telegram?.WebApp.initData;if(!raw){returnModal.current=modal;setModal('browser-login');return}setLoading(true);try{const r=await api('/auth/telegram',{initData:raw});setToken(r.token);await refresh()}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{const tg=window.Telegram?.WebApp;const expand=()=>{try{tg?.expand()}catch{}};tg?.ready();expand();const retry=setTimeout(expand,350);try{tg?.setHeaderColor?.('#07080E');tg?.setBackgroundColor?.('#07080E')}catch{}void loadCatalog();if(tg?.initData)void login();else{const saved=savedToken();if(saved){setToken(saved);void refresh().catch(()=>setToken(''))}}return()=>clearTimeout(retry)},[]);
 useEffect(()=>{if(!account)return;const id=setInterval(()=>{if(document.visibilityState==='visible')refresh().catch(e=>setError(e.message))},30000);return()=>clearInterval(id)},[account?.user.id]);
 useEffect(()=>{if(!chosen||!account||account.user.preferredLanguage===language)return;let active=true;void api('/me/language',{language},'PATCH').then(()=>{if(active)setAccount(previous=>previous&&previous.user.id===account.user.id?{...previous,user:{...previous.user,preferredLanguage:language}}:previous)}).catch(()=>{/* retry after refresh */});return()=>{active=false}},[account?.user.id,account?.user.preferredLanguage,language,chosen]);
 useEffect(()=>{if(!modal)return;const old=document.activeElement as HTMLElement;modalRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal('');if(e.key==='Tab'){const list=modalRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]');if(!list?.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}};document.addEventListener('keydown',key);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;old?.focus()}},[modal]);
 function navigate(next:string){haptic();setTab(next);setEntered(true)}
 async function acceptAgreement(){setAccepting(true);setError('');try{await api('/agreement/accept',{version:AGREEMENT_VERSION});await refresh()}catch(e){setError((e as Error).message)}finally{setAccepting(false)}}
 async function acceptOffer(){setAccepting(true);setError('');try{await api('/offer/accept',{version:OFFER_VERSION,documentSha256:OFFER_DOCUMENT_SHA256,readConfirmed:true});await refresh();setNotice(t('Акцепт оферты зафиксирован в профиле.'))}catch(e){setError((e as Error).message)}finally{setAccepting(false)}}
 async function submitTestOrder(){if(ordering)return;setOrdering(true);setError('');try{if(!orderKey.current)orderKey.current=crypto.randomUUID();await api('/test/orders',{idempotencyKey:orderKey.current});orderKey.current='';await refresh();setModal('');setNotice(t('Тестовый заказ передан владельцу на подтверждение.'))}catch(e){setError((e as Error).message)}finally{setOrdering(false)}}
 async function readOrders(){try{await api('/test/orders/read',{});await refresh()}catch(e){setError((e as Error).message)}}
 const alerts=<>{error&&<div className="alert error" role="alert">{error}<button aria-label={t("Закрыть")} onClick={()=>setError('')}><Icon name="close" size={18}/></button></div>}{notice&&<div className="alert" role="status">{notice}<button aria-label={t("Закрыть")} onClick={()=>setNotice('')}><Icon name="close" size={18}/></button></div>}</>;
 if(!chosen)return <LanguagePicker/>;
 if(loading)return <Splash/>;
 if(account&&!account.agreement.accepted)return <AgreementGate busy={accepting} error={error} onAccept={acceptAgreement}/>;
 if(account&&!account.offer.accepted)return <OfferGate busy={accepting} error={error} onAccept={acceptOffer}/>;
 return <div className="app-shell" onContextMenu={e=>{if((e.target as HTMLElement).closest('img,.core-visual'))e.preventDefault()}} onDragStart={e=>{if((e.target as HTMLElement).closest('img'))e.preventDefault()}}>
  <header className="topbar"><button className="brand" onClick={()=>{setEntered(false);haptic()}} aria-label={t("AetherMind — начало")}><img src="/assets/icons/icon-72.png" alt=""/><span>Aether<span className="cyan">Mind</span><small>{t("DECENTRALIZED GPU NETWORK")}</small></span></button><button className="icon-button support-button" aria-label={`${t('Техническая поддержка')}${account?.notifications.unreadSupport?`, ${t('непрочитанных ответов:')} ${account.notifications.unreadSupport}`:''}`} onClick={()=>setModal('support')}><Icon name="help"/>{Boolean(account?.notifications.unreadSupport)&&<span className="notify-badge">{Math.min(account!.notifications.unreadSupport,99)}</span>}</button></header>
  {!modal&&alerts}
  {!entered?<main className="welcome welcome-v2"><div className="eyebrow"><i/> DePIN GPU INFRASTRUCTURE</div><CoreVisual/><h1>{t("Вычислительная сеть.")}<br/><span className="gradient">{t("Ваше участие.")}</span></h1><p className="lead">{t("Выберите фиксированный тариф. AetherMind назначает оборудование, обслуживает кластер и распределяет B2B-задачи.")}</p><div className="welcome-features"><span><Icon name="shield" size={17}/> {t("Оферта № 88/2026-AI")}</span><span><Icon name="node" size={17}/> {t("Фиксированный Epoch")}</span><span><Icon name="grid" size={17}/> {t("Путь в профиле")}</span></div><button className="primary shimmer" onClick={()=>navigate(account?.selectedTariff?'dashboard':'nodes')}>{t("Начать зарабатывать")} <Icon name="arrow"/></button>{!inTelegram&&!account&&<button className="ghost wide" onClick={()=>void login()}>{t("Войти через Telegram")}</button>}{account&&<button className="ghost wide" onClick={()=>navigate('dashboard')}>{t("Открыть профиль")}</button>}<p className="fine">{t("Тестовые заказы доступны после начисления тестовых средств владельцем. Реальные платежи и начисления не включены.")}</p><div className="welcome-links"><button className="text-button" onClick={()=>setModal('offer')}>{t("Публичная оферта")}</button><button className="text-button" onClick={()=>setModal('agreement')}>{t("Пользовательское соглашение")}</button><button className="text-button" onClick={()=>setModal('terms')}>{t("Как это работает")}</button></div></main>:<main className="workspace">
   {tab==='dashboard'&&(account?<Profile account={account} onMarket={()=>navigate('nodes')} onFunding={()=>setModal('payments')} onOrder={()=>setModal('order')} onWithdraw={()=>setModal('withdraw')} onOffer={()=>setModal('offer')} onReadOrders={()=>void readOrders()}/>:<section className="empty panel account-required"><Icon name="user" size={34}/><h2>{t("Войдите в профиль")}</h2><p>{t("Авторизация через Telegram нужна, чтобы сохранять этапы и выбранный тариф.")}</p><button className="primary" onClick={()=>void login()}>{t("Войти через Telegram")}</button></section>)}
   {tab==='nodes'&&<Market authenticated={Boolean(account)} selectedId={account?.selectedTariff?.nodeId} onLogin={()=>void login()} onSelected={refresh} onNotice={setNotice} onError={setError}/>}
   {tab==='cluster'&&(account?<Referrals account={account} bot={bot} onNotice={setNotice} onError={setError}/>:<section className="empty panel account-required"><Icon name="users" size={34}/><h2>{t("Партнёрская сеть")}</h2><p>{t("Войдите, чтобы получить персональную ссылку.")}</p><button className="primary" onClick={()=>void login()}>{t("Войти через Telegram")}</button></section>)}
   {tab==='wallet'&&<><div className="section-title"><h1>{t("Финансы")}</h1><span className="micro">{t("USDT LEDGER / 04")}</span></div><section className="panel balance-card"><span>{t("Внутренний учётный баланс")}</span><div className="balance"><Counter value={account?.balance||'0'}/><small>USDT</small></div><div className="actions"><button className="primary" onClick={()=>account?setModal('payments'):void login()}><Icon name="plus"/> {t("Пополнить")}</button><button className="secondary" onClick={()=>account?setModal('withdraw'):void login()}><Icon name="arrow"/> {t("Вывести")}</button></div></section><section className="panel wallet-test"><span>{t("Тестовый баланс")}</span><b>{Math.floor(Number(account?.testBalance||0))} USDT</b><p>{t("Только для проверки заказов. Не выводится и не приносит доход.")}</p></section><div className="notice-block"><Icon name="shield"/><p>{t("Баланс ведётся во внутреннем учёте USDT. Платёжный провайдер и вывод пока не подключены. Токен AETHER в интерфейсе не используется.")}</p></div><div className="section-title"><h2>{t("История операций")}</h2><span className="micro">{t("CONFIRMED ONLY")}</span></div>{account?.entries.length?account.entries.map(e=><div className="panel request" key={e.id}><b>{e.amount} USDT</b><p>{t(e.kind)}</p></div>):<div className="panel empty"><Icon name="wallet" size={32}/><h3>{t("Операций пока нет")}</h3><p>{t("Здесь появятся только подтверждённые записи платёжного сервиса.")}</p></div>}</>}
   {tab==='owner'&&account?.user.isOwner&&<OwnerPanel onRefresh={refresh}/>}
   <footer><button className="text-button" onClick={()=>setModal('offer')}>{t("Публичная оферта")}</button><button className="text-button" onClick={()=>setModal('agreement')}>{t("Соглашение")}</button><button className="text-button" onClick={()=>setModal('terms')}>{t("Регламент")}</button><span>AETHERMIND / DePIN</span></footer>
  </main>}
  {entered&&<nav className={`bottom-nav ${account?.user.isOwner?'owner-nav':''}`} aria-label={t("Основная навигация")}>{[...([['dashboard','user',t('Профиль')],['nodes','node',t('Тарифы')],['cluster','users',t('Партнёры')],['wallet','wallet',t('Финансы')]] as string[][]),...(account?.user.isOwner?[['owner','grid',t('Управление')]]:[])].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>navigate(id)}><Icon name={icon}/><span>{label}</span>{id==='owner'&&Boolean((account?.notifications.unreadSupport||0)+(account?.notifications.pendingTestOrders||0))&&<span className="nav-dot"/>}</button>)}</nav>}
  {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!accepting)setModal('')}}><div className={`modal panel ${modal==='agreement'?'agreement-modal':modal==='offer'?'offer-modal':''}`} role="dialog" aria-modal="true" aria-label={t("Информация AetherMind")} tabIndex={-1} ref={modalRef}><button className="modal-close icon-button" aria-label={t("Закрыть")} onClick={()=>setModal('')}><Icon name="close"/></button>{alerts}
   {modal==='browser-login'&&<BrowserLogin onSuccess={async token=>{setToken(token);await refresh();setModal(returnModal.current);setNotice(t('Вход через Telegram выполнен.'))}}/>}
   {modal==='support'&&(account?<SupportPanel tickets={account.tickets} onRefresh={refresh}/>:<><h2>{t("Войдите для обращения")}</h2><button className="primary wide" onClick={()=>void login()}>{t("Войти через Telegram")}</button></>)}
   {modal==='payments'&&<><Icon name="wallet" size={38}/><h2>{t("Пополнение готовится")}</h2><p>{t("Платёжный провайдер ещё не подключён, поэтому адреса, QR-коды и заявки на депозит не создаются.")}</p><p className="fine">{t("Выбранный тариф сохранён. До подтверждённого пополнения баланс, Epoch и расчёт доходности не запускаются.")}</p></>}
   {modal==='order'&&<><Icon name="node" size={38}/><h2>{t("Проверка тестового заказа")}</h2>{account?.selectedTariff?<><p><b>{account.selectedTariff.name}</b> · {account.selectedTariff.depositUsdt} USDT</p><p>{t("Тестовый баланс")}: {Math.floor(Number(account.testBalance))} USDT</p>{account.requests.some(r=>r.isTestOrder&&['REQUESTED','REVIEWED'].includes(r.status))?<p className="fine">{t("Ваш заказ уже ожидает решения владельца.")}</p>:Number(account.testBalance)<Number(account.selectedTariff.depositUsdt)?<p className="fine">{t("Недостаточно тестовых USDT. Обратитесь к владельцу для тестового начисления.")}</p>:<button className="primary wide" disabled={ordering} onClick={()=>void submitTestOrder()}>{ordering?t('Отправка…'):t('Заказать на проверку')}</button>}</>:<button className="secondary" onClick={()=>{setModal('');navigate('nodes')}}>{t("Выбрать тариф")}</button>}<p className="fine">{t("Тестовые средства не являются депозитом. Одобрение не запускает GPU, Epoch или начисления.")}</p></>}
   {modal==='withdraw'&&<><Icon name="lock" size={38}/><h2>{t("Вывод пока недоступен")}</h2><p>{t("Этап вывода открывается после завершения Epoch. Модуль выплат ещё не подключён, средства и баланс сейчас не изменяются.")}</p></>}
   {modal==='offer'&&<OfferDocument/>}
   {modal==='agreement'&&<AgreementDocument/>}
   {modal==='terms'&&<><span className="eyebrow">{t("ПУТЬ ПРОВАЙДЕРА НОДЫ")}</span><h2>{t("Как работает AetherMind")}</h2><ol><li>{t("Регистрация через Telegram и однократный акцепт документов.")}</li><li>{t("Выбор фиксированного тарифа по оферте.")}</li><li>{t("После подключения платёжного модуля — подтверждённое пополнение USDT.")}</li><li>{t("Заказ слота: Оператор назначает оборудование и запускает Epoch.")}</li><li>{t("После завершения Epoch — доступ к выводу через подключённый платёжный модуль.")}</li></ol><p>{t("Пользователь не выбирает режим производительности или задачи. Оператор управляет инфраструктурой и распределением B2B-нагрузки.")}</p></>}
  </div></div>}
 </div>
}
