import {useEffect,useRef,useState} from 'react';
import {CountUp} from 'countup.js';
import lottie from 'lottie-web/build/player/lottie_light';
import {useAmbientMotion} from './motion';
import CoreVisual from './CoreVisual';
import OwnerPanel from './OwnerPanel';
import SupportPanel from './SupportPanel';
import Market from './Market';
import Profile from './Profile';
import Referrals from './Referrals';
import BrowserLogin from './BrowserLogin';
import {AGREEMENT_VERSION,AgreementDocument,AgreementGate} from './Agreement';
import {OFFER_DOCUMENT_SHA256,OFFER_VERSION,OfferDocument,OfferGate} from './Offer';
import {api,setToken,savedToken,haptic,type Account} from './api';
import {Icon} from './Icons';
import './owner.css';
import './entry.css';
import './agreement.css';
import './app-v2.css';

function Counter({value}:{value:string}){const ref=useRef<HTMLSpanElement>(null);const whole=Math.floor(Number(value));useEffect(()=>{if(!ref.current)return;const n=new CountUp(ref.current,whole,{decimalPlaces:0,duration:.65,useEasing:true});if(matchMedia('(prefers-reduced-motion: reduce)').matches)ref.current.textContent=whole.toLocaleString('ru-RU');else n.start();return()=>n.reset()},[whole]);return <span ref={ref}>{whole.toLocaleString('ru-RU')}</span>}
function Splash(){const el=useRef<HTMLDivElement>(null);useEffect(()=>{if(!el.current||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const anim=lottie.loadAnimation({container:el.current,renderer:'svg',loop:true,autoplay:true,path:'/assets/splash.json'});return()=>anim.destroy()},[]);return <div className="splash"><div ref={el} className="splash-ring"/><img src="/assets/core.webp" alt="Нейронное ядро" draggable={false}/><p>Соединяем с AetherMind…</p></div>}

export default function App(){
 useAmbientMotion();
 const [tab,setTab]=useState('dashboard'),[entered,setEntered]=useState(false),[bot,setBot]=useState(''),[account,setAccount]=useState<Account|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[accepting,setAccepting]=useState(false);
 const inTelegram=Boolean(window.Telegram?.WebApp.initData),returnModal=useRef(''),modalRef=useRef<HTMLDivElement>(null);
 async function loadCatalog(){try{const c=await api('/catalog');setBot(c.botUsername)}catch{setError('Нет связи с API. Проверьте соединение и повторите.')}}
 async function refresh(){setAccount(await api<Account>('/me'))}
 async function login(){setError('');const raw=window.Telegram?.WebApp.initData;if(!raw){returnModal.current=modal;setModal('browser-login');return}setLoading(true);try{const r=await api('/auth/telegram',{initData:raw});setToken(r.token);await refresh()}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{const tg=window.Telegram?.WebApp;const expand=()=>{try{tg?.expand()}catch{}};tg?.ready();expand();const retry=setTimeout(expand,350);try{tg?.setHeaderColor?.('#07080E');tg?.setBackgroundColor?.('#07080E')}catch{}void loadCatalog();if(tg?.initData)void login();else{const saved=savedToken();if(saved){setToken(saved);void refresh().catch(()=>setToken(''))}}return()=>clearTimeout(retry)},[]);
 useEffect(()=>{if(!account)return;const id=setInterval(()=>{if(document.visibilityState==='visible')refresh().catch(e=>setError(e.message))},30000);return()=>clearInterval(id)},[account?.user.id]);
 useEffect(()=>{if(!modal)return;const old=document.activeElement as HTMLElement;modalRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal('');if(e.key==='Tab'){const list=modalRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]');if(!list?.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}};document.addEventListener('keydown',key);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;old?.focus()}},[modal]);
 function navigate(next:string){haptic();setTab(next);setEntered(true)}
 async function acceptAgreement(){setAccepting(true);setError('');try{await api('/agreement/accept',{version:AGREEMENT_VERSION});await refresh()}catch(e){setError((e as Error).message)}finally{setAccepting(false)}}
 async function acceptOffer(){setAccepting(true);setError('');try{await api('/offer/accept',{version:OFFER_VERSION,documentSha256:OFFER_DOCUMENT_SHA256,readConfirmed:true});await refresh();setNotice('Акцепт оферты зафиксирован в профиле.')}catch(e){setError((e as Error).message)}finally{setAccepting(false)}}
 const alerts=<>{error&&<div className="alert error" role="alert">{error}<button aria-label="Закрыть" onClick={()=>setError('')}><Icon name="close" size={18}/></button></div>}{notice&&<div className="alert" role="status">{notice}<button aria-label="Закрыть" onClick={()=>setNotice('')}><Icon name="close" size={18}/></button></div>}</>;
 if(loading)return <Splash/>;
 if(account&&!account.agreement.accepted)return <AgreementGate busy={accepting} error={error} onAccept={acceptAgreement}/>;
 if(account&&!account.offer.accepted)return <OfferGate busy={accepting} error={error} onAccept={acceptOffer}/>;
 return <div className="app-shell" onContextMenu={e=>{if((e.target as HTMLElement).closest('img,.core-visual'))e.preventDefault()}} onDragStart={e=>{if((e.target as HTMLElement).closest('img'))e.preventDefault()}}>
  <header className="topbar"><button className="brand" onClick={()=>{setEntered(false);haptic()}} aria-label="AetherMind — начало"><img src="/assets/icons/icon-72.png" alt=""/><span>Aether<span className="cyan">Mind</span><small>DECENTRALIZED GPU NETWORK</small></span></button><button className="icon-button" aria-label="Техническая поддержка" onClick={()=>setModal('support')}><Icon name="help"/></button></header>
  {!modal&&alerts}
  {!entered?<main className="welcome welcome-v2"><div className="eyebrow"><i/> DePIN GPU INFRASTRUCTURE</div><CoreVisual/><h1>Вычислительная сеть.<br/><span className="gradient">Ваше участие.</span></h1><p className="lead">Выберите фиксированный тариф. AetherMind назначает оборудование, обслуживает кластер и распределяет B2B-задачи.</p><div className="welcome-features"><span><Icon name="shield" size={17}/> Оферта № 88/2026-AI</span><span><Icon name="node" size={17}/> Фиксированный Epoch</span><span><Icon name="grid" size={17}/> Путь в профиле</span></div><button className="primary shimmer" onClick={()=>navigate(account?.selectedTariff?'dashboard':'nodes')}>Начать зарабатывать <Icon name="arrow"/></button>{!inTelegram&&!account&&<button className="ghost wide" onClick={()=>void login()}>Войти через Telegram</button>}{account&&<button className="ghost wide" onClick={()=>navigate('dashboard')}>Открыть профиль</button>}<p className="fine">Сейчас доступны акцепт и выбор тарифа. Пополнение, списания и начисления ещё не включены.</p><div className="welcome-links"><button className="text-button" onClick={()=>setModal('offer')}>Публичная оферта</button><button className="text-button" onClick={()=>setModal('agreement')}>Пользовательское соглашение</button><button className="text-button" onClick={()=>setModal('terms')}>Как это работает</button></div></main>:<main className="workspace">
   {tab==='dashboard'&&(account?<Profile account={account} onMarket={()=>navigate('nodes')} onFunding={()=>setModal('payments')} onOrder={()=>setModal('order')} onWithdraw={()=>setModal('withdraw')} onOffer={()=>setModal('offer')}/>:<section className="empty panel account-required"><Icon name="user" size={34}/><h2>Войдите в профиль</h2><p>Авторизация через Telegram нужна, чтобы сохранять этапы и выбранный тариф.</p><button className="primary" onClick={()=>void login()}>Войти через Telegram</button></section>)}
   {tab==='nodes'&&<Market authenticated={Boolean(account)} selectedId={account?.selectedTariff?.nodeId} onLogin={()=>void login()} onSelected={refresh} onNotice={setNotice} onError={setError}/>}
   {tab==='cluster'&&(account?<Referrals account={account} bot={bot} onNotice={setNotice} onError={setError}/>:<section className="empty panel account-required"><Icon name="users" size={34}/><h2>Партнёрская сеть</h2><p>Войдите, чтобы получить персональную ссылку.</p><button className="primary" onClick={()=>void login()}>Войти через Telegram</button></section>)}
   {tab==='wallet'&&<><div className="section-title"><h1>Финансы</h1><span className="micro">USDT LEDGER / 04</span></div><section className="panel balance-card"><span>Внутренний учётный баланс</span><div className="balance"><Counter value={account?.balance||'0'}/><small>USDT</small></div><div className="actions"><button className="primary" onClick={()=>account?setModal('payments'):void login()}><Icon name="plus"/> Пополнить</button><button className="secondary" onClick={()=>account?setModal('withdraw'):void login()}><Icon name="arrow"/> Вывести</button></div></section><div className="notice-block"><Icon name="shield"/><p>Баланс ведётся во внутреннем учёте USDT. Платёжный провайдер и вывод пока не подключены. Токен AETHER в интерфейсе не используется.</p></div><div className="section-title"><h2>История операций</h2><span className="micro">CONFIRMED ONLY</span></div>{account?.entries.length?account.entries.map(e=><div className="panel request" key={e.id}><b>{e.amount} USDT</b><p>{e.kind}</p></div>):<div className="panel empty"><Icon name="wallet" size={32}/><h3>Операций пока нет</h3><p>Здесь появятся только подтверждённые записи платёжного сервиса.</p></div>}</>}
   <footer><button className="text-button" onClick={()=>setModal('offer')}>Публичная оферта</button><button className="text-button" onClick={()=>setModal('agreement')}>Соглашение</button><button className="text-button" onClick={()=>setModal('terms')}>Регламент</button>{account?.user.isOwner&&<button className="text-button" onClick={()=>setModal('admin')}>Панель владельца</button>}<span>AETHERMIND / DePIN</span></footer>
  </main>}
  {entered&&<nav className="bottom-nav" aria-label="Основная навигация">{[['dashboard','user','Профиль'],['nodes','node','Тарифы'],['cluster','users','Партнёры'],['wallet','wallet','Финансы']].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>navigate(id)}><Icon name={icon}/><span>{label}</span></button>)}</nav>}
  {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!accepting)setModal('')}}><div className={`modal panel ${modal==='agreement'?'agreement-modal':modal==='offer'?'offer-modal':''}`} role="dialog" aria-modal="true" aria-label="Информация AetherMind" tabIndex={-1} ref={modalRef}><button className="modal-close icon-button" aria-label="Закрыть" onClick={()=>setModal('')}><Icon name="close"/></button>{alerts}
   {modal==='browser-login'&&<BrowserLogin onSuccess={async token=>{setToken(token);await refresh();setModal(returnModal.current);setNotice('Вход через Telegram выполнен.')}}/>}
   {modal==='support'&&(account?<SupportPanel tickets={account.tickets} onRefresh={refresh}/>:<><h2>Войдите для обращения</h2><button className="primary wide" onClick={()=>void login()}>Войти через Telegram</button></>)}
   {modal==='payments'&&<><Icon name="wallet" size={38}/><h2>Пополнение готовится</h2><p>Платёжный провайдер ещё не подключён, поэтому адреса, QR-коды и заявки на депозит не создаются.</p><p className="fine">Выбранный тариф сохранён. До подтверждённого пополнения баланс, Epoch и расчёт доходности не запускаются.</p></>}
   {modal==='order'&&<><Icon name="node" size={38}/><h2>Заказ тарифа пока закрыт</h2><p>Кнопка заказа будет активирована после подключения пополнения и подтверждения депозита на внутреннем USDT-балансе.</p><p className="fine">Оборудование и вычислительные задачи назначает Оператор; профили ECO/Performance не используются.</p></>}
   {modal==='withdraw'&&<><Icon name="lock" size={38}/><h2>Вывод пока недоступен</h2><p>Этап вывода открывается после завершения Epoch. Модуль выплат ещё не подключён, средства и баланс сейчас не изменяются.</p></>}
   {modal==='offer'&&<OfferDocument/>}
   {modal==='agreement'&&<AgreementDocument/>}
   {modal==='terms'&&<><span className="eyebrow">ПУТЬ ПРОВАЙДЕРА НОДЫ</span><h2>Как работает AetherMind</h2><ol><li>Регистрация через Telegram и однократный акцепт документов.</li><li>Выбор фиксированного тарифа по оферте.</li><li>После подключения платёжного модуля — подтверждённое пополнение USDT.</li><li>Заказ слота: Оператор назначает оборудование и запускает Epoch.</li><li>После завершения Epoch — доступ к выводу через подключённый платёжный модуль.</li></ol><p>Пользователь не выбирает режим производительности или задачи. Оператор управляет инфраструктурой и распределением B2B-нагрузки.</p></>}
   {modal==='admin'&&account?.user.isOwner&&<OwnerPanel onRefresh={refresh}/>}
  </div></div>}
 </div>
}
