import {useEffect,useRef,useState} from 'react';import {CountUp} from 'countup.js';import lottie from 'lottie-web/build/player/lottie_light';
import {api,setToken,haptic,Account,NodeSpec,RequestItem,Ticket} from './api';import{Icon}from'./Icons';
const stateLabel:Record<string,string>={REQUESTED:'Ожидает рассмотрения',REVIEWED:'На согласовании',CLOSED:'Закрыта'};
function Counter({value}:{value:string}){const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{if(ref.current){const n=new CountUp(ref.current,Number(value),{decimalPlaces:2,duration:0.65,useEasing:true});if(matchMedia('(prefers-reduced-motion: reduce)').matches)ref.current.textContent=Number(value).toFixed(2);else n.start();return()=>n.reset();}},[value]);return <span ref={ref}>{Number(value).toFixed(2)}</span>}
function Splash(){const el=useRef<HTMLDivElement>(null);useEffect(()=>{if(!el.current||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const anim=lottie.loadAnimation({container:el.current,renderer:'svg',loop:true,autoplay:true,path:'/assets/splash.json'});return()=>anim.destroy();},[]);return <div className="splash"><div ref={el} className="splash-ring"/><img src="/assets/core.webp" alt="Нейронное ядро"/><p>Соединяем с AetherMind…</p></div>}
export default function App(){
 const [tab,setTab]=useState('dashboard'),[entered,setEntered]=useState(false),[nodes,setNodes]=useState<NodeSpec[]>([]),[bot,setBot]=useState(''),[account,setAccount]=useState<Account|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[selected,setSelected]=useState<NodeSpec|null>(null),[profile,setProfile]=useState('BALANCED'),[workload,setWorkload]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[admin,setAdmin]=useState<{users:number;requests:RequestItem[];tickets:Ticket[];audit:{id:string;action:string;actorId:string;targetId:string}[]}|null>(null);
 const key=useRef(crypto.randomUUID());const modalRef=useRef<HTMLDivElement>(null);
 async function loadCatalog(){try{const c=await api('/catalog');setNodes(c.nodes);setBot(c.botUsername);}catch{setError('Нет связи с API. Проверьте соединение и повторите.');}}
 async function refresh(){setAccount(await api<Account>('/me'));}
 async function login(){setError('');const raw=window.Telegram?.WebApp.initData;if(!raw){setError('Для входа откройте приложение через кнопку меню Telegram-бота.');return;}setLoading(true);try{const r=await api('/auth/telegram',{initData:raw});setToken(r.token);await refresh();setEntered(true);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();try{tg?.setHeaderColor?.('#07080E');tg?.setBackgroundColor?.('#07080E');}catch{}void loadCatalog();if(tg?.initData)void login();},[]);
 useEffect(()=>{if(!account)return;const id=setInterval(()=>{if(document.visibilityState==='visible')refresh().catch(e=>setError(e.message));},30000);return()=>clearInterval(id);},[account?.user.id]);
 useEffect(()=>{if(!modal)return;const old=document.activeElement as HTMLElement;modalRef.current?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal('');if(e.key==='Tab'){const list=modalRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input, select, textarea, a[href]');if(!list?.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}};document.addEventListener('keydown',handle);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handle);document.body.style.overflow=overflow;old?.focus();};},[modal]);
 function navigate(t:string){haptic();setTab(t);setEntered(true);}
 function choose(n:NodeSpec){haptic();setSelected(n);key.current=crypto.randomUUID();setModal('node');}
 async function submit(){if(saving)return;setSaving(true);setError('');try{await api('/requests',{nodeId:selected?.id,profile,workload,idempotencyKey:key.current});await refresh();setModal('');setNotice('Заявка сохранена. Ответ появится в кабинете. Деньги не списывались.');setWorkload('');navigate('dashboard');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 async function sendSupport(){setSaving(true);try{await api('/support',{message});await refresh();setMessage('');setNotice('Обращение отправлено.');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 async function showAdmin(){try{setAdmin(await api('/admin'));setModal('admin');}catch(e){setError((e as Error).message);}}
 async function updateRequest(id:string,status:string){setSaving(true);try{await api('/admin/requests/'+id,{status},'PATCH');setAdmin(await api('/admin'));await refresh();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 async function reply(id:string,text:string){setSaving(true);try{await api('/admin/tickets/'+id,{reply:text},'PATCH');setAdmin(await api('/admin'));}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 const active=account?.activeNodes.length||0;
 const alerts=<>{error&&<div className="alert error" role="alert">{error}<button aria-label="Закрыть ошибку" onClick={()=>setError('')}><Icon name="close" size={18}/></button></div>}{notice&&<div className="alert" role="status">{notice}<button aria-label="Закрыть уведомление" onClick={()=>setNotice('')}><Icon name="close" size={18}/></button></div>}</>;
 if(loading)return <Splash/>;
 return <div className="app-shell">
 <header className="topbar"><button className="brand" onClick={()=>{setEntered(false);haptic();}} aria-label="AetherMind — начало"><img src="/assets/icons/icon-72.png" alt=""/><span>Aether<span className="cyan">Mind</span><small>COMPUTE WITHOUT LIMITS</small></span></button><button className="icon-button" aria-label="Техническая поддержка" onClick={()=>setModal('support')}><Icon name="help"/></button></header>
 {!modal&&alerts}
 {!entered?<main className="welcome"><div className="eyebrow"><i/> GPU CLOUD INFRASTRUCTURE</div><div className="core-art"><div className="orbit orbit-one"/><img src="/assets/core.webp" alt="Светящееся ядро AetherMind в стеклянном кубе"/><span className="orbit-label">NEURAL COMPUTE ENGINE</span></div><h1>Мощность для<br/><span className="gradient">вашего интеллекта.</span></h1><p className="lead">GPU-ноды для обучения моделей, инференса и новых AI-идей. Выберите конфигурацию — мы согласуем ресурсы под вашу задачу.</p><div className="welcome-features"><span><Icon name="node" size={18}/> GPU-вычисления</span><span><Icon name="shield" size={18}/> Прозрачный учёт</span></div><button className="primary shimmer" onClick={()=>navigate('nodes')}>Арендовать ноду <Icon name="arrow"/></button><button className="ghost wide" onClick={()=>account?navigate('dashboard'):void login()}>Войти в аккаунт</button><p className="fine">Без обещаний доходности. Оплата — только после согласования условий и подключения платёжного сервиса.</p><button className="text-button" onClick={()=>setModal('terms')}>Как работает AetherMind</button></main>:<main className="workspace">
 <div className="userline"><div className="avatar">{account?.user.name.slice(0,1)||'A'}</div><div><small>ВАШ ВЫЧИСЛИТЕЛЬНЫЙ КЛАСТЕР</small><strong>{account?`Привет, ${account.user.name}`:'Добро пожаловать'}</strong></div><span className="chip muted">{account?'Telegram ✓':'Гость'}</span></div>
 {tab==='dashboard'&&<><div className="section-title"><h1>Центр управления</h1><span className="micro">OVERVIEW / 01</span></div><section className="balance-card panel"><div className="balance-top"><span>Баланс аккаунта</span><span className="chip">USDT</span></div><div className="balance"><Counter value={account?.balance||'0'}/><small>USDT</small></div><button className="subtle-button" onClick={()=>{setModal('payments');haptic();}}><Icon name="plus" size={18}/> Пополнить</button><div className="balance-footer"><Icon name="shield" size={15}/> Только подтверждённые операции</div></section><section className="network panel"><img src="/assets/server.webp" alt="Концептуальная визуализация AI-кластера"/><div className="network-copy"><span className="eyebrow">NETWORK TELEMETRY</span><h2>Всё начинается<br/>с первой ноды.</h2><p>Загрузка сети: <b>нет данных</b></p><span className="chip muted">Провайдер не подключён</span></div></section><div className="stats"><div className="panel"><Icon name="node"/><strong>{active.toString().padStart(2,'0')}</strong><small>Активные ноды</small></div><div className="panel"><Icon name="bolt"/><strong>—</strong><small>Начислено сегодня</small></div></div><div className="section-title"><h2>Мои ноды</h2><button className="text-button" onClick={()=>navigate('nodes')}>Каталог <Icon name="arrow" size={16}/></button></div><div className="empty panel"><Icon name="node" size={30}/><h3>Ресурсы ещё не подключены</h3><p>Оставьте заявку. До согласования цены и доступа списаний нет.</p><button className="secondary" onClick={()=>navigate('nodes')}>Выбрать конфигурацию</button></div>{!!account?.requests.length&&<section><h2>Заявки</h2>{account.requests.map(r=><div key={r.id} className="request panel"><span className="micro">{stateLabel[r.status]}</span><h3>{nodes.find(n=>n.id===r.nodeId)?.name||r.nodeId}</h3><p>{r.workload}</p><small>{r.profile} · {new Date(r.createdAt).toLocaleDateString('ru')}</small></div>)}</section>}</>}
 {tab==='nodes'&&<><div className="section-title"><h1>Ноды</h1><span className="micro">HARDWARE / 02</span></div><p className="lead small">Вычисления под вашу задачу.<br/>Конфигурация, стоимость и доступ — по запросу.</p><div className="filter"><span className="chip">Все конфигурации</span><span className="micro">{nodes.length} В КАТАЛОГЕ</span></div><div className="node-grid">{nodes.map(n=><article key={n.id} className={'node-card panel '+(n.status==='CONCEPT'?'violet':'')} onPointerMove={e=>{if(e.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`perspective(900px) rotateY(${(e.clientX-r.left-r.width/2)/70}deg)`;}} onPointerLeave={e=>e.currentTarget.style.transform=''}><div className="node-meta"><span className="micro">{n.label}</span><span className={'chip '+(n.status==='CONCEPT'?'purple':'muted')}>{n.status==='CONCEPT'?'Концепция':'Под запрос'}</span></div><img className="node-art" src={n.image} alt={'Художественный образ '+n.name} loading="lazy"/><h2>{n.name}</h2><p>{n.use}</p><div className="node-specs"><span>{n.memory||'R&D'}<small>{n.memory?'VRAM':'НАПРАВЛЕНИЕ'}</small></span><span>{n.compute||'—'}<small>ПЛАТФОРМА</small></span><span>—<small>ЦЕНА / ЧАС</small></span></div><button className={n.status==='CONCEPT'?'secondary wide':'primary wide'} onClick={()=>choose(n)}>{n.status==='CONCEPT'?'О концепции':'Выбрать ноду'}<Icon name="arrow" size={18}/></button></article>)}</div>{!nodes.length&&<button className="secondary" onClick={()=>void loadCatalog()}>Повторить загрузку каталога</button>}</>}
 {tab==='cluster'&&<><div className="section-title"><h1>Кластер</h1><span className="micro">CONNECTIONS / 03</span></div><section className="cluster-hero panel"><img src="/assets/quantum.webp" alt="Концептуальное ядро кластера"/><h2>Большие идеи.<br/><span className="gradient">Общая мощность.</span></h2><p>Приглашайте коллег в AetherMind и создавайте сообщество AI-разработчиков.</p></section><div className="stats"><div className="panel"><strong>{account?.referrals||0}</strong><small>Приглашено участников</small></div><div className="panel"><strong>—</strong><small>Бонусная программа</small></div></div><div className="panel padded"><h3>Ваша пригласительная ссылка</h3><p>Денежные вознаграждения не включены.</p>{account&&bot?<><code className="ref-link">https://t.me/{bot}?start=r_{account.user.id}</code><button className="secondary wide" onClick={()=>{navigator.clipboard.writeText(`https://t.me/${bot}?start=r_${account.user.id}`).then(()=>setNotice('Ссылка скопирована.')).catch(()=>setError('Не удалось скопировать. Выделите ссылку вручную.'));}}><Icon name="copy" size={18}/> Скопировать</button></>:<button className="secondary" onClick={()=>void login()}>Войти через Telegram</button>}</div></>}
 {tab==='wallet'&&<><div className="section-title"><h1>Кошелёк</h1><span className="micro">ACCOUNTING / 04</span></div><section className="panel balance-card"><span>Учётный баланс</span><div className="balance"><Counter value={account?.balance||'0'}/><small>USDT</small></div><div className="actions"><button className="primary" onClick={()=>setModal('payments')}><Icon name="plus"/> Пополнить</button><button className="secondary" onClick={()=>setModal('withdraw')}><Icon name="arrow"/> Вывести</button></div></section><div className="notice-block"><Icon name="shield"/><p>Приём и вывод средств пока не подключены. USDT — единица учёта интерфейса, не обещание конвертации Stars или доходности.</p></div><div className="section-title"><h2>История операций</h2><span className="micro">LEDGER</span></div>{account?.entries.length?account.entries.map(e=><div className="panel request" key={e.id}><b>{e.amount} USDT</b><p>{e.kind}</p></div>):<div className="panel empty"><Icon name="wallet" size={32}/><h3>Здесь будут ваши операции</h3><p>Баланс меняется только после подтверждения платёжным сервисом.</p></div>}</>}
 <footer><button className="text-button" onClick={()=>setModal('terms')}>Условия работы</button>{account?.user.isOwner&&<button className="text-button" onClick={()=>void showAdmin()}>Панель владельца</button>}<span>AETHERMIND / GPU CLOUD</span></footer>
 </main>}
 {entered&&<nav className="bottom-nav" aria-label="Основная навигация">{[['dashboard','grid','Дашборд'],['nodes','node','Ноды'],['cluster','cluster','Кластер'],['wallet','wallet','Кошелёк']].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>navigate(id)}><Icon name={icon}/><span>{label}</span></button>)}</nav>}
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!saving)setModal('');}}><div className="modal panel" role="dialog" aria-modal="true" aria-label="Информация AetherMind" tabIndex={-1} ref={modalRef}><button className="modal-close icon-button" disabled={saving} aria-label="Закрыть" onClick={()=>setModal('')}><Icon name="close"/></button>{alerts}
 {modal==='node'&&selected&&<><img className="modal-art" src={selected.image} alt={selected.name}/><span className="eyebrow">{selected.label}</span><h2>{selected.name}</h2>{selected.status==='CONCEPT'?<p>Художественная концепция развития. Quantum AI Server не является доступным оборудованием и не продаётся.</p>:<><p>Заявка без оплаты. Проверим доступность, согласуем стоимость и предоставим инструкции подключения.</p><label>Профиль работы<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="ECO">Eco · энергоэффективность</option><option value="BALANCED">Balanced · баланс</option><option value="PERFORMANCE">Performance · производительность</option></select></label><label>Что хотите запустить?<textarea value={workload} maxLength={1500} onChange={e=>setWorkload(e.target.value)} placeholder="Модель, датасет, объём памяти, срок аренды…"/></label><p className="fine">Профиль — пожелание к заявке. Пока нода не выделена, оборудование не управляется.</p>{account?<button className="primary wide" disabled={saving||workload.trim().length<5} onClick={()=>void submit()}>{saving?'Отправляем…':'Отправить заявку'}</button>:<button className="primary wide" onClick={()=>void login()}>Войти через Telegram</button>}</> }</>}
 {modal==='support'&&<><span className="eyebrow">SUPPORT CENTER</span><h2>На связи с вами</h2><p>Вопросы о нодах, доступе и работе приложения.</p>{account?<><label>Ваше сообщение<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000} placeholder="Опишите задачу или проблему…"/></label><button className="primary wide" disabled={saving||message.trim().length<5} onClick={()=>void sendSupport()}>Отправить</button>{account.tickets.map(t=><div className="ticket" key={t.id}><p>{t.message}</p><div className="reply">{t.reply||'Ожидает ответа поддержки'}</div></div>)}</>:<button className="primary wide" onClick={()=>void login()}>Войти через Telegram</button>}</>}
 {modal==='payments'&&<><Icon name="shield" size={40}/><h2>Пополнение не подключено</h2><p>Сейчас можно выбрать конфигурацию и отправить заявку без оплаты.</p><p>Для цифровых услуг внутри Telegram требуется Telegram Stars. Окончательная схема оплаты будет опубликована после подключения вычислительного провайдера.</p><p className="fine">Адресов для перевода и QR-кодов пока нет. Не отправляйте средства по реквизитам из личных сообщений.</p></>}
 {modal==='withdraw'&&<><Icon name="wallet" size={40}/><h2>Вывод недоступен</h2><p>Платёжный сервис не подключён. Заявки на вывод не создаются, средства не блокируются.</p><p className="fine">Порог 10 USDT и сроки обработки пока не являются действующими условиями. Искусственных задержек и фиктивных транзакций нет.</p></>}
 {modal==='terms'&&<><span className="eyebrow">TRANSPARENT BY DESIGN</span><h2>Как работает AetherMind</h2><ol><li>Вы выбираете GPU-конфигурацию и описываете задачу.</li><li>Оператор проверяет наличие ресурса и согласует цену, срок и условия доступа.</li><li>После подключения провайдера и оплаты выдаются инструкции доступа к выделенной ноде.</li></ol><p>На текущем этапе принимаются только заявки. Мощности, контракты с IT-компаниями и загрузка сети не заявляются без подтверждения.</p><p>Аренда вычислений не является инвестицией или гарантией пассивного дохода. Реферальные начисления не включены.</p><h3>Данные аккаунта</h3><p>Храним Telegram ID, имя, username, заявки и обращения. Оператор видит эти данные для поддержки. Запрос на удаление можно отправить через раздел поддержки. Пароли, seed-фразы и приватные ключи не запрашиваем.</p></>}
 {modal==='admin'&&admin&&<><span className="eyebrow">OWNER CONSOLE</span><h2>Панель владельца</h2><p>Пользователей: {admin.users}. Данные доступны только вашему Telegram ID.</p><h3>Заявки</h3>{admin.requests.map(r=><div className="ticket" key={r.id}><b>{r.user?.name} · {r.nodeId}</b><p>{r.workload}</p><small>{stateLabel[r.status]}</small><div className="actions"><button className="secondary" disabled={saving} onClick={()=>void updateRequest(r.id,'REVIEWED')}>В работу</button><button className="secondary" disabled={saving} onClick={()=>void updateRequest(r.id,'CLOSED')}>Закрыть</button></div></div>)}<h3>Обращения</h3>{admin.tickets.map(t=><form className="ticket" key={t.id} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void reply(t.id,String(data.get('reply')||''));}}><b>{t.user?.name}</b><p>{t.message}</p><label>Ответ<textarea name="reply" defaultValue={t.reply||''} required minLength={2} maxLength={2000}/></label><button className="secondary" disabled={saving}>Сохранить ответ</button></form>)}<h3>Журнал действий</h3>{admin.audit.map(a=><p className="fine" key={a.id}>{a.actorId}: {a.action} · {a.targetId.slice(0,8)}</p>)}</>}
 </div></div>}
 </div>
}
