import {useEffect,useState} from 'react';
import {api,type Account,type JourneyStep} from './api';
import {Icon} from './Icons';
import {useLanguage,intlLocale} from './i18n';
import {epochDays} from './Assets';
import {displayBalance} from './dashboard-model';
import {activityLabels,statusLabels,type ActivityItem} from './production-types';
import './dashboard.css';

export type MarketNode={id:string;name:string;priceUsdt:string;contractDays:number;availability:'AVAILABLE'|'SOLD_OUT'|'UNCONFIGURED'|'PAUSED'|'CONCEPT';canBuy:boolean;canSelect:boolean;experimental:boolean;image:string};
type SystemStatus={tonDeposits:string;withdrawals:string;orders:string};
type Props={account:Account|null;onMarket:()=>void;onFinance:()=>void;onAssets:()=>void;onWithdraw:()=>void;onOrder:()=>void;onSupport:()=>void;onActivity:()=>void;onTour:()=>void;onLogin:()=>void;onOffer:()=>void};
const icons:Record<JourneyStep['state'],string>={DONE:'check',CURRENT:'bolt',WAITING:'clock',LOCKED:'lock'};
const date=(value:string,locale:string)=>new Date(value).toLocaleDateString(locale);

export default function Dashboard({account,onMarket,onFinance,onAssets,onWithdraw,onOrder,onSupport,onActivity,onTour,onLogin,onOffer}:Props){
 const {t,language}=useLanguage(),locale=intlLocale(language);
 const [nodes,setNodes]=useState<MarketNode[]>([]),[activity,setActivity]=useState<ActivityItem[]>([]),[status,setStatus]=useState<SystemStatus|null>(null),[problem,setProblem]=useState('');
 useEffect(()=>{let live=true;void api<{nodes:MarketNode[]}>('/v1/market').then(data=>{if(live)setNodes(data.nodes)}).catch(e=>{if(live)setProblem((e as Error).message)});return()=>{live=false}},[account?.updatedAt]);
 useEffect(()=>{if(!account)return;let live=true;void Promise.allSettled([api<{items:ActivityItem[]}>('/v1/activity'),api<SystemStatus>('/v1/status')]).then(results=>{if(!live)return;if(results[0].status==='fulfilled')setActivity(results[0].value.items.slice(0,5));if(results[1].status==='fulfilled')setStatus(results[1].value);if(results.some(item=>item.status==='rejected'))setProblem(t('Часть данных временно недоступна. Повторите позже.'))});return()=>{live=false}},[account?.updatedAt,language]);
 const selected=nodes.find(n=>n.id===account?.selectedTariff?.nodeId),leased=account?.activeNodes||[];
 const provisioning=leased.filter(n=>n.status==='PROVISIONING');
 const active=leased.filter(n=>['ACTIVE','OVERCLOCKED'].includes(n.status));
 const completed=leased.filter(n=>['COMPLETED','EARLY_UNBONDED','EXPIRED'].includes(n.status));
 const featured=provisioning[0]||active[0]||completed[0];
 const action=account?.nextAction;
 const next:Record<NonNullable<typeof action>['kind'],{text:string;button:string;run:()=>void}>={
  SELECT_TARIFF:{text:'Выберите тариф, чтобы оформить первую ноду.',button:'Выбрать тариф',run:onMarket},
  ADD_FUNDS:{text:'Для выбранного тарифа не хватает средств на доступном балансе.',button:`${t('Пополнить на')} ${displayBalance(action?.missing||'0',locale)} USDT`,run:onFinance},
  REQUEST_PENDING:{text:'Заявка рассматривается оператором.',button:'Мои ноды',run:onAssets},
  PROVISIONING:{text:'Заказ оплачен. Оператор назначает оборудование.',button:'Открыть мою ноду',run:onAssets},
  EPOCH_ACTIVE:{text:'Epoch активен. Следите за сроком и расчётом в кабинете.',button:'Открыть мою ноду',run:onAssets},
  WITHDRAW_MANUAL:{text:'Завершившийся Epoch требует проверки статуса.',button:'Мои ноды',run:onAssets},
  ORDER_UNAVAILABLE:{text:'Заказ сейчас недоступен. Выбранный тариф сохранён.',button:'Открыть тарифы',run:onMarket},
  ORDER_SOLD_OUT:{text:'Для выбранной категории нет подтверждённых свободных слотов.',button:'Сравнить тарифы',run:onMarket},
  ORDER_READY:{text:'Баланс достаточен. Проверьте условия перед заказом.',button:'Заказать ноду',run:onOrder},
  CURRENT_OFFER_REQUIRED:{text:'Примите актуальную редакцию оферты перед заказом.',button:'Открыть условия',run:onOrder},
  EPOCH_COMPLETED:{text:'Epoch завершён. Результат и доступный баланс видны в кабинете.',button:'Мои ноды',run:onAssets}
 };
 const current=action?next[action.kind]:null;
 const heroAction=featured?{label:'Открыть мою ноду',run:onAssets}:action?.kind==='ORDER_READY'?{label:'Заказать ноду',run:onOrder}:action?.kind==='ADD_FUNDS'?{label:next.ADD_FUNDS.button,run:onFinance}:{label:'Выбрать тариф',run:onMarket};
 const steps:[string,string,()=>void][]=[
  ['Выберите тариф и изучите условия.','Срок, депозит и расчёт показаны до подтверждения.',onMarket],
  ['Подключите TON-кошелёк и пополните баланс USDT.','Сумма появляется после проверки перевода.',account?onFinance:onLogin],
  ['Подтвердите заказ ноды.','Выбор тарифа сам по себе не списывает баланс.',account?onOrder:onLogin],
  ['Дождитесь активации оператором и отслеживайте Epoch.','Период участия начинается только после активации.',account?onAssets:onTour]
 ];
 const stepIndex=provisioning.length||active.length?3:account?.selectedTariff?account.nextAction.kind==='ADD_FUNDS'?1:2:0;
 // The answers refer to the published offer and existing withdrawal flow, not estimated rates.
 const answers:[string,string,()=>void][]=[
  ['Что такое нода?','Нода — назначаемое оператором оборудование в GPU-инфраструктуре. GPU — вычислительный процессор для задач обработки данных.',onMarket],
  ['Когда начинается Epoch?','Epoch — договорный период участия. Его срок отсчитывается после активации оборудования оператором.',account?onAssets:onTour],
  ['В какой сети пополнять USDT?','Для пополнения используется только USDT в сети TON и счёт, созданный в приложении.',onFinance],
  ['Что происходит после заказа?','Оплаченный заказ получает статус подготовки. Оператор назначает оборудование и отдельно активирует Epoch.',account?onAssets:onTour],
  ['Где правила вывода и досрочного завершения?','Откройте условия в оферте и актуальный расчёт в окне вывода или карточке ноды.',onWithdraw],
  ['Как получить помощь?','Напишите в поддержку из кабинета; обращение сохраняется в профиле.',onSupport]
 ];
 const myNodes=<section className="panel dashboard-my-nodes" data-tour="nodes"><div className="section-title"><h2>{t('Мои ноды')}</h2>{account&&<button className="text-button" onClick={onAssets}>{t('Открыть')} <Icon name="arrow" size={16}/></button>}</div>{!account?<p>{t('Войдите через Telegram, чтобы увидеть свои заказы и Epoch.')}</p>:!provisioning.length&&!active.length&&!completed.length?<div className="dashboard-empty"><p>{t('Выберите тариф, чтобы оформить первую ноду.')}</p><button className="secondary" onClick={onMarket}>{t('Выбрать тариф')}</button></div>:<div className="dashboard-node-grid">{[...provisioning,...active,...completed.slice(0,1)].slice(0,4).map(node=>{const days=epochDays(node);return <article className="dashboard-node" key={node.id}><span className="chip">{t(statusLabels[node.status]||node.status)}</span><h3>{node.node?.name||node.nodeId}</h3><p>{node.status==='PROVISIONING'?`${t('Заказ')}: ${date(node.createdAt,locale)} · ${t('Далее — назначение оператором')}`:`${t('Режим')}: ${node.mode||'—'} · Epoch ${days?`${days.current}/${days.total}`:'—'}`}</p>{node.activatedAt&&<small>{t('Активация')}: {date(node.activatedAt,locale)} · {t('Завершение')}: {node.epochEndsAt?date(node.epochEndsAt,locale):'—'}</small>}{days&&<progress value={days.total-days.remaining} max={days.total} aria-label={t('Прогресс Epoch')}/>}<button className="text-button" onClick={onAssets}>{t('Подробнее')} <Icon name="arrow" size={15}/></button></article>})}</div>}</section>;
 return <section className={`dashboard-page ${featured?'has-node':''}`} aria-labelledby="dashboard-heading">
  <header className="dashboard-heading"><span className="eyebrow">AETHERMIND / GPU NETWORK</span><h1 id="dashboard-heading">{t('Главная')}</h1></header>
  <section className="dashboard-intro" aria-labelledby="intro-title" data-tour="intro"><div className="dashboard-intro-copy"><span className="eyebrow">{featured?t('ВАШ ТЕКУЩИЙ ЭТАП'):t('ПУТЬ УЧАСТНИКА')}</span><h2 id="intro-title">{t(featured?provisioning.length?'Ваш заказ ожидает назначения':active.length?'Моя нода и её Epoch':'Epoch завершён':'Ваш путь к участию в GPU-инфраструктуре')}</h2><p>{t(featured?provisioning.length?'Вы подтвердили заказ. Оператор назначит оборудование; отсчёт Epoch начнётся после активации.':active.length?'Состояние ноды, срок Epoch и реальные операции находятся в личном кабинете.':'Epoch завершён. Откройте ноду, чтобы увидеть итог и доступные действия.':'Выберите тариф, пополните баланс USDT в сети TON и оформите заказ ноды. Оператор назначит оборудование и активирует Epoch. Состояние ноды и операции доступны в личном кабинете.')}</p><p className="dashboard-glossary">{t('GPU — вычислительный процессор; нода — назначаемое оператором оборудование; Epoch — период участия после активации.')}</p><div className="dashboard-hero-buttons"><button className="primary" onClick={heroAction.run}>{t(heroAction.label)} <Icon name="arrow" size={17}/></button><button className="secondary" onClick={onTour}>{t('Как это работает')}</button></div><ul className="dashboard-facts"><li>USDT · TON</li><li>{t('Условия по оферте')}</li><li>{t('Статусы и операции в кабинете')}</li></ul></div><div className="dashboard-intro-visual"><img src="/assets/core.webp" width="320" height="320" alt="" aria-hidden="true"/><div className="dashboard-visual-caption"><span>{t(featured?'ТЕКУЩЕЕ СОСТОЯНИЕ':'AETHERMIND / NODE')}</span><strong>{featured?featured.node?.name||featured.nodeId:t('Вычислительная инфраструктура')}</strong><small>{featured?t(statusLabels[featured.status]||featured.status):t('Оператор назначает оборудование после заказа')}</small></div></div></section>
  {problem&&<p role="status" className="dashboard-problem">{problem}</p>}
  {account&&<section className="dashboard-overview" aria-label={t('Личный обзор')} data-tour="account"><div className="panel"><span>{t('Доступный баланс')}</span><strong>{displayBalance(account.balance,locale)} <small>USDT</small></strong><button className="text-button" onClick={onFinance}>{t('Пополнить')} <Icon name="arrow" size={16}/></button></div><div className="panel"><span>{t('Выбранный тариф')}</span><strong>{account.selectedTariff?.name||t('Не выбран')}</strong><small>{account.selectedTariff?`${account.selectedTariff.depositUsdt} USDT · ${account.selectedTariff.days} ${t('дней')}`:t('Выберите категорию для первой ноды')}</small></div><div className="panel"><span>{t('Мои ноды')}</span><strong>{active.length} {t('активных')} · {provisioning.length} {t('ожидают')}</strong><small>{t('В Base Epoch')}: {account.lockedBase} USDT · {t('В Compound Epoch')}: {account.lockedCompound} USDT</small></div></section>}
  {account&&current&&<aside className="panel next-action" aria-live="polite"><div><span className="eyebrow">{t('Следующее действие')}</span><h2>{t(current.text)}</h2>{action?.kind==='ADD_FUNDS'&&<p>{action.tariff} · {t('Стоимость')}: {displayBalance(action.required||'0',locale)} USDT · {t('Не хватает')}: {displayBalance(action.missing||'0',locale)} USDT</p>}</div><button className="secondary" onClick={current.run}>{t(current.button)} <Icon name="arrow" size={17}/></button></aside>}
  {featured&&myNodes}
  <section className="panel dashboard-start" data-tour="journey"><div className="section-title"><div><span className="eyebrow">01 / {t('МАРШРУТ')}</span><h2>{t('Как начать')}</h2></div><button className="text-button" onClick={onTour}>{t('Посмотреть демонстрацию')} <Icon name="arrow" size={16}/></button></div><ol>{steps.map(([title,description,run],index)=><li key={index} className={account&&index===stepIndex?'current':''} aria-current={account&&index===stepIndex?'step':undefined}><span className="dashboard-step-number">0{index+1}</span><div><h3>{t(title)}</h3><p>{t(description)}</p></div><button className="text-button" onClick={run}>{t('Перейти')} <Icon name="arrow" size={15}/></button></li>)}</ol></section>
  <section className="dashboard-tariffs" data-tour="tariffs"><div className="section-title"><div><span className="eyebrow">02 / {t('УСЛОВИЯ')}</span><h2>{t('Выберите категорию')}</h2></div><button className="text-button" onClick={onMarket}>{t('Все тарифы')} <Icon name="arrow" size={16}/></button></div><div className="dashboard-tariff-grid">{nodes.filter(n=>!n.experimental).slice(0,3).map(n=><article className="panel" key={n.id}><span className="eyebrow">{n.name}</span><strong>{displayBalance(n.priceUsdt,locale)} <small>USDT</small></strong><p>{t('Срок Epoch')}: {n.contractDays} {t('дней')}</p><small>{t(n.availability==='AVAILABLE'?'Можно заказать':n.availability==='SOLD_OUT'?'Нет свободных слотов':n.availability==='UNCONFIGURED'?'Слоты не подтверждены':'Можно выбрать')}</small><button className="secondary" onClick={onMarket}>{t('Посмотреть условия')}</button></article>)}{!nodes.length&&<p>{t('Параметры тарифов загружаются из каталога.')}</p>}</div></section>
  {!featured&&myNodes}

  <section className="dashboard-platform"><div className="section-title"><div><span className="eyebrow">03 / {t('ПЛАТФОРМА')}</span><h2>{t('Что делает AetherMind')}</h2></div></div><div className="dashboard-platform-grid"><article className="panel"><Icon name="node"/><h3>{t('Оборудование')}</h3><p>{t('Оператор назначает и обслуживает инфраструктуру; договор описывает направления GPU и B2B-нагрузки.')}</p></article><article className="panel"><Icon name="wallet"/><h3>{t('Учёт операций')}</h3><p>{t('Баланс и операции отражаются в кабинете после проверки и записи на сервере.')}</p></article><article className="panel"><Icon name="help"/><h3>{t('Сопровождение')}</h3><p>{t('Поддержка помогает с пополнениями, заказами, нодами и выводом.')}</p></article></div></section>
  {account&&<div className="dashboard-lower"><section className="panel dashboard-activity" data-tour="activity"><div className="section-title"><h2>{t('Последние операции')}</h2><button className="text-button" onClick={onActivity}>{t('Вся история')} <Icon name="arrow" size={16}/></button></div>{activity.length?<ul>{activity.map(item=><li key={item.id}><span><b>{t(activityLabels[item.type]||item.type)}</b><small>{new Date(item.createdAt).toLocaleString(locale)}</small></span><span>{item.amount?`${item.amount} USDT` : t(statusLabels[item.status]||item.status)}</span></li>)}</ul>:<p>{t('Здесь появятся пополнения, заказы и изменения нод после записи операций.')}</p>}</section><section className="panel dashboard-system"><h2>{t('Состояние системы')}</h2>{status?<dl>{[['tonDeposits','Пополнение USDT · TON'],['withdrawals','Заявки на вывод'],['orders','Заказ нод']].map(([key,label])=><div key={key}><dt>{t(label)}</dt><dd className={status[key as keyof SystemStatus]==='OPERATIONAL'?'ok':''}>{t(statusLabels[status[key as keyof SystemStatus]]||status[key as keyof SystemStatus])}</dd></div>)}</dl>:<p>{t('Проверяем состояние функций…')}</p>}</section></div>}
  <section className="panel dashboard-faq" data-tour="help"><div className="section-title"><h2>{t('Вопросы и помощь')}</h2><button className="text-button" onClick={onSupport}>{t('Поддержка')} <Icon name="arrow" size={16}/></button></div><div>{answers.map(([question,answer,run])=><details key={question}><summary>{t(question)}</summary><p>{t(answer)}</p><button className="text-button" onClick={run}>{t(question.startsWith('Где')?'Открыть окно вывода':'Подробнее')} <Icon name="arrow" size={15}/></button></details>)}</div><button className="text-button" onClick={onTour}>{t('Посмотреть демонстрацию')}</button><button className="text-button" onClick={onOffer}>{t('Публичная оферта')}</button></section>
  {account&&<details className="panel dashboard-journey"><summary>{t('Этапы участия')} · {account.journey.filter(s=>s.state==='DONE').length}/{account.journey.length}</summary><ol className="dashboard-steps">{account.journey.map((step,index)=><li key={step.id} className={step.state.toLowerCase()} aria-current={step.state==='CURRENT'?'step':undefined}><span className="journey-index"><Icon name={icons[step.state]} size={16}/></span><div><small>{t('Этап')} {index+1}</small><b>{t(step.title)}</b><p>{t(step.description)}</p></div></li>)}</ol></details>}
 </section>;
}
