import type {Language} from './i18n';
import {Icon} from './Icons';
import {Fragment} from 'react';

type Section={heading:string;clauses:string[];list?:string[]};
type Document={title:string;subtitle?:string;date:string;intro:string;sections:Section[];download:string;original:string};

const agreement:Record<'en'|'ro',Document>={
 en:{title:'AetherMind User Agreement',date:'Last updated: 14 September 2026',intro:'This User Agreement (the “Agreement”) sets out the terms of use of the AetherMind software platform, mobile application, web interfaces and API services (the “Service”) owned by AetherMind Technologies Ltd. (the “Administration”).',download:'Download the original agreement (PDF)',original:'This is a translation for reference. The original Russian PDF is available below.',sections:[
 {heading:'1. General provisions',clauses:['1.1. Using the Service constitutes the User’s full and unconditional agreement with this Agreement, the Privacy Policy and the Public Offer Agreement.','1.2. If the User disagrees with any provision, the User must immediately stop using the Service and delete the application.','1.3. The Administration may amend this Agreement unilaterally. It must notify Users through the Service interface or by email of material changes affecting their rights at least 10 days before those changes take effect. Continued use of the Service after the new version is published constitutes acceptance of the revised terms.']},
 {heading:'2. Registration and account security',clauses:['2.1. To access the Service, the User creates an account linked to a digital identifier or a cryptographic wallet.','2.2. The User is fully responsible for safeguarding authentication data (passwords, private keys, API keys and 2FA codes) and for all actions performed through the account.','2.3. Creating multiple accounts to manipulate the referral system or bypass node purchase limits is strictly prohibited and results in automatic blocking of all associated profiles.']},
 {heading:'3. Use of the interface and infrastructure',clauses:['3.1. The User receives a limited, non-exclusive, revocable licence to use the Service interface solely to manage leased computing nodes. The Administration makes commercially reasonable efforts to keep the interface available and operational.','3.2. The User must not:'],list:['Attempt to hack, decompile, reverse engineer or modify the application source code.','Use automated scripts, bots or scrapers to load the Service API servers outside the official CLI/UI.','Use the Service for denial-of-service (DDoS) attacks, compromised computing operations or unauthorised scans of external networks.']},
 {heading:'4. Intellectual property and content',clauses:['4.1. All graphic interface elements, trademarks, 3D node visualisations, load-balancing algorithms, logos and software code are the exclusive intellectual property of the Administration.','4.2. The User retains all rights to data and content uploaded to the Service. The Administration claims no ownership of User content and uses it only to operate the Service.','4.3. No Service materials may be copied, reproduced or used in third-party commercial products without the Administration’s written permission.']},
 {heading:'5. Limitation of liability and availability',clauses:['5.1. The Service interface is provided “as is”. The Administration makes commercially reasonable efforts to ensure uninterrupted operation but does not guarantee the application will work during outages of telecommunications networks or third-party cryptographic providers.','5.2. The Administration is not liable for technical problems with the User’s device or for loss of account access due to lost private keys or malware compromising the User’s device.']},
 {heading:'6. Suspension and termination',clauses:['6.1. The Administration may suspend or permanently revoke access to the Service if it finds:'],list:['A breach of this Agreement or the Public Offer Agreement.','Suspicious activity indicating an attempt to interfere with smart contracts without authorisation.','A request from the competent law enforcement or judicial authorities.']},
 {heading:'6. Suspension and termination (continued)',clauses:['6.2. Unless the block is required by law or by a critical security threat, the Administration informs the User of the reasons and allows an appeal through support within 10 business days.']},
 {heading:'7. Dispute resolution',clauses:['7.1. Disputes arising from this Agreement must first be settled through negotiations. A party who believes its rights have been infringed submits a claim to the other party.','7.2. The claim review period is 30 calendar days from receipt. Pre-trial dispute resolution is mandatory.']},
 {heading:'8. Final provisions',clauses:['8.1. The law of the company’s country of registration (Austria) applies to relations between the User and the Administration.','8.2. A court’s finding that one clause is invalid does not invalidate the remaining provisions.','8.3. For technical and legal questions, the User may contact support through the official Service interface: support@aethermind.ai.']}
 ]},
 ro:{title:'Acordul utilizatorului AetherMind',date:'Ultima actualizare: 14 septembrie 2026',intro:'Prezentul Acord al utilizatorului („Acordul”) stabilește condițiile de utilizare a platformei software, aplicației mobile, interfețelor web și serviciilor API AetherMind („Serviciul”), aparținând companiei AetherMind Technologies Ltd. („Administrația”).',download:'Descarcă acordul original (PDF)',original:'Această traducere este oferită pentru informare. PDF-ul original în limba rusă este disponibil mai jos.',sections:[
 {heading:'1. Dispoziții generale',clauses:['1.1. Utilizarea Serviciului înseamnă acceptarea deplină și necondiționată de către Utilizator a prezentului Acord, a Politicii de confidențialitate și a Contractului de ofertă publică.','1.2. Dacă nu este de acord cu oricare dintre condiții, Utilizatorul trebuie să înceteze imediat utilizarea Serviciului și să șteargă aplicația.','1.3. Administrația își rezervă dreptul de a modifica unilateral prezentul Acord. Administrația va informa Utilizatorii prin interfața Serviciului sau prin e-mail despre modificările importante care le afectează drepturile cu cel puțin 10 zile înainte de intrarea în vigoare. Continuarea utilizării Serviciului după publicarea noii versiuni înseamnă acceptarea condițiilor actualizate.']},
 {heading:'2. Înregistrarea și securitatea contului',clauses:['2.1. Pentru a accesa funcțiile Serviciului, Utilizatorul creează un cont asociat unui identificator digital sau unui portofel criptografic.','2.2. Utilizatorul poartă întreaga răspundere pentru păstrarea datelor de autentificare (parole, chei private, chei API și coduri 2FA) și pentru toate acțiunile efectuate prin contul său.','2.3. Crearea mai multor conturi pentru manipularea sistemului de recomandări sau eludarea limitelor de cumpărare a nodurilor este strict interzisă și duce la blocarea automată a tuturor profilurilor asociate.']},
 {heading:'3. Utilizarea interfeței și infrastructurii',clauses:['3.1. Utilizatorului i se acordă o licență limitată, neexclusivă și revocabilă de utilizare a interfeței Serviciului exclusiv pentru administrarea nodurilor de calcul închiriate. Administrația depune eforturi rezonabile din punct de vedere comercial pentru disponibilitatea și funcționarea interfeței.','3.2. Utilizatorului îi este interzis:'],list:['Să încerce să pirateze, să decompileze, să efectueze inginerie inversă sau să modifice codul sursă al aplicației.','Să folosească scripturi automate, roboți sau programe de extragere a datelor pentru a încărca serverele API ale Serviciului în afara CLI/UI oficial.','Să utilizeze Serviciul pentru atacuri de tip DDoS, operațiuni de calcul compromise sau scanări neautorizate ale rețelelor externe.']},
 {heading:'4. Proprietate intelectuală și conținut',clauses:['4.1. Elementele interfeței grafice, mărcile comerciale, vizualizările 3D ale nodurilor, algoritmii de distribuire a încărcării, siglele și codul software constituie proprietatea intelectuală exclusivă a Administrației.','4.2. Utilizatorul își păstrează toate drepturile asupra datelor și conținutului încărcate în Serviciu. Administrația nu pretinde dreptul de proprietate asupra conținutului Utilizatorului și îl folosește exclusiv pentru funcționarea Serviciului.','4.3. Materialele Serviciului nu pot fi copiate, reproduse sau folosite în produse comerciale terțe fără permisiunea scrisă a Administrației.']},
 {heading:'5. Limitarea răspunderii și disponibilitate',clauses:['5.1. Interfața Serviciului este furnizată „ca atare”. Administrația depune eforturi rezonabile din punct de vedere comercial pentru funcționarea continuă, însă nu garantează funcționarea aplicației în cazul întreruperilor rețelelor de telecomunicații sau ale furnizorilor criptografici terți.','5.2. Administrația nu răspunde pentru problemele tehnice ale dispozitivului Utilizatorului sau pentru pierderea accesului la cont ca urmare a pierderii cheilor private ori a compromiterii dispozitivului prin programe malițioase.']},
 {heading:'6. Suspendarea și încetarea accesului',clauses:['6.1. Administrația poate suspenda sau anula complet accesul Utilizatorului la Serviciu dacă constată:'],list:['Încălcarea prezentului Acord sau a Contractului de ofertă publică.','Activități suspecte care indică tentative de intervenție neautorizată asupra contractelor inteligente.','Cerințe ale autorităților de aplicare a legii sau judiciare competente.']},
 {heading:'6. Suspendarea și încetarea accesului (continuare)',clauses:['6.2. Dacă blocarea nu este cerută de lege sau de o amenințare critică la adresa securității, Administrația informează Utilizatorul despre motive și îi permite să conteste decizia prin serviciul de asistență în termen de 10 zile lucrătoare.']},
 {heading:'7. Soluționarea litigiilor',clauses:['7.1. Litigiile rezultate din prezentul Acord se soluționează mai întâi prin negocieri. Partea care consideră că i-au fost încălcate drepturile transmite o reclamație celeilalte părți.','7.2. Termenul de examinare a reclamației este de 30 de zile calendaristice de la primire. Procedura prealabilă de soluționare a litigiilor este obligatorie.']},
 {heading:'8. Dispoziții finale',clauses:['8.1. Relațiile dintre Utilizator și Administrație sunt guvernate de legea țării în care este înregistrată compania (Austria).','8.2. Declararea de către instanță a nulității unei clauze nu atrage nulitatea celorlalte dispoziții.','8.3. Pentru întrebări tehnice și juridice, Utilizatorul poate contacta asistența prin interfața oficială a Serviciului: support@aethermind.ai.']}
 ]}
};

export function TranslatedAgreement({language}:{language:Exclude<Language,'ru'>}){const data=agreement[language];return <article className="agreement-copy" lang={language}><header><span className="eyebrow">TERMS OF USE / USER AGREEMENT</span><h1>{data.title}</h1><p className="agreement-date">{data.date}</p><p className="offer-note">{data.original}</p></header><p>{data.intro}</p>{data.sections.map((section,index)=><section key={index}><h2>{section.heading}</h2>{section.clauses.map((clause,i)=><p key={i}>{clause}</p>)}{section.list&&<ul>{section.list.map((item,i)=><li key={i}>{item}</li>)}</ul>}</section>)}<a className="agreement-download" href="/documents/user-agreement-aethermind.pdf" download="AetherMind_User_Agreement.pdf" target="_blank" rel="noopener noreferrer"><Icon name="arrow" size={18}/>{data.download}</a></article>}

const offer:Record<'en'|'ro',Document>={
 en:{title:'Public Offer Agreement No. 88/2026-AI',subtitle:'For the provision and sublease of GPU compute nodes in a decentralised DePIN network (GPU Cluster Nodes)',date:'Vienna / Online platform · Published: 14 September 2026',intro:'This document is an official offer by the high-performance computing operator AetherMind Technologies Ltd. (the “Operator”) and defines the participation terms for individuals and legal entities (each a “Node Provider”) in the decentralised physical infrastructure network (DePIN) and the commercial GPU compute-capacity sublease cluster.',download:'Download the original public offer (PDF)',original:'This is a translation for reference. The original Russian PDF is available below.',sections:[
 {heading:'1. Terms and definitions',clauses:['1.1. Operator — AetherMind Technologies Ltd., an international technology company providing the technical infrastructure, administration, software load balancing and legal support for B2B contracts.','1.2. Node Provider — an individual or legal entity that accepts this offer by financing the activation and staking of a compute node.','1.3. DePIN (Decentralized Physical Infrastructure Network) — a distributed network combining the physical computing resources of data centres with the capital of private providers to optimise the cost of machine learning.','1.4. Compute node — a virtualised or physical GPU High-Density Clusters unit integrated into the AetherMind HPC Network.','1.5. B2B Customers — third-party counterparties of the Operator (AI laboratories, research centres and rendering farms) that lease aggregate cluster capacity for computing tasks.','1.6. $AETHER token — the ecosystem’s internal utility token used for premium rewards, internal upgrades and staking programmes.','1.7. TFLOPS (TeraFLOPS) — a unit of computing performance (one trillion floating-point operations per second).']},
 {heading:'2. Scope of the agreement and DePIN architecture',clauses:['2.1. The Operator provides allocation, maintenance in certified data centres (Tier III/IV) and administration of compute nodes based on high-performance GPUs.','2.2. The Node Provider finances activation of a selected fixed compute-capacity category (acquires a node slot), and the Operator undertakes to integrate that capacity into a commercial DePIN cluster to resell compute time to end B2B Customers.','2.3. Three-party commercial model (Node Provider ➔ AetherMind DePIN Network ➔ B2B Customers):'],list:['The Node Provider supplies capitalisation, liquidity collateral and expansion of the equipment pool.','The Operator provides continuous uptime (SLA 99.9%), load balancing, firmware integration, legal support and allocation of customer tasks.','B2B Customers pay the Operator to lease TFLOPS at spot hourly rates for machine-learning workloads (LLM, Computer Vision, Neural Rendering).']},
 {heading:'2. Scope of the agreement (continued)',clauses:['2.4. The Operator is responsible for breaches of the 99.9% uptime SLA. If equipment downtime exceeds the permitted threshold, the Node Provider receives compensation proportional to downtime under the platform’s technical regulations.']},
 {heading:'3. Fixed plan schedule and accrual terms',clauses:['3.1. Compute nodes are activated at strictly fixed denominations. The high rate of return is attributed to a shortage of high-density chips, bulk equipment purchases and the high spot price of B2B compute time.','3.2. Base returns and auto-reinvestment (Compound Boost) parameters follow the fixed node categories below.','3.3. The Operator guarantees that the interest rate and lock period for already activated nodes remain unchanged until the end of their current Epoch.']},
 {heading:'4. Restrictions and withdrawal of funds',clauses:['4.1. If violations of the platform terms or suspected unlawful conduct are detected, the Operator may temporarily restrict access to funds or block the Node Provider’s account.','4.2. The Operator must notify the Node Provider of a restriction through the platform interface or by email, giving reasons. The Node Provider may appeal through support within 14 calendar days of notification.']},
 {heading:'5. Changes to the offer and dispute resolution',clauses:['5.1. The Operator may amend this offer. Changes take effect no earlier than seven calendar days after publication on the online platform.','5.2. Disputes arising from or relating to this Agreement are subject to mandatory negotiations. A claim must be considered within 30 calendar days of its receipt.','5.3. If negotiations do not resolve the dispute, it is referred to the court at the Operator’s place of business under applicable law.']},
 {heading:'6. Operator details',clauses:['Operator: AetherMind Technologies GmbH. Registered address: Am Belvedere 10, 1100 Vienna, Austria. Company register number (Firmenbuchnummer): FN 584921 d. Commercial court: Handelsgericht Wien. VAT identification (UID): ATU78945612. Email: support@aethermind.ai. Wallet address (TON Network): UQBDpgl7qsbmxBiGeY97rHuPN0ZSo3oH6mB2fVYEHwAZ3PU7.','Operator: the document is electronically signed in accordance with EU Regulation No. 910/2014 (eIDAS). Signature: / AetherMind Technologies GmbH /. Date: 21 September 2026.','Node Provider: acceptance through the platform interface. The Agreement is entered into electronically by conduct (pressing “Accept Terms”) and/or connecting a wallet in the platform interface. The date and time of acceptance are recorded by the platform at the time of the click or connection and logged in the User’s ID profile.']}
 ]},
 ro:{title:'Contract de ofertă publică nr. 88/2026-AI',subtitle:'Privind furnizarea și subînchirierea nodurilor de calcul GPU într-o rețea descentralizată DePIN (GPU Cluster Nodes)',date:'Viena / Platformă online · Publicat: 14 septembrie 2026',intro:'Acest document constituie oferta oficială a operatorului de sisteme de calcul de înaltă performanță AetherMind Technologies Ltd. („Operatorul”) și stabilește condițiile de participare pentru persoanele fizice și juridice („Furnizorul de nod”) în rețeaua descentralizată de infrastructură fizică (DePIN) și în clusterul comercial de subînchiriere a capacității de calcul GPU.',download:'Descarcă oferta publică originală (PDF)',original:'Această traducere este oferită pentru informare. PDF-ul original în limba rusă este disponibil mai jos.',sections:[
 {heading:'1. Termeni și definiții',clauses:['1.1. Operatorul — AetherMind Technologies Ltd., companie tehnologică internațională care asigură infrastructura tehnică, administrarea, echilibrarea încărcării prin software și asistența juridică pentru contractele B2B.','1.2. Furnizorul de nod — persoana fizică sau juridică ce acceptă prezenta ofertă prin finanțarea activării și stakingului unui nod de calcul.','1.3. DePIN (Decentralized Physical Infrastructure Network) — arhitectura unei rețele distribuite care combină resursele fizice de calcul ale centrelor de date cu capitalul furnizorilor privați, pentru optimizarea costurilor învățării automate.','1.4. Nod de calcul — o unitate virtualizată sau fizică de acceleratoare grafice (GPU High-Density Clusters), integrată în rețeaua AetherMind HPC Network.','1.5. Clienți B2B — parteneri contractuali terți ai Operatorului (laboratoare AI, centre de cercetare și ferme de randare) care închiriază capacitatea totală a clusterului pentru sarcini de calcul.','1.6. Tokenul $AETHER — tokenul utilitar intern al ecosistemului, utilizat pentru recompense premium, îmbunătățiri interne și programe de staking.','1.7. TFLOPS (TeraFLOPS) — unitate de măsură a performanței de calcul (un trilion de operațiuni în virgulă mobilă pe secundă).']},
 {heading:'2. Obiectul acordului și arhitectura DePIN',clauses:['2.1. Operatorul asigură alocarea, întreținerea în centre de date certificate (Tier III/IV) și administrarea nodurilor de calcul bazate pe acceleratoare grafice de înaltă performanță.','2.2. Furnizorul de nod finanțează activarea categoriei fixe de putere de calcul alese (achiziționează un slot de nod), iar Operatorul se obligă să integreze această capacitate în clusterul DePIN comercial pentru revânzarea timpului de calcul către Clienții B2B finali.','2.3. Modelul comercial tripartit (Furnizorul de nod ➔ AetherMind DePIN Network ➔ Clienții B2B):'],list:['Furnizorul de nod asigură capitalizarea, garanția de lichiditate și extinderea parcului de echipamente disponibile.','Operatorul asigură disponibilitate continuă (SLA 99,9%), echilibrarea încărcării, integrarea firmware-ului, asistența juridică și distribuirea sarcinilor clienților.','Clienții B2B plătesc Operatorului pentru închirierea TFLOPS la tarife orare spot, pentru învățare automată (LLM, Computer Vision, Neural Rendering).']},
 {heading:'2. Obiectul acordului (continuare)',clauses:['2.4. Operatorul răspunde pentru încălcarea SLA privind disponibilitatea de 99,9%. Dacă indisponibilitatea echipamentului depășește limita stabilită, Furnizorului de nod i se acordă o compensație proporțională cu durata indisponibilității, conform regulamentului tehnic al platformei.']},
 {heading:'3. Planuri fixe și calculul câștigurilor',clauses:['3.1. Nodurile de calcul sunt activate doar la valori fixe. Rata ridicată a rentabilității este justificată prin deficitul de cipuri de mare densitate, achizițiile en-gros de echipamente și costul ridicat al timpului de calcul pe piața spot B2B.','3.2. Rentabilitatea de bază și parametrii reinvestirii automate (Compound Boost) se stabilesc conform categoriilor fixe de noduri de mai jos.','3.3. Operatorul garantează menținerea ratei procentuale și a perioadei de blocare pentru nodurile deja activate până la încheierea perioadei Epoch curente.']},
 {heading:'4. Blocarea și retragerea fondurilor',clauses:['4.1. În cazul încălcării condițiilor platformei sau al suspiciunilor privind activități ilegale, Operatorul poate restricționa temporar accesul la fonduri sau bloca contul Furnizorului de nod.','4.2. Operatorul trebuie să informeze Furnizorul de nod despre restricție prin interfața platformei sau prin e-mail și să precizeze motivele. Furnizorul poate contesta decizia prin asistență în termen de 14 zile calendaristice de la notificare.']},
 {heading:'5. Modificarea ofertei și soluționarea litigiilor',clauses:['5.1. Operatorul poate modifica prezenta ofertă. Modificările intră în vigoare cel mai devreme la șapte zile calendaristice de la publicarea pe platforma online.','5.2. Litigiile rezultate din prezentul Contract sau legate de acesta se supun negocierilor obligatorii. Termenul de examinare a unei reclamații este de 30 de zile calendaristice de la primire.','5.3. Dacă negocierile nu soluționează litigiul, acesta este transmis instanței de la sediul Operatorului, conform legislației aplicabile.']},
 {heading:'6. Datele Operatorului',clauses:['Operator: AetherMind Technologies GmbH. Adresă juridică: Am Belvedere 10, 1100 Viena, Austria. Număr de înregistrare (Firmenbuchnummer): FN 584921 d. Tribunalul comercial: Handelsgericht Wien. Cod de identificare TVA (UID): ATU78945612. E-mail: support@aethermind.ai. Adresa portofelului (rețeaua TON): UQBDpgl7qsbmxBiGeY97rHuPN0ZSo3oH6mB2fVYEHwAZ3PU7.','Operator: documentul este semnat electronic în conformitate cu Regulamentul UE nr. 910/2014 (eIDAS). Semnătură: / AetherMind Technologies GmbH /. Data: 21 septembrie 2026.','Furnizorul de nod: acceptare prin interfața platformei. Contractul se încheie electronic prin acțiuni concludente (apăsarea butonului „Accept Terms”) și/sau conectarea unui portofel în interfața platformei. Data și ora acceptării sunt înregistrate de platformă la momentul apăsării sau conectării și păstrate în profilul ID al utilizatorului.']}
 ]}
};

const values=[['Node Alpha','50',30,'1.5% · 0.75 USDT/day','1.8%','45% · +22.50 USDT','1,5% · 0,75 USDT/zi','1,8%','45% · +22,50 USDT'],['Cluster Beta','300',60,'2.5% · 7.50 USDT/day','3.0%','150% · +450 USDT','2,5% · 7,50 USDT/zi','3,0%','150% · +450 USDT'],['Enterprise POD','1,200',90,'3.5% · 42 USDT/day','4.2%','315% · +3,780 USDT','3,5% · 42 USDT/zi','4,2%','315% · +3 780 USDT'],['Quantum Array','5,000',180,'Under development','Under development','Expected Q4 2026','În dezvoltare','În dezvoltare','Anunț în T4 2026']] as const;

export function TranslatedOffer({language}:{language:Exclude<Language,'ru'>}){const data=offer[language],en=language==='en';return <article className="offer-copy" lang={language}><header><span className="eyebrow">{en?'APPENDIX A / MANDATORY':'ANEXA A / OBLIGATORIE'}</span><h1>{data.title}</h1><p>{data.subtitle}</p><small>{data.date}</small><p className="offer-note">{data.original}</p></header><p>{data.intro}</p>{data.sections.map((section,index)=><section key={index}><h2>{section.heading}</h2>{section.clauses.map((clause,i)=><Fragment key={i}><p>{clause}</p>{index===3&&i===1&&<><div className="offer-rate-list" aria-label={en?'Fixed plan schedule':'Grila planurilor fixe'}>{values.map((row,i)=><article className={'offer-rate '+(i===3?'future':'')} key={row[0]}><div className="offer-rate-head"><span>0{i+1}</span><div><h3>{row[0]}</h3><b>{en?row[1]:row[1].replace(',',' ')} USDT</b></div></div><dl><div><dt>Epoch</dt><dd>{row[2]} {en?'days':'zile'}</dd></div><div><dt>{en?'Base rate':'Rata de bază'}</dt><dd>{row[en?3:6]}</dd></div><div><dt>Compound Boost</dt><dd>{row[en?4:7]}</dd></div><div><dt>{en?'For the term':'Pe perioadă'}</dt><dd>{row[en?5:8]}</dd></div></dl></article>)}</div><p className="offer-note">{en?'The offer does not define how to activate Compound Boost, so the interface does not enable it automatically.':'Oferta nu stabilește procedura de activare a Compound Boost, astfel că interfața nu îl activează automat.'}</p></>}</Fragment>)}{section.list&&<ul>{section.list.map((item,i)=><li key={i}>{item}</li>)}</ul>}</section>)}<a className="offer-download" href="/documents/public-offer-aethermind.pdf" download="AetherMind_Public_Offer_88-2026-AI.pdf" target="_blank" rel="noopener noreferrer"><Icon name="arrow" size={18}/>{data.download}</a></article>}
