import {useEffect,useState} from 'react';
import {api} from './api';
import {useLanguage,intlLocale} from './i18n';
import {shortHash,statusLabels,type Withdrawal} from './production-types';
import './production.css';

const actions:Record<string,{next:string;label:string}[]>={REQUESTED:[{next:'UNDER_REVIEW',label:'Взять на проверку'},{next:'REJECTED',label:'Отклонить'}],UNDER_REVIEW:[{next:'APPROVED',label:'Одобрить'},{next:'REJECTED',label:'Отклонить'}],APPROVED:[{next:'PROCESSING',label:'В обработку'},{next:'REJECTED',label:'Отклонить'}],PROCESSING:[{next:'COMPLETED',label:'Завершить'}]};
export default function OwnerWithdrawals({onRefresh}:{onRefresh:()=>Promise<void>}){
 const {t,language}=useLanguage(),locale=intlLocale(language);
 const [rows,setRows]=useState<Withdrawal[]|null>(null),[selected,setSelected]=useState<Withdrawal|null>(null),[fee,setFee]=useState(''),[hash,setHash]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false);
 async function load(){const data=await api<{items:Withdrawal[];hasMore:boolean}>('/v1/admin/withdrawals?page='+page);setRows(data.items);setHasMore(data.hasMore);setSelected(old=>old?data.items.find(row=>row.id===old.id)||old:null)}
 useEffect(()=>{void load().catch(e=>setError((e as Error).message))},[page]);
 async function change(next:string){if(!selected||busy)return;setBusy(true);setError('');try{const body:Record<string,string>={status:next};if(next==='REJECTED')body.rejectionReason=reason.trim();if(fee.trim()&&['APPROVED','PROCESSING','COMPLETED'].includes(next))body.networkFee=fee.trim();if(hash.trim()&&['PROCESSING','COMPLETED'].includes(next))body.txHash=hash.trim();const result=await api<Withdrawal>('/v1/admin/withdrawals/'+selected.id,body,'PATCH');setSelected({...result,user:selected.user});await load();await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="production-page"><h2>{t('Заявки на вывод')}</h2><p>{t('Перевод выполняется оператором вручную; изменение статуса не отправляет деньги.')}</p>{error&&<p role="alert" className="owner-error">{error}</p>}{rows===null?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/></div>:rows.length?<div className="production-list">{rows.map(row=><button key={row.id} className="production-row" aria-expanded={selected?.id===row.id} onClick={()=>{setSelected(row);setFee(row.networkFee||'');setHash(row.txHash||'');setReason(row.rejectionReason||'')}}><span><b>{row.user?.username?'@'+row.user.username:row.user?.name||row.user?.id} · {row.amount} USDT</b><small>TON · {new Date(row.createdAt).toLocaleString(locale)}</small></span><span>{t(statusLabels[row.status]||row.status)}</span></button>)}</div>:<p className="production-empty">{t('Заявок на вывод пока нет')}</p>}
  {selected&&<article className="panel production-detail"><h3>{t('Детали заявки')}</h3><dl><div><dt>{t('Пользователь')}</dt><dd>{selected.user?.name} · {selected.user?.id}</dd></div><div><dt>{t('Сумма')}</dt><dd>{selected.amount} USDT</dd></div><div><dt>{t('Сеть')}</dt><dd>TON Mainnet</dd></div><div><dt>{t('Получатель')}</dt><dd>{selected.destinationAddress}</dd></div><div><dt>{t('Статус')}</dt><dd>{t(statusLabels[selected.status]||selected.status)}</dd></div>{selected.txHash&&<div><dt>Transaction hash</dt><dd><a href={'https://tonviewer.com/transaction/'+selected.txHash} target="_blank" rel="noopener noreferrer">{shortHash(selected.txHash)} ↗</a></dd></div>}</dl>{Boolean(actions[selected.status]?.length)&&<div className="production-form"><label>{t('Сетевой Gas Fee, если известен')}<input inputMode="decimal" value={fee} onChange={e=>setFee(e.target.value)} placeholder="—"/></label><label>{t('Хэш транзакции TON')}<input value={hash} maxLength={64} onChange={e=>setHash(e.target.value)} placeholder={t('После ручного перевода')}/></label><label>{t('Причина отказа')}<textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><div className="production-actions">{actions[selected.status].map(action=><button key={action.next} className={action.next==='REJECTED'?'secondary':'primary'} disabled={busy} onClick={()=>void change(action.next)}>{t(action.label)}</button>)}</div></div>}</article>}
  <div className="production-actions"><button className="secondary" disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>{t('Назад')}</button><span>{page+1}</span><button className="secondary" disabled={!hasMore||busy} onClick={()=>setPage(p=>p+1)}>{t('Далее')}</button></div>
 </section>;
}
