import {useEffect,useRef,useState} from 'react';
import {api,RequestItem,Ticket} from './api';
import {ticketLabels} from './SupportPanel';
import {Icon} from './Icons';

type Summary={users:number;openRequests:number;pendingPayments:number;openTickets:number;unreadTickets:number;confirmedDeposits:string};
type Audit={id:string;action:string;actorId:string;targetId:string;createdAt:string};
type UserRow={id:string;name:string;username?:string|null;createdAt:string;selectedTariffId?:string|null;selectedTariff?:{name:string}|null;invitedCount:number;balance:string;deposited:string};
type UserDetails={user:{id:string;name:string;username?:string|null;createdAt:string;referrerId?:string|null};statistics:{invitedCount:number;deposited:string;balance:string;tickets:number;openTickets:number};documents:{agreementAcceptedAt:string|null;offerAcceptedAt:string|null};selectedTariff?:{id:string;name:string;priceUsdt:string;contractDays:number}|null;invited:{id:string;name:string;username?:string|null;createdAt:string;selectedTariff?:{id:string;name:string}|null}[];referrals:{page:number;total:number;hasMore:boolean};requests:RequestItem[];leases:{id:string;status:string;createdAt:string;expiresAt:string;node:{name:string}}[]};
type Page<T>={items:T[];page:number;total:number;hasMore:boolean};

const date=(value:string)=>new Date(value).toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'short'});
const money=(value:string)=>Math.floor(Number(value||0)).toLocaleString('ru-RU')+' USDT';
const username=(user:{name:string;username?:string|null})=>user.username?'@'+user.username:user.name;
const requestLabels:Record<string,string>={REQUESTED:'Новая',REVIEWED:'В работе',CLOSED:'Закрыта'};
const paymentLabels:Record<string,string>={WAITING:'Ожидает оплаты',PAID:'Оплачено'};

export default function OwnerPanel({onRefresh}:{onRefresh:()=>Promise<void>}){
 const [section,setSection]=useState('overview'),[page,setPage]=useState(0),[summary,setSummary]=useState<Summary|null>(null),[items,setItems]=useState<any[]>([]),[total,setTotal]=useState(0),[hasMore,setHasMore]=useState(false);
 const [query,setQuery]=useState(''),[submittedQuery,setSubmittedQuery]=useState(''),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[payment,setPayment]=useState('');
 const [userDetail,setUserDetail]=useState<UserDetails|null>(null),[ticketDetail,setTicketDetail]=useState<Ticket|null>(null),[auditOpen,setAuditOpen]=useState(false),[audit,setAudit]=useState<Audit[]>([]);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const version=useRef(0),saving=useRef(false);
 async function load(showSpinner=true){
  const generation=++version.current;if(showSpinner)setLoading(true);setError('');
  try{
   const summaryPromise=api<Summary>('/admin');
   let data:Page<any>={items:[],page:0,total:0,hasMore:false};
   if(section!=='overview'){
    const q=new URLSearchParams({page:String(page)});
    if(section==='users'&&submittedQuery)q.set('q',submittedQuery);
    if(section==='requests'){if(status)q.set('status',status);if(payment)q.set('payment',payment)}
    if(section==='tickets'){if(status)q.set('status',status);if(category)q.set('category',category)}
    data=await api<Page<any>>('/admin/'+section+'?'+q);
   }
   const nextSummary=await summaryPromise;
   if(generation===version.current){setSummary(nextSummary);setItems(data.items);setTotal(data.total);setHasMore(data.hasMore)}
  }catch(e){if(generation===version.current)setError((e as Error).message)}finally{if(generation===version.current)setLoading(false)}
 }
 useEffect(()=>{setItems([]);setUserDetail(null);setTicketDetail(null);void load();return()=>{version.current++}},[section,page,submittedQuery,status,category,payment]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'&&(section==='overview'||section==='tickets'))void load(false)},20000);return()=>clearInterval(timer)},[section,page,status,category,payment]);
 function select(next:string){if(next===section||saving.current)return;setStatus('');setCategory('');setPayment('');setPage(0);setSection(next)}
 async function requestChange(id:string,body:unknown){
  if(saving.current)return;saving.current=true;setBusy(true);setError('');setNotice('');
  try{await api('/admin/requests/'+id,body,'PATCH');setNotice('Заявка обновлена.');await load(false);await onRefresh()}catch(e){setError((e as Error).message)}finally{saving.current=false;setBusy(false)}
 }
 async function openUser(id:string,refPage=0){setLoading(true);setError('');try{setUserDetail(await api<UserDetails>('/admin/users/'+id+'?refPage='+refPage))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 async function openTicket(id:string){
  setLoading(true);setError('');try{const detail=await api<Ticket>('/admin/tickets/'+id);setTicketDetail(detail);if(detail.ownerUnread){await api('/admin/tickets/'+id+'/read',{});setTicketDetail({...detail,ownerUnread:false});await load(false)}}catch(e){setError((e as Error).message)}finally{setLoading(false)}
 }
 async function ticketAction(path:string,body:unknown,method:'POST'|'PATCH'='POST'){
  if(!ticketDetail||saving.current)return;saving.current=true;setBusy(true);setError('');setNotice('');
  try{await api(path,body,method);setNotice('Тикет обновлён.');await openTicket(ticketDetail.id);await load(false);await onRefresh()}catch(e){setError((e as Error).message)}finally{saving.current=false;setBusy(false)}
 }
 async function showAudit(){setAuditOpen(true);setError('');try{const result=await api<{items:Audit[]}>('/admin/audit');setAudit(result.items)}catch(e){setError((e as Error).message)} }
 return <section className="owner-console">
  <div className="owner-head"><div><span className="eyebrow">OWNER CONTROL CENTER</span><h1>Управление AetherMind</h1><p>Пользователи, заявки и поддержка в одном защищённом разделе.</p></div><button className="owner-log" onClick={()=>void showAudit()}><Icon name="clock" size={16}/> Журнал</button></div>
  {error&&<p className="owner-error" role="alert">{error}</p>}{notice&&<p className="owner-success" role="status">{notice}</p>}
  <div className="owner-summary">
   <button onClick={()=>select('users')}><span>Пользователи</span><b>{summary?.users??'—'}</b><small>всего аккаунтов</small></button>
   <button onClick={()=>select('requests')}><span>Заявки</span><b>{summary?.openRequests??'—'}</b><small>{summary?.pendingPayments??'—'} ждут оплаты</small></button>
   <button onClick={()=>select('tickets')}><span>Тикеты</span><b>{summary?.openTickets??'—'}</b><small>{summary?.unreadTickets??'—'} непрочитано</small></button>
   <div><span>Депозиты</span><b>{summary?money(summary.confirmedDeposits):'—'}</b><small>только подтверждённые</small></div>
  </div>
  <div className="owner-tabs" role="tablist" aria-label="Разделы владельца">{[['overview','Обзор'],['users','Пользователи'],['requests','Заявки'],['tickets','Тикеты']].map(([id,label])=><button key={id} role="tab" disabled={busy} aria-selected={section===id} onClick={()=>select(id)}>{label}{id==='tickets'&&Boolean(summary?.unreadTickets)&&<i>{summary!.unreadTickets}</i>}</button>)}</div>

  {section==='overview'&&<div className="owner-overview"><article className="panel"><Icon name="users"/><div><h3>Пользователи</h3><p>Поиск аккаунта, баланс, подтверждённый депозит, приглашённые и назначенное оборудование.</p></div><button className="secondary" onClick={()=>select('users')}>Открыть</button></article><article className="panel"><Icon name="node"/><div><h3>Заявки оборудования</h3><p>Оборудование, ход обработки и отдельный статус оплаты без ручной имитации платежа.</p></div><button className="secondary" onClick={()=>select('requests')}>Открыть</button></article><article className="panel"><Icon name="help"/><div><h3>Поддержка</h3><p>Живые диалоги с историей, непрочитанными сообщениями и закрытием тикета оператором.</p></div><button className="secondary" onClick={()=>select('tickets')}>Открыть</button></article><div className="notice-block"><Icon name="shield"/><p>Платёжный провайдер ещё не подключён. Статус «Оплачено» появится только после подтверждения будущим платёжным модулем; панель владельца не создаёт финансовые операции.</p></div></div>}

  {section==='users'&&<div className="owner-section">
   {!userDetail?<><form className="owner-search" onSubmit={e=>{e.preventDefault();setPage(0);setSubmittedQuery(query.trim())}}><input value={query} onChange={e=>setQuery(e.target.value)} maxLength={64} placeholder="Имя, @username или Telegram ID" aria-label="Поиск пользователя"/><button className="secondary">Найти</button>{submittedQuery&&<button type="button" className="owner-log" onClick={()=>{setQuery('');setSubmittedQuery('');setPage(0)}}>Сбросить</button>}</form><div className="owner-list-head"><b>Пользователи</b><span>{total}</span></div>{loading?<p role="status">Загрузка…</p>:!items.length?<p className="owner-empty">Пользователи не найдены</p>:<div className="owner-user-list">{(items as UserRow[]).map(user=><button key={user.id} onClick={()=>void openUser(user.id)}><span className="owner-avatar">{user.name.slice(0,1).toUpperCase()}</span><span className="owner-user-main"><b>{username(user)}</b><small>{user.name} · ID {user.id}</small></span><span><b>{money(user.balance)}</b><small>Баланс</small></span><span><b>{user.invitedCount}</b><small>Приглашено</small></span><Icon name="chevron" size={17}/></button>)}</div>}</>:<UserCard data={userDetail} loading={loading} onBack={()=>setUserDetail(null)} onReferralPage={next=>void openUser(userDetail.user.id,next)}/>}
  </div>}

  {section==='requests'&&<div className="owner-section"><div className="owner-filter"><select aria-label="Статус заявки" value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">Все заявки</option><option value="REQUESTED">Новые</option><option value="REVIEWED">В работе</option><option value="CLOSED">Закрытые</option></select><select aria-label="Статус платежа" value={payment} onChange={e=>{setPayment(e.target.value);setPage(0)}}><option value="">Любая оплата</option><option value="WAITING">Ожидает оплаты</option><option value="PAID">Оплачено</option></select></div><div className="owner-list-head"><b>Заявки на оборудование</b><span>{total}</span></div>{loading?<p role="status">Загрузка…</p>:!items.length?<p className="owner-empty">Заявок нет</p>:<div className="owner-request-list">{(items as RequestItem[]).map(request=><article className="owner-request" key={request.id}><div className="owner-request-main"><span className="owner-meta">#{request.id.slice(0,8)} · {date(request.createdAt)}</span><h3>{request.equipment?.name||request.nodeId}</h3><p>{request.user?username(request.user):'Пользователь'} <small>ID {request.user?.id}</small></p></div><div><small>Платёж</small><b className={`payment-state ${request.paymentStatus==='PAID'?'paid':'waiting'}`}>{paymentLabels[request.paymentStatus]}</b></div><div><small>Обработка</small><b>{requestLabels[request.status]||request.status}</b></div><div className="owner-request-actions">{request.status==='CLOSED'?<div className="owner-reason"><b>{request.decision==='ACCEPTED'?'Принята':'Отказ'}</b><span>{request.closureReason}</span></div>:<><button className="secondary" disabled={busy||request.status==='REVIEWED'} onClick={()=>void requestChange(request.id,{status:'REVIEWED'})}>В работу</button><details><summary>Закрыть</summary><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void requestChange(request.id,{status:'CLOSED',decision:data.get('decision'),closureReason:data.get('reason')})}}><select name="decision" required defaultValue=""><option value="" disabled>Решение</option><option value="ACCEPTED">Принять</option><option value="REJECTED">Отказать</option></select><textarea name="reason" required minLength={3} maxLength={1000} placeholder="Причина для пользователя"/><button className="primary" disabled={busy}>Подтвердить</button></form></details></>}</div></article>)}</div>}</div>}

  {section==='tickets'&&<div className="owner-section"><div className="owner-filter"><select aria-label="Статус тикета" value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">Все статусы</option>{Object.entries(ticketLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Тип тикета" value={category} onChange={e=>{setCategory(e.target.value);setPage(0)}}><option value="">Все обращения</option><option value="QUESTION">Вопросы</option><option value="COMPLAINT">Жалобы</option></select></div><div className="owner-ticket-layout"><div className={`owner-ticket-list ${ticketDetail?'has-active':''}`}>{loading&&!items.length?<p role="status">Загрузка…</p>:!items.length?<p className="owner-empty">Тикетов нет</p>:(items as Ticket[]).map(ticket=><button className={`${ticketDetail?.id===ticket.id?'active':''} ${ticket.ownerUnread?'unread':''}`} key={ticket.id} onClick={()=>void openTicket(ticket.id)}><span><b>{ticket.subject}</b><i>{ticketLabels[ticket.status]}</i></span><small>{ticket.user?username(ticket.user):'Пользователь'} · {date(ticket.lastMessageAt)}</small><p>{ticket.messages?.[0]?.body||'Нет сообщений'}</p></button>)}</div><div className={`owner-chat panel ${ticketDetail?'active':''}`}>{ticketDetail?<TicketChat ticket={ticketDetail} busy={busy} onBack={()=>setTicketDetail(null)} onReply={(message)=>ticketAction('/admin/tickets/'+ticketDetail.id+'/messages',{message})} onStatus={(next)=>ticketAction('/admin/tickets/'+ticketDetail.id,{status:next},'PATCH')}/>:<div className="owner-chat-empty"><Icon name="help" size={34}/><h3>Выберите тикет</h3><p>Переписка и действия оператора появятся здесь.</p></div>}</div></div></div>}

  {section!=='overview'&&!userDetail&&!ticketDetail&&<div className="owner-pagination"><button className="secondary" disabled={!page||loading||busy} onClick={()=>setPage(value=>value-1)}>Назад</button><span>{page+1}</span><button className="secondary" disabled={!hasMore||loading||busy} onClick={()=>setPage(value=>value+1)}>Далее</button><button className="owner-log" disabled={loading||busy} onClick={()=>void load()}><Icon name="clock" size={14}/> Обновить</button></div>}

  {auditOpen&&<div className="owner-drawer-backdrop" onClick={e=>{if(e.target===e.currentTarget)setAuditOpen(false)}}><aside className="owner-drawer" aria-label="Журнал действий"><div><h2>Журнал действий</h2><button className="icon-button" aria-label="Закрыть журнал" onClick={()=>setAuditOpen(false)}><Icon name="close"/></button></div><p>Последние 30 служебных событий. Финансовые значения здесь не меняются.</p>{!audit.length?<p className="owner-empty">Записей нет</p>:audit.map(row=><article key={row.id}><b>{row.action}</b><span>{row.actorId} → {row.targetId}</span><time>{date(row.createdAt)}</time></article>)}</aside></div>}
 </section>
}

function UserCard({data,loading,onBack,onReferralPage}:{data:UserDetails;loading:boolean;onBack:()=>void;onReferralPage:(page:number)=>void}){
 return <div className="owner-user-detail"><button className="owner-back" onClick={onBack}><Icon name="chevron" size={17}/> К списку</button><div className="owner-detail-identity"><span className="owner-avatar large">{data.user.name.slice(0,1).toUpperCase()}</span><div><h2>{data.user.name}</h2><p>{data.user.username?'@'+data.user.username:'Username не указан'} · ID {data.user.id}</p><small>Регистрация: {date(data.user.createdAt)}</small></div></div><div className="owner-detail-stats"><div><span>Приглашено</span><b>{data.statistics.invitedCount}</b></div><div><span>Вложено</span><b>{money(data.statistics.deposited)}</b></div><div><span>Баланс</span><b>{money(data.statistics.balance)}</b></div><div><span>Тикеты</span><b>{data.statistics.openTickets} / {data.statistics.tickets}</b><small>открыто / всего</small></div></div><div className="owner-detail-grid"><article className="panel"><h3>Аккаунт и тариф</h3><dl><div><dt>Тариф</dt><dd>{data.selectedTariff?.name||'Не выбран'}</dd></div><div><dt>Оферта</dt><dd>{data.documents.offerAcceptedAt?date(data.documents.offerAcceptedAt):'Не принята'}</dd></div><div><dt>Соглашение</dt><dd>{data.documents.agreementAcceptedAt?date(data.documents.agreementAcceptedAt):'Не принято'}</dd></div><div><dt>Пригласивший</dt><dd>{data.user.referrerId||'Нет'}</dd></div></dl></article><article className="panel"><h3>Оборудование</h3>{data.leases.length?data.leases.map(lease=><div className="owner-mini-row" key={lease.id}><b>{lease.node.name}</b><span>{lease.status}</span><small>{date(lease.createdAt)} — {date(lease.expiresAt)}</small></div>):<p>Оборудование ещё не назначено.</p>}</article></div><section className="owner-referrals"><div className="owner-list-head"><b>Кого пригласил пользователь</b><span>{data.referrals.total}</span></div>{!data.invited.length?<p className="owner-empty">Приглашённых пока нет</p>:data.invited.map(person=><div className="owner-mini-row" key={person.id}><b>{username(person)}</b><span>ID {person.id}</span><small>{person.selectedTariff?.name||'Тариф не выбран'} · {date(person.createdAt)}</small></div>)}{data.referrals.total>100&&<div className="owner-pagination"><button className="secondary" disabled={!data.referrals.page||loading} onClick={()=>onReferralPage(data.referrals.page-1)}>Назад</button><span>{data.referrals.page+1}</span><button className="secondary" disabled={!data.referrals.hasMore||loading} onClick={()=>onReferralPage(data.referrals.page+1)}>Далее</button></div>}</section></div>
}

function TicketChat({ticket,busy,onBack,onReply,onStatus}:{ticket:Ticket;busy:boolean;onBack:()=>void;onReply:(message:string)=>void;onStatus:(status:string)=>void}){
 return <><div className="owner-chat-head"><button className="owner-back mobile-only" onClick={onBack}><Icon name="chevron" size={17}/> Назад</button><span>{ticket.category==='COMPLAINT'?'Жалоба':'Вопрос'} · #{ticket.id.slice(0,8)}</span><h3>{ticket.subject}</h3><p>{ticket.user?username(ticket.user):'Пользователь'} · ID {ticket.user?.id}</p><i>{ticketLabels[ticket.status]}</i></div><div className="owner-chat-messages">{ticket.messages.map(message=><article className={message.authorType==='OWNER'?'operator':'customer'} key={message.id}><b>{message.authorType==='OWNER'?'Вы':'Пользователь'}</b><p>{message.body}</p><time>{date(message.createdAt)}</time></article>)}</div>{ticket.status==='CLOSED'?<div className="owner-chat-actions"><span>Тикет закрыт</span><button className="secondary" disabled={busy} onClick={()=>onStatus('OPEN')}>Открыть повторно</button></div>:<><form className="owner-chat-reply" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),message=String(data.get('message')||'').trim();if(message){onReply(message);form.reset()}}}><textarea name="message" required minLength={2} maxLength={2000} placeholder="Ответ пользователю…"/><button className="primary" disabled={busy}>Ответить</button></form><div className="owner-chat-actions"><button className="secondary" disabled={busy||ticket.status==='IN_PROGRESS'} onClick={()=>onStatus('IN_PROGRESS')}>В работу</button><button className="owner-danger" disabled={busy} onClick={()=>onStatus('CLOSED')}>Закрыть тикет</button></div></>}</>
}
