import {useEffect,useState} from 'react';
import {api} from './api';
import {useLanguage,intlLocale} from './i18n';
import {statusLabels} from './production-types';
import './production.css';

type Operations={backend:string;database:string;tonCenter:string;tonApi:string;telegram:string;depositWatcher:string;lastReconciliation:string|null;gasless:string;depositMode:string;withdrawalMode:string;orders:string;accrual:string;build:string;uptimeSeconds:number};
const fields:[keyof Operations,string][]=[['backend','Backend'],['database','База данных'],['tonCenter','TON Center'],['tonApi','TONAPI'],['telegram','Telegram bot/webhook'],['depositWatcher','Deposit watcher'],['gasless','Gasless'],['depositMode','Режим пополнений'],['withdrawalMode','Режим вывода'],['orders','Заказы'],['accrual','Начисления'],['build','Build SHA'],['uptimeSeconds','Время работы'],['lastReconciliation','Последняя сверка']];
export default function OwnerOperations(){const {t,language}=useLanguage(),locale=intlLocale(language),[value,setValue]=useState<Operations|null>(null),[requests,setRequests]=useState<{id:string;kind:string;status:string;createdAt:string;user:{id:string;name:string}}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const [health,data]=await Promise.all([api<Operations>('/v1/admin/operations'),api<{items:typeof requests}>('/v1/admin/data-requests')]);setValue(health);setRequests(data.items)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 return <section className="production-page"><div className="production-heading"><h2>{t('Операции')}</h2><button className="secondary" disabled={busy} onClick={()=>void load()}>{t('Обновить')}</button></div><p>{t('Состояние сервисов. Настройки доступны только на сервере.')}</p>{error&&<p role="alert" className="owner-error">{error}</p>}{!value?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/><i/></div>:<dl className="panel production-facts">{fields.map(([key,label])=><div key={key}><dt>{t(label)}</dt><dd>{key==='lastReconciliation'?value[key]?new Date(String(value[key])).toLocaleString(locale):'—':key==='uptimeSeconds'?Math.floor(value.uptimeSeconds/60)+' '+t('мин') :t(statusLabels[String(value[key])?.toUpperCase()]||String(value[key]??'—'))}</dd></div>)}</dl>}<h3>{t('Запросы по данным')}</h3>{requests.length?<div className="production-list">{requests.map(row=><article className="panel production-row" key={row.id}><span><b>{row.user.name} · ID {row.user.id}</b><small>{t(row.kind==='DATA_EXPORT_REQUEST'?'Экспорт данных':'Удаление аккаунта')} · {new Date(row.createdAt).toLocaleString(locale)}</small></span><span>{t(statusLabels[row.status]||row.status)}</span></article>)}</div>:<p className="production-empty">{t('Запросов пока нет')}</p>}</section>;
}
