import {useLanguage,intlLocale} from './i18n';
import {useEffect,useState} from 'react';
import {api} from './api';
type Item={id:string;invoiceId:string|null;amount:string|null;receivedAmount?:string|null;status:string;sender:string|null;recipient?:string;jettonMaster?:string;txHash:string|null;traceId:string|null;createdAt:string;confirmedAt?:string|null;queryId?:string;user?:{id:string;name:string;username?:string|null}};
type Health={network:string;tonCenter:{configured:boolean;reachable:boolean;indexed:boolean};tonApi:{configured:boolean;reachable:boolean;officialUsdtSupported:boolean};gasless:{enabled:boolean;rollout:string};treasuryJettonWallet:string|null;relay:string|null};
export default function OwnerDeposits({items,detail,status,total,loading,onStatus,onOpen,onBack}:{items:Item[];detail:Item|null;status:string;total:number;loading:boolean;onStatus:(value:string)=>void;onOpen:(id:string)=>void;onBack:()=>void}){
 const {t,language}=useLanguage(),locale=intlLocale(language);
 const [health,setHealth]=useState<Health|null>(null);
 useEffect(()=>{let active=true;void api<Health>('/v1/ton/health').then(value=>{if(active)setHealth(value)}).catch(()=>{});return()=>{active=false}},[]);
 const options=[['','Все'],['PENDING','Ожидают'],['CANCELLED','Отменены'],['CONFIRMED','Подтверждены'],['CREDITED','Зачислены'],['EXPIRED','Истекли'],['REJECTED','Отклонены'],['MANUAL_REVIEW','Ручная проверка'],['UNMATCHED','Без счёта']];
 const format=(date:string)=>new Date(date).toLocaleString(locale,{dateStyle:'short',timeStyle:'short'});
 return <div className="owner-section"><div className="panel owner-deposit-detail"><h3>TON · {t('Состояние сети')}</h3><dl>{[['TON Center',health?.tonCenter.reachable?t('Доступен'):t('Недоступен')],['TON Center v3',health?.tonCenter.indexed?t('Доступен'):t('Недоступен')],['TONAPI',health?.tonApi.reachable?t('Доступен'):t('Недоступен')],['USDT gas token',health?.tonApi.officialUsdtSupported?t('Поддерживается'):t('Недоступен')],['Gasless',health?.gasless.enabled?(health.gasless.rollout==='canary'?t('Только тестерам'):t('Публично')):t('Выключен')]].map(([key,val])=><div key={key}><dt>{key}</dt><dd>{val}</dd></div>)}</dl></div><div className="owner-filter"><select aria-label={t('Статус депозита')} value={status} onChange={e=>onStatus(e.target.value)}>{options.map(([value,label])=><option key={value} value={value}>{t(label)}</option>)}</select></div><div className="owner-list-head"><b>{t('Платежи USDT · TON')}</b><span>{total}</span></div>{detail?<article className="panel owner-deposit-detail"><button className="owner-back" onClick={onBack}>← {t('К списку')}</button><h3>{detail.invoiceId||t('Без счёта')}</h3><dl>{[[t('Пользователь'),detail.user?(detail.user.username?'@'+detail.user.username:detail.user.name)+' · '+detail.user.id:'—'],[t('Статус'),detail.status],[t('Сумма'),(detail.amount||'—')+' USDT'],[t('Обнаружено'),detail.receivedAmount||'—'],['Jetton Master',detail.jettonMaster||'—'],[t('Отправитель'),detail.sender||'—'],[t('Получатель'),detail.recipient||'—'],['Transaction hash',detail.txHash||'—'],['Trace',detail.traceId||'—'],['Query ID',detail.queryId||'—'],[t('Создан'),format(detail.createdAt)],[t('Подтверждён'),detail.confirmedAt?format(detail.confirmedAt):'—']].map(([name,val])=><div key={name}><dt>{name}</dt><dd>{val}</dd></div>)}</dl>{detail.txHash&&<a href={'https://tonviewer.com/transaction/'+detail.txHash} target="_blank" rel="noopener noreferrer">TON explorer ↗</a>}</article>:loading?<p role="status">{t('Загрузка…')}</p>:!items.length?<p className="owner-empty">{t('Платежей нет')}</p>:<div className="owner-deposit-list">{items.map(row=><button className="panel" key={row.id} onClick={()=>onOpen(row.id)}><span><b>{row.user?(row.user.username?'@'+row.user.username:row.user.name):t('Без счёта')}</b><small>{row.invoiceId||row.txHash}</small></span><span>{row.amount||'—'} USDT</span><span>{t(row.status)}</span><small>{format(row.createdAt)}</small></button>)}</div>}</div>;
}
