import {useEffect,useRef,useState} from 'react';
import {useLanguage} from './i18n';
import {api} from './api';
import {Icon} from './Icons';
import './product-tour.css';

const slides=[
 {title:'Выбор тарифа',body:'Сравните стоимость и срок работы. Выбор тарифа сохраняется без списания средств.',focus:'tariff'},
 {title:'Пополнение счета',body:'Подключите TON-кошелёк, укажите сумму и переведите USDT в сети TON. После проверки перевода деньги появятся на доступном балансе.',focus:'invoice'},
 {title:'Заказ тарифа',body:'Проверьте тариф, сумму и условия. После подтверждения заказа сервис начнёт подготовку оборудования.',focus:'review'},
 {title:'Получение прибыли',body:'Сервис назначает и активирует оборудование. Оно выполняет работу, а начисления отражаются в кабинете по условиям тарифа.',focus:'activation'},
 {title:'Вывод средств',body:'Нажмите «Вывести», укажите сумму и адрес TON. Проверьте комиссии и создайте заявку. Сервис рассмотрит её и выполнит перевод после проверки.',focus:'withdrawal'}
] as const;
const version='aethermind-tour-v2';

export default function ProductTour({onClose,onMarket}:{onClose:()=>void;onMarket:()=>void}){
 const {t}=useLanguage(),[index,setIndex]=useState(0),[selected,setSelected]=useState(0),[tariffs,setTariffs]=useState<{id:string;name:string;priceUsdt:string;contractDays:number;experimental:boolean}[]>([]),dialog=useRef<HTMLDivElement>(null),opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{let live=true;void api<{nodes:typeof tariffs}>('/v1/market').then(data=>{if(live)setTariffs(data.nodes.filter(row=>!row.experimental).slice(0,2))}).catch(()=>{});return()=>{live=false}},[]);
 useEffect(()=>{opener.current=document.activeElement as HTMLElement;dialog.current?.focus();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;opener.current?.focus()}},[]);
 useEffect(()=>{const target=dialog.current?.querySelector<HTMLElement>(`[data-tour="${slides[index].focus}"]`);const align=()=>target?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});align();window.addEventListener('resize',align);return()=>window.removeEventListener('resize',align)},[index]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();onClose()}if(e.key==='ArrowRight')setIndex(i=>Math.min(slides.length-1,i+1));if(e.key==='ArrowLeft')setIndex(i=>Math.max(0,i-1));if(e.key==='Tab'){const items=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled)');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[onClose]);
 const finish=()=>{try{localStorage.setItem('aethermind.tour.version',version)}catch{}onClose()};
 const active=slides[index],tariff=tariffs[selected]||tariffs[0];
 return <div className="tour-backdrop" role="presentation"><div className="tour-panel" role="dialog" aria-modal="true" aria-labelledby="tour-title" aria-describedby="tour-description" ref={dialog} tabIndex={-1}>
  <header className="tour-header"><div><span className="eyebrow">AETHERMIND / {t('Как это работает')}</span><h2 id="tour-title">{t(active.title)}</h2></div><button className="icon-button" aria-label={t('Закрыть демонстрацию')} onClick={finish}><Icon name="close"/></button></header>
  <p id="tour-description">{t(active.body)}</p>
  <div className="tour-preview" aria-live="polite">
   {index===0&&<div className="tour-cards">{tariffs.length?tariffs.map((row,i)=><div className="tour-mock" key={row.id} data-tour={i===selected?'tariff':undefined}><span>{row.name}</span><strong>{row.priceUsdt} USDT</strong><small>{t('Срок работы')}: {row.contractDays} {t('дней')}</small><button className="secondary" aria-pressed={selected===i} onClick={()=>setSelected(i)}>{t(selected===i?'Выбрано':'Выбрать тариф')}</button></div>):<div className="tour-mock" data-tour="tariff"><strong>{t('Сравните тарифы в каталоге')}</strong><small>{t('Каталог временно недоступен. Можно продолжить знакомство и открыть тарифы позже.')}</small></div>}</div>}
   {index===1&&<div className="tour-mock" data-tour="invoice"><span>USDT · TON</span><strong>{t('Пополнение счета')}</strong><div className="tour-stage"><Icon name="wallet"/>{t('TON-кошелёк подключён')}</div><label>{t('Сумма пополнения')}<input readOnly value={(tariff?.priceUsdt||'50')+' USDT'}/></label><div className="tour-sequence"><span>{t('Счёт создан')}</span><Icon name="arrow" size={17}/><span>{t('Перевод проверен')}</span></div><small>{t('Доступный баланс после проверки')}</small><strong>+{tariff?.priceUsdt||'50'} USDT</strong></div>}
   {index===2&&<div className="tour-mock" data-tour="review"><span>{t('ПРОВЕРКА ЗАКАЗА')}</span><dl><div><dt>{t('Тариф')}</dt><dd>{tariff?.name||t('Выбранный тариф')}</dd></div><div><dt>{t('Будет списано')}</dt><dd>{tariff?`${tariff.priceUsdt} USDT`:'—'}</dd></div><div><dt>{t('Режим')}</dt><dd>BASE</dd></div><div><dt>{t('Срок работы')}</dt><dd>{tariff?.contractDays||'—'} {t('дней после активации')}</dd></div></dl><span className="tour-faux-button">{t('Подтвердить заказ')}</span><div className="tour-stage"><Icon name="clock"/>{t('Подготовка оборудования')}</div></div>}
   {index===3&&<div className="tour-mock" data-tour="activation"><span>{t('Мои ноды')}</span><strong>{tariff?.name||t('Моя нода')}</strong><div className="tour-stage"><Icon name="check"/>{t('Оборудование активировано')}</div><p>{t('Оборудование выполняет вычислительные задачи.')}</p><dl><div><dt>{t('Срок работы')}</dt><dd>{tariff?.contractDays||'—'} {t('дней')}</dd></div><div><dt>{t('Начисления')}</dt><dd>{t('В личном кабинете')}</dd></div><div><dt>{t('Доступный баланс')}</dt><dd>{t('После расчёта по тарифу')}</dd></div></dl><small>{t('Суммы и даты появляются после фактической активации и расчёта.')}</small></div>}
   {index===4&&<div className="tour-mock" data-tour="withdrawal"><span className="tour-faux-button">{t('Вывести')}</span><label>{t('Сумма вывода')}<input readOnly value="10 USDT"/></label><label>{t('Адрес TON')}<input readOnly value="UQ…"/></label><dl><div><dt>{t('Комиссии')}</dt><dd>{t('По расчёту заявки')}</dd></div><div><dt>{t('К получению')}</dt><dd>{t('Сумма минус комиссии')}</dd></div></dl><small>{t('При досрочном завершении проверьте отдельную комиссию в условиях платформы.')}</small><span className="tour-faux-button">{t('Создать заявку на вывод')}</span><div className="tour-stage"><Icon name="clock"/>{t('Заявка ожидает проверки')}</div></div>}

  </div>
  <footer className="tour-footer"><span aria-live="polite">{t('Шаг')} {index+1} / {slides.length}</span><div className="tour-progress" aria-hidden="true">{slides.map((slide,i)=><span key={slide.focus} className={i===index?'active':''}/>)}</div><div className="tour-buttons"><button className="secondary" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>{t('Назад')}</button><button className="secondary" onClick={finish}>{t('Пропустить')}</button>{index<slides.length-1?<button className="primary" onClick={()=>setIndex(i=>i+1)}>{t('Далее')}</button>:<button className="primary" onClick={()=>{finish();onMarket()}}>{t('Перейти к тарифам')}</button>}</div></footer>
 </div></div>;
}
