import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {useIsConnectionRestored,useTonConnectUI,useTonWallet} from '@tonconnect/ui-react';
import {useLanguage,intlLocale,languages} from './i18n';
import {api,type Account} from './api';
import {useAppBack} from './navigation';
import {Icon} from './Icons';
import {PageHeader,Section,FeatureTile,ListRow,IconContainer,StatusPill,EmptyState} from './UI';
import Assets from './Assets';
import Referrals from './Referrals';
import Activity from './Activity';
import Privacy from './Privacy';
import {statusLabels} from './production-types';
import './account.css';

type Page='root'|'account'|'assets'|'wallets'|'security'|'notifications'|'partners'|'language'|'documents'|'privacy'|'data'|'status'|'activity'|'about'|'journey';
type WalletState={connectedWallet:string|null;rawAddress:string|null;verified:boolean;walletVersion:string|null};
const labels:Record<Exclude<Page,'root'>,string>={account:'Данные аккаунта',assets:'Мои GPU',wallets:'Кошельки',security:'Безопасность',notifications:'Уведомления',partners:'Партнёры',language:'Язык',documents:'Документы',privacy:'Конфиденциальность',data:'Управление данными',status:'Состояние системы',activity:'История активности',about:'О платформе',journey:'Этапы участия'};
const short=(address:string)=>address.slice(0,7)+'…'+address.slice(-5);
// Keep the stored Epoch key compatible with existing device preferences.
const notificationKeys=['Платежи','Тарифы','Epoch','Поддержка','Системные события'] as const;
const preferenceIcons=['wallet','node','bolt','help','bell'];
const preferenceDescriptions=['Пополнения и заявки на вывод','Выбор тарифа и состояние заказа','Срок работы и начисления оборудования','Ответы на ваши обращения','Сообщения о работе платформы'];

export default function Profile({account,bot,onMarket,onFinance,onOwner,onOffer,onAgreement,onSupport,onNotifications,onLogout,onNotice,onError,onRefresh,activityReference,initialPage='root',initialLeaseId,onGpuReturn}:{account:Account;bot:string;onMarket:()=>void;onFinance:()=>void;onOwner:()=>void;onOffer:()=>void;onAgreement:()=>void;onSupport:(reference?:{referenceType:'DEPOSIT'|'WITHDRAWAL';referenceId:string})=>void;onNotifications:()=>void;onLogout:()=>void;onNotice:(s:string)=>void;onError:(s:string)=>void;onRefresh:()=>Promise<void>;initialPage?:Page;initialLeaseId?:string|null;onGpuReturn?:()=>void;activityReference?:{type:string;id:string}|null}){
 const {t,language,choose}=useLanguage(),locale=intlLocale(language),[page,setPage]=useState<Page>(initialPage);
 const [ui]=useTonConnectUI(),wallet=useTonWallet(),restored=useIsConnectionRestored();
 const positions=useRef<Partial<Record<Page,number>>>({}),previousPage=useRef<Page>('root'),openerIds=useRef<Partial<Record<Page,string>>>({}),focusIntent=useRef<{top:number;id:string}|null>(null);
 const [walletState,setWalletState]=useState<WalletState|null>(null),[walletLoading,setWalletLoading]=useState(false),[walletBusy,setWalletBusy]=useState(false),[walletError,setWalletError]=useState('');
 const [status,setStatus]=useState<Record<string,string>|null>(null),[statusError,setStatusError]=useState(''),[retry,setRetry]=useState(0),[dataRows,setDataRows]=useState<{id:string;kind:string;status:string;createdAt:string}[]|null>(null),[dataBusy,setDataBusy]=useState(false),[dataError,setDataError]=useState('');
 const settingsKey='aethermind.notifications.'+account.user.id;
 const [preferences,setPreferences]=useState<Record<string,boolean>>(()=>{try{return {...Object.fromEntries(notificationKeys.map(key=>[key,true])),...JSON.parse(localStorage.getItem(settingsKey)||'{}')}}catch{return Object.fromEntries(notificationKeys.map(key=>[key,true]))}});
 useEffect(()=>setPage(initialPage),[initialPage]);
 function openPage(next:Page,opener?:string){positions.current[page]=window.scrollY;openerIds.current[next]=opener||(document.activeElement as HTMLElement)?.id||'';previousPage.current=page;focusIntent.current={top:0,id:next==='activity'?'activity-title':next==='assets'?'assets-heading':'account-heading'};setPage(next)}
 function back(){const next=page==='privacy'&&previousPage.current==='documents'?'documents':'root';focusIntent.current={top:positions.current[next]||0,id:openerIds.current[page]||'account-heading'};setPage(next)}
 useLayoutEffect(()=>{const intent=focusIntent.current;if(!intent)return;focusIntent.current=null;window.scrollTo({top:intent.top});(document.getElementById(intent.id)||document.getElementById('account-heading'))?.focus({preventScroll:true})},[page]);
 useAppBack(page!=='root'&&!(page==='assets'&&Boolean(initialLeaseId)),back);
 useEffect(()=>{if(page!=='wallets'&&page!=='security')return;let live=true;if(!walletState)setWalletLoading(true);setWalletError('');void api<WalletState>('/v1/wallet').then(result=>{if(live)setWalletState(result)}).catch(e=>{if(live)setWalletError((e as Error).message)}).finally(()=>{if(live)setWalletLoading(false)});return()=>{live=false}},[page,account.updatedAt,wallet?.account.address,retry]);
 useEffect(()=>{if(page!=='status'&&page!=='about')return;let live=true;setStatusError('');void api<Record<string,string>>('/v1/status').then(result=>{if(live)setStatus(result)}).catch(e=>{if(live)setStatusError((e as Error).message)});return()=>{live=false}},[page,retry]);
 useEffect(()=>{if(page!=='data')return;let live=true;setDataError('');void api<{items:typeof dataRows}>('/v1/data-requests').then(result=>{if(live)setDataRows(result.items)}).catch(e=>{if(live)setDataError((e as Error).message)});return()=>{live=false}},[page,retry]);
 async function dataRequest(kind:'DATA_EXPORT_REQUEST'|'DATA_DELETION_REQUEST'){setDataBusy(true);setDataError('');try{await api('/v1/data-requests',{kind});const rows=await api<{items:NonNullable<typeof dataRows>}>('/v1/data-requests');setDataRows(rows.items);onNotice(t('Запрос зарегистрирован. Оператор рассмотрит его.'))}catch(e){setDataError((e as Error).message)}finally{setDataBusy(false)}}
 const verified=Boolean(wallet&&wallet.account.chain==='-239'&&walletState?.verified&&(wallet.account.address===walletState.rawAddress||wallet.account.address===walletState.connectedWallet));
 async function reconnect(){setWalletBusy(true);setWalletError('');try{ui.setConnectRequestParameters({state:'loading'});const nonce=await api<{payload:string}>('/v1/ton/proof/payload',{});ui.setConnectRequestParameters({state:'ready',value:{tonProof:nonce.payload}});if(wallet)await ui.disconnect();await ui.openModal()}catch(e){setWalletError((e as Error).message)}finally{setWalletBusy(false)}}
 function toggle(key:string){const next={...preferences,[key]:!preferences[key]};setPreferences(next);try{localStorage.setItem(settingsKey,JSON.stringify(next))}catch{/* private mode */}}
 const groups:{title:string;icon:string;items:{page?:Page;label:string;icon:string;run?:()=>void}[]}[]=[
  {title:'Оборудование',icon:'node',items:[{label:'Тарифы',icon:'node',run:onMarket},{page:'assets',label:'Мои GPU',icon:'cluster'},{page:'journey',label:'Этапы участия',icon:'journey'}]},
  {title:'Средства',icon:'wallet',items:[{label:'Финансы',icon:'wallet',run:onFinance},{page:'wallets',label:'Кошельки',icon:'shield'},{page:'activity',label:'История',icon:'history'}]},
  {title:'Аккаунт',icon:'user',items:[{page:'account',label:'Данные аккаунта',icon:'user'},{page:'security',label:'Безопасность',icon:'lock'},{page:'notifications',label:'Уведомления',icon:'bell'},{page:'language',label:'Язык',icon:'language'}]},
  {title:'Сервис',icon:'help',items:[{page:'partners',label:'Партнёры',icon:'users'},{label:'Поддержка',icon:'help',run:()=>onSupport()},{page:'status',label:'Состояние системы',icon:'network'},{page:'about',label:'О платформе',icon:'info'}]},
  {title:'Документы и данные',icon:'documents',items:[{page:'documents',label:'Документы',icon:'documents'},{page:'privacy',label:'Конфиденциальность',icon:'shield'},{page:'data',label:'Управление данными',icon:'data'}]}
 ];
 const profileHeader=<div className="account-header panel"><div className="account-avatar" aria-hidden="true">{account.user.name?.trim().charAt(0).toUpperCase()||'A'}</div><div><h2>{account.user.name}</h2><p>{account.user.username?'@'+account.user.username:t('Имя пользователя не указано')}</p></div></div>;
 const walletRows=<div className="ui-list-group"><ListRow icon="wallet" title={t('TON-кошелёк')} value={wallet?short(wallet.account.address):t('Кошелёк не подключён')}/><ListRow icon="network" title={t('Сеть')} value={wallet?.account.chain==='-239'?'TON Mainnet':wallet?t('Неверная сеть'):'TON Mainnet'}/><ListRow icon="shield" title={t('Подтверждение кошелька')} value={<StatusPill status={verified?'CONFIRMED':'PENDING'} label={t(verified?'Подтверждён':'Не подтверждён')}/>}/><ListRow icon="info" title={t('Версия кошелька')} value={verified?walletState?.walletVersion||t('Не определена'):'—'}/></div>;
 return <section className={'account-page account-'+page} aria-labelledby={page==='activity'?'activity-title':page==='assets'?'assets-heading':'account-heading'}>
  {page!=='activity'&&page!=='assets'&&<PageHeader id="account-heading" title={t(page==='root'?'Профиль':labels[page])} onBack={page==='root'?undefined:back} backLabel={t('Профиль')}/>}
  {page==='root'?<>
   {profileHeader}
   {account.user.isOwner&&<button id="profile-owner-entry" className="account-owner-entry panel" onClick={onOwner}><IconContainer name="settings" tone="violet"/><span><b>{t('Управление')}</b><small>{t('Пользователи, платежи и поддержка')}</small>{Boolean(account.notifications.unreadSupport)&&<small className="owner-unread">{t('Непрочитанные обращения: {count}',{count:account.notifications.unreadSupport})}</small>}</span><Icon name="chevron" size={20}/></button>}
   <div className="account-sections">{groups.map((group,index)=><Section title={t(group.title)} icon={group.icon} key={group.title}><div className="account-tiles">{group.items.map(item=><FeatureTile key={item.label} id={'profile-item-'+(item.page||item.icon)} icon={item.icon} label={t(item.label)} tone={index===2||index===4?'violet':'cyan'} onClick={item.run||(()=>openPage(item.page!,'profile-item-'+(item.page||item.icon)))}/>)}</div></Section>)}</div>
   <button className="account-logout text-button" onClick={onLogout}><Icon name="logout" size={20}/>{t('Выйти из аккаунта')}</button>
  </>:<>
   {page==='account'&&<div className="account-content">{profileHeader}<div className="ui-list-group"><ListRow icon="user" title="Telegram ID" value={account.user.id}/><ListRow icon="clock" title={t('Регистрация')} value={new Date(account.user.createdAt).toLocaleString(locale)}/></div></div>}
   {page==='assets'&&<Assets initialLeaseId={initialLeaseId} onGpuReturn={onGpuReturn} onBack={back} nodes={account.activeNodes} onMarket={onMarket} onOffer={onOffer} onRefresh={onRefresh}/>}
   {page==='wallets'&&<div className="account-content">{walletLoading?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/></div>:walletRows}{walletError&&<div className="alert error" role="alert">{walletError}<button aria-label={t('Закрыть')} onClick={()=>setWalletError('')}><Icon name="close"/></button><button className="text-button account-retry" onClick={()=>setRetry(n=>n+1)}>{t('Повторить')}</button></div>}<div className="account-actions"><button className="secondary" disabled={walletBusy||!restored} onClick={()=>void reconnect()}>{t(wallet?'Переподключить':'Подключить TON-кошелёк')}</button>{wallet&&<><button className="secondary" onClick={()=>void navigator.clipboard.writeText(wallet.account.address).then(()=>onNotice(t('Адрес скопирован'))).catch(()=>onError(t('Не удалось скопировать адрес.')))}><Icon name="copy" size={18}/>{t('Копировать адрес')}</button><button className="ghost" disabled={walletBusy} onClick={()=>void ui.disconnect().catch(e=>setWalletError((e as Error).message))}>{t('Отключить')}</button></>}</div></div>}
   {page==='security'&&<div className="account-content"><div className="ui-list-group"><ListRow icon="shield" title={t('Аутентификация')} description={t('Вход через ваш аккаунт Telegram')} value="Telegram"/><ListRow icon="lock" title={t('Веб-сессия')} value={<StatusPill status="ACTIVE" label={t('Активна')}/>}/><ListRow icon="wallet" title={t('Подключённый кошелёк')} value={wallet?short(wallet.account.address):t('Не подключён')}/><ListRow icon="shield" title="TON Proof" value={walletLoading?t('Загрузка…'):t(verified?'Подтверждён':'Не подтверждён')}/></div><button className="text-button account-logout" onClick={onLogout}><Icon name="logout" size={20}/>{t('Выйти из аккаунта')}</button></div>}
   {page==='notifications'&&<div className="account-content"><div className="ui-list-group"><ListRow icon="bell" title={t('Открыть центр уведомлений')} value={account.notifications.unread||'0'} onClick={onNotifications}/></div><p className="account-local-note">{t('Настройки отображения на этом устройстве. Уведомления в Telegram пока не подключены.')}</p><div className="ui-list-group">{notificationKeys.map((key,index)=><label className="account-toggle" key={key}><IconContainer name={preferenceIcons[index]}/><span><b>{t(key==='Epoch'?'Начисления':key)}</b><small>{t(preferenceDescriptions[index])}</small></span><input type="checkbox" role="switch" aria-label={t(key==='Epoch'?'Начисления':key)} checked={preferences[key]} onChange={()=>toggle(key)}/></label>)}</div></div>}
   {page==='partners'&&<Referrals account={account} bot={bot} onNotice={onNotice} onError={onError}/>}
   {page==='language'&&<div className="account-content"><div className="ui-list-group" role="group" aria-label={t('Выберите язык')}>{languages.map(item=><button className={'account-language ui-list-row '+(language===item.code?'selected':'')} key={item.code} lang={item.code} aria-pressed={language===item.code} onClick={()=>choose(item.code)}><IconContainer name="language"/><span className="ui-row-copy"><b>{item.native}</b><small>{item.name}</small></span>{language===item.code&&<Icon name="check" size={22}/>}</button>)}</div><p className="account-local-note">{t('Настройка сохраняется в вашем аккаунте.')}</p></div>}
   {page==='documents'&&<div className="account-content"><div className="ui-list-group"><ListRow icon="documents" title={t('Публичная оферта')} onClick={onOffer}/>{account.financialOffer&&<a className="ui-list-row account-document" href={account.financialOffer.documentUrl} target="_blank" rel="noopener noreferrer"><IconContainer name="download"/><span className="ui-row-copy"><b>{t('Новая финансовая редакция оферты')}</b><small>PDF</small></span><Icon name="arrow" size={18}/></a>}<ListRow icon="receipt" title={t('Пользовательское соглашение')} onClick={onAgreement}/><ListRow id="profile-document-privacy" icon="shield" title={t('Политика конфиденциальности')} onClick={()=>openPage('privacy','profile-document-privacy')}/></div><p className="account-local-note">{t('Акцепт зафиксирован')} {account.offer.acceptedAt?new Date(account.offer.acceptedAt).toLocaleString(locale):'—'}.</p></div>}
   {page==='privacy'&&<Privacy embedded/>}
   {page==='data'&&<div className="account-content">{dataError&&<div className="production-problem" role="alert"><p>{dataError}</p><button className="secondary" disabled={dataBusy} onClick={()=>setRetry(n=>n+1)}>{t('Повторить')}</button></div>}<p>{t('Запросы на экспорт и удаление рассматриваются оператором. Финансовая история сохраняется с учётом применимых сроков хранения.')}</p><div className="ui-list-group"><ListRow icon="download" title={t('Запросить экспорт данных')} onClick={dataBusy?undefined:()=>void dataRequest('DATA_EXPORT_REQUEST')}/><ListRow icon="data" title={t('Запросить удаление аккаунта')} onClick={dataBusy?undefined:()=>void dataRequest('DATA_DELETION_REQUEST')}/></div><Section title={t('Мои запросы')}>{dataRows===null?(!dataError&&<p role="status">{t('Загрузка…')}</p>):!dataRows.length?<EmptyState icon="data" title={t('Запросов пока нет')}/>:<div className="ui-list-group">{dataRows.map(row=><ListRow key={row.id} icon="data" title={t(row.kind==='DATA_EXPORT_REQUEST'?'Экспорт данных':'Удаление аккаунта')} description={new Date(row.createdAt).toLocaleString(locale)} value={<StatusPill status={row.status} label={t(statusLabels[row.status]||row.status)}/>}/>)}</div>}</Section></div>}
   {page==='journey'&&<article className="panel account-content"><ol className="profile-journey">{account.journey.map((step,index)=><li key={step.id} className={step.state.toLowerCase()} aria-current={step.state==='CURRENT'?'step':undefined}><IconContainer name={step.state==='DONE'?'check':step.state==='CURRENT'?'bolt':'clock'}/><div><small>{t('Этап')} {index+1}</small><h3>{t(step.title)}</h3><p>{t(step.description)}</p><StatusPill status={step.state} label={t(step.state==='DONE'?'Завершено':step.state==='CURRENT'?'Текущий этап':'Далее')}/></div></li>)}</ol></article>}
   {page==='activity'&&<Activity initialReference={activityReference} onBack={back} onSupport={reference=>onSupport(reference)}/>}
   {page==='status'&&<div className="account-content">{statusError&&<p role="alert">{statusError}<button className="text-button account-retry" onClick={()=>setRetry(n=>n+1)}>{t('Повторить')}</button></p>}{!status?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/></div>:<div className="ui-list-group">{([['platform','Платформа','network'],['tonDeposits','Пополнения TON','download'],['withdrawals','Выводы','send'],['orders','Заказы','node']] as const).map(([key,label,icon])=><ListRow key={key} icon={icon} title={t(label)} value={<StatusPill status={status[key]} label={t(statusLabels[status[key]]||status[key]||'—')}/>}/>)}</div>}{['PAUSED','DEGRADED'].includes(status?.tonDeposits||'')&&<p className="account-local-note" role="status">{t(status?.tonDeposits==='PAUSED'?'Пополнения TON временно приостановлены. Уже отправленные транзакции продолжают проверяться.':'Проверка пополнений TON задерживается. Уже отправленные транзакции продолжают проверяться.')}</p>}</div>}
   {page==='about'&&<div className="account-content"><p>{t('Вычислительная сеть GPU с фиксированными тарифами и ручным рассмотрением вывода.')}</p><div className="ui-list-group"><ListRow icon="info" title={t('Версия')} value="0.1.0"/><ListRow icon="node" title="Build SHA" value={status?.build||'—'}/><ListRow icon="network" title={t('Окружение')} value="TON Mainnet"/><ListRow icon="documents" title={t('Открыть оферту')} onClick={onOffer}/></div></div>}
  </>}
 </section>;
}
