import {useEffect,useRef,useState} from 'react';
import {useIsConnectionRestored,useTonConnectUI,useTonWallet} from '@tonconnect/ui-react';
import {useLanguage,intlLocale,languages,type Language} from './i18n';
import {api,type Account} from './api';
import {useAppBack} from './navigation';
import {Icon} from './Icons';
import Assets from './Assets';
import Referrals from './Referrals';
import Activity from './Activity';
import Privacy from './Privacy';
import {statusLabels} from './production-types';
import './account.css';

type Page='root'|'account'|'assets'|'wallets'|'security'|'notifications'|'partners'|'language'|'documents'|'privacy'|'data'|'status'|'activity'|'about';
type WalletState={connectedWallet:string|null;rawAddress:string|null;verified:boolean;walletVersion:string|null};
const labels:Record<Exclude<Page,'root'>,string>={account:'Аккаунт',assets:'Мои ноды',wallets:'Кошельки',security:'Безопасность',notifications:'Уведомления',partners:'Партнёры',language:'Язык',documents:'Документы',privacy:'Конфиденциальность',data:'Конфиденциальность и данные',status:'Состояние системы',activity:'История активности',about:'О платформе'};
const items:{page:Exclude<Page,'root'>;icon:string}[]=[{page:'account',icon:'user'},{page:'assets',icon:'node'},{page:'wallets',icon:'wallet'},{page:'security',icon:'shield'},{page:'notifications',icon:'bolt'},{page:'partners',icon:'users'},{page:'language',icon:'grid'},{page:'documents',icon:'copy'},{page:'privacy',icon:'lock'},{page:'data',icon:'shield'},{page:'status',icon:'check'},{page:'activity',icon:'clock'},{page:'about',icon:'node'}];
const short=(address:string)=>address.slice(0,7)+'…'+address.slice(-5);
const notificationKeys=['Платежи','Тарифы','Epoch','Поддержка','Системные события'] as const;

export default function Profile({account,bot,onMarket,onOffer,onAgreement,onSupport,onNotifications,onLogout,onNotice,onError,onRefresh,initialPage='root'}:{account:Account;bot:string;onMarket:()=>void;onOffer:()=>void;onAgreement:()=>void;onSupport:(reference?:{referenceType:'DEPOSIT'|'WITHDRAWAL';referenceId:string})=>void;onNotifications:()=>void;onLogout:()=>void;onNotice:(s:string)=>void;onError:(s:string)=>void;onRefresh:()=>Promise<void>;initialPage?:Page}){
 const {t,language,choose}=useLanguage(),locale=intlLocale(language),[page,setPage]=useState<Page>(initialPage);
 const [ui]=useTonConnectUI(),wallet=useTonWallet(),restored=useIsConnectionRestored();
 const opener=useRef<HTMLElement|null>(null),previousPage=useRef<Page>('root');
 const [walletState,setWalletState]=useState<WalletState|null>(null),[walletLoading,setWalletLoading]=useState(false),[walletBusy,setWalletBusy]=useState(false),[walletError,setWalletError]=useState('');
 const [status,setStatus]=useState<Record<string,string>|null>(null),[statusError,setStatusError]=useState(''),[dataRows,setDataRows]=useState<{id:string;kind:string;status:string;createdAt:string}[]|null>(null),[dataBusy,setDataBusy]=useState(false);
 const settingsKey='aethermind.notifications.'+account.user.id;
 const [preferences,setPreferences]=useState<Record<string,boolean>>(()=>{try{return {...Object.fromEntries(notificationKeys.map(key=>[key,true])),...JSON.parse(localStorage.getItem(settingsKey)||'{}')}}catch{return Object.fromEntries(notificationKeys.map(key=>[key,true]))}});
 useEffect(()=>setPage(initialPage),[initialPage]);
 function openPage(next:Page){opener.current=document.activeElement as HTMLElement;previousPage.current=page;setPage(next)}
 function back(){setPage(page==='privacy'&&previousPage.current==='documents'?'documents':'root');requestAnimationFrame(()=>{(opener.current?.isConnected?opener.current:document.getElementById('account-heading'))?.focus()})}
 useAppBack(page!=='root',back);
 useEffect(()=>{if(page!=='wallets')return;let live=true;if(!walletState)setWalletLoading(true);void api<WalletState>('/v1/wallet').then(result=>{if(live)setWalletState(result)}).catch(e=>{if(live)setWalletError((e as Error).message)}).finally(()=>{if(live)setWalletLoading(false)});return()=>{live=false}},[page,account.updatedAt,wallet?.account.address]);
 useEffect(()=>{if(page!=='status'&&page!=='about')return;let live=true;void api<Record<string,string>>('/v1/status').then(result=>{if(live)setStatus(result)}).catch(e=>{if(live)setStatusError((e as Error).message)});return()=>{live=false}},[page]);
 useEffect(()=>{if(page!=='data')return;let live=true;void api<{items:typeof dataRows}>('/v1/data-requests').then(result=>{if(live)setDataRows(result.items)}).catch(e=>{if(live)onError((e as Error).message)});return()=>{live=false}},[page]);
 async function dataRequest(kind:'DATA_EXPORT_REQUEST'|'DATA_DELETION_REQUEST'){setDataBusy(true);try{await api('/v1/data-requests',{kind});const rows=await api<{items:NonNullable<typeof dataRows>}>('/v1/data-requests');setDataRows(rows.items);onNotice(t('Запрос зарегистрирован. Оператор рассмотрит его.'))}catch(e){onError((e as Error).message)}finally{setDataBusy(false)}}
 const verified=Boolean(wallet&&wallet.account.chain==='-239'&&walletState?.verified&&(wallet.account.address===walletState.rawAddress||wallet.account.address===walletState.connectedWallet));
 async function reconnect(){setWalletBusy(true);setWalletError('');try{ui.setConnectRequestParameters({state:'loading'});const nonce=await api<{payload:string}>('/v1/ton/proof/payload',{});ui.setConnectRequestParameters({state:'ready',value:{tonProof:nonce.payload}});if(wallet)await ui.disconnect();await ui.openModal()}catch(e){setWalletError((e as Error).message)}finally{setWalletBusy(false)}}
 function toggle(key:string){const next={...preferences,[key]:!preferences[key]};setPreferences(next);try{localStorage.setItem(settingsKey,JSON.stringify(next))}catch{/* private mode */}}
 const profileHeader=<div className="account-header panel"><div className="account-avatar" aria-hidden="true">{account.user.name?.trim().charAt(0).toUpperCase()||'A'}</div><div><h2>{account.user.name}</h2><p>{account.user.username?'@'+account.user.username:t('Имя пользователя не указано')}</p><small>Telegram ID · {account.user.id} · {t('Регистрация')} {new Date(account.user.createdAt).toLocaleDateString(locale)}</small></div></div>;
 return <section className="account-page" aria-labelledby="account-heading">
  <header className="section-title"><h1 id="account-heading" tabIndex={-1}>{t('Профиль')}</h1><span className="micro">AETHERMIND / ACCOUNT</span></header>
  {page!=='root'&&page!=='activity'&&<button className="secondary account-back" onClick={back}>← {t('Профиль')}</button>}
  {page==='root'?<>{profileHeader}<div className="account-grid">{items.map(item=><button className="panel account-link" key={item.page} onClick={()=>openPage(item.page)}><Icon name={item.icon} size={21}/><span>{t(labels[item.page])}</span><Icon name="chevron" size={16}/></button>)}<button className="panel account-link" onClick={()=>onSupport()}><Icon name="help" size={21}/><span>{t('Поддержка')}</span><Icon name="chevron" size={16}/></button></div><button className="secondary account-logout" onClick={onLogout}><Icon name="logout" size={19}/>{t('Выйти из аккаунта')}</button></>:<>
   {page==='account'&&<div className="account-content">{profileHeader}<article className="panel account-info"><h2>{t('Аккаунт')}</h2><p>Telegram ID: {account.user.id}</p><p>{t('Регистрация')}: {new Date(account.user.createdAt).toLocaleString(locale)}</p></article></div>}
   {page==='assets'&&<Assets nodes={account.activeNodes} onMarket={onMarket} onOffer={onOffer} onRefresh={onRefresh}/>}
   {page==='wallets'&&<article className="panel account-content"><h2>{t('Кошельки')}</h2><p>{t('TON-кошелёк')} · TON Mainnet</p>{walletLoading?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/></div>:<><strong className="account-address">{wallet?short(wallet.account.address):t('Кошелёк не подключён')}</strong><dl className="account-facts"><div><dt>{t('Версия кошелька')}</dt><dd>{verified?walletState?.walletVersion||t('Не определена'):'—'}</dd></div><div><dt>TON Proof</dt><dd>{verified?t('Подтверждён'):t('Не подтверждён')}</dd></div></dl></>}{walletError&&<p role="alert">{walletError}</p>}<div className="account-actions"><button className="secondary" disabled={walletBusy||!restored} onClick={()=>void reconnect()}>{t(wallet?'Переподключить':'Подключить TON-кошелёк')}</button>{wallet&&<button className="ghost" disabled={walletBusy} onClick={()=>void ui.disconnect().catch(e=>setWalletError((e as Error).message))}>{t('Отключить')}</button>}</div></article>}
   {page==='security'&&<article className="panel account-content"><h2>{t('Безопасность')}</h2><dl className="account-facts"><div><dt>{t('Аутентификация')}</dt><dd>Telegram</dd></div><div><dt>{t('Веб-сессия')}</dt><dd>{t('Активна')}</dd></div><div><dt>{t('Подключённый кошелёк')}</dt><dd>{wallet?short(wallet.account.address):t('Не подключён')}</dd></div></dl><button className="secondary" onClick={onLogout}><Icon name="logout" size={18}/>{t('Выйти из аккаунта')}</button></article>}
   {page==='notifications'&&<article className="panel account-content"><h2>{t('Уведомления')}</h2><button className="primary" onClick={onNotifications}>{t('Открыть центр уведомлений')} · {account.notifications.unread||0}</button><p>{t('Настройки отображения на этом устройстве. Уведомления в Telegram пока не подключены.')}</p>{notificationKeys.map(key=><label className="account-toggle" key={key}><span>{t(key)}</span><input type="checkbox" checked={preferences[key]} onChange={()=>toggle(key)}/></label>)}</article>}
   {page==='partners'&&<Referrals account={account} bot={bot} onNotice={onNotice} onError={onError}/>}
   {page==='language'&&<article className="panel account-content"><h2>{t('Язык приложения')}</h2><label>{t('Выберите язык')}<select value={language} onChange={event=>choose(event.target.value as Language)}>{languages.map(item=><option key={item.code} value={item.code} lang={item.code}>{item.native}</option>)}</select></label><p>{t('Настройка сохраняется в вашем аккаунте.')}</p></article>}
   {page==='documents'&&<article className="panel account-content"><h2>{t('Документы')}</h2><button className="account-document" onClick={onOffer}>{t('Публичная оферта')} <Icon name="arrow" size={17}/></button>{account.financialOffer&&<a className="account-document" href={account.financialOffer.documentUrl} target="_blank" rel="noopener noreferrer">{t('Новая финансовая редакция оферты')} ↗</a>}<button className="account-document" onClick={onAgreement}>{t('Пользовательское соглашение')} <Icon name="arrow" size={17}/></button><button className="account-document" onClick={()=>openPage('privacy')}>{t('Политика конфиденциальности')} <Icon name="arrow" size={17}/></button><p>{t('Акцепт зафиксирован')} {account.offer.acceptedAt?new Date(account.offer.acceptedAt).toLocaleString(locale):'—'}.</p></article>}
   {page==='privacy'&&<Privacy embedded/>}
   {page==='data'&&<article className="panel account-content"><h2>{t('Конфиденциальность и данные')}</h2><p>{t('Запросы на экспорт и удаление рассматриваются оператором. Финансовая история сохраняется с учётом применимых сроков хранения.')}</p><div className="account-actions"><button className="secondary" disabled={dataBusy} onClick={()=>void dataRequest('DATA_EXPORT_REQUEST')}>{t('Запросить экспорт данных')}</button><button className="secondary" disabled={dataBusy} onClick={()=>void dataRequest('DATA_DELETION_REQUEST')}>{t('Запросить удаление аккаунта')}</button></div><h3>{t('Мои запросы')}</h3>{dataRows===null?<p role="status">{t('Загрузка…')}</p>:!dataRows.length?<p>{t('Запросов пока нет')}</p>:dataRows.map(row=><p key={row.id}>{t(row.kind==='DATA_EXPORT_REQUEST'?'Экспорт данных':'Удаление аккаунта')} · {t(statusLabels[row.status]||row.status)} · {new Date(row.createdAt).toLocaleString(locale)}</p>)}</article>}
   {page==='activity'&&<Activity onBack={back} onSupport={reference=>onSupport(reference)}/>}
   {page==='status'&&<article className="panel account-content"><h2>{t('Состояние системы')}</h2>{statusError&&<p role="alert">{statusError}</p>}{!status?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/></div>:<dl className="account-facts">{([['platform','Платформа'],['tonDeposits','Пополнения TON'],['withdrawals','Выводы'],['orders','Заказы']] as const).map(([key,label])=><div key={key}><dt>{t(label)}</dt><dd>{t(statusLabels[status[key]]||status[key]||'—')}</dd></div>)}</dl>}{['PAUSED','DEGRADED'].includes(status?.tonDeposits||'')&&<p role="status">{t(status?.tonDeposits==='PAUSED'?'Пополнения TON временно приостановлены. Уже отправленные транзакции продолжают проверяться.':'Проверка пополнений TON задерживается. Уже отправленные транзакции продолжают проверяться.')}</p>}</article>}
   {page==='about'&&<article className="panel account-content"><h2>AetherMind</h2><p>{t('Вычислительная сеть GPU с фиксированными тарифами и ручным рассмотрением вывода.')}</p><dl className="account-facts"><div><dt>{t('Версия')}</dt><dd>0.1.0</dd></div><div><dt>Build SHA</dt><dd>{status?.build||'—'}</dd></div><div><dt>{t('Окружение')}</dt><dd>TON Mainnet</dd></div></dl><button className="text-button" onClick={onOffer}>{t('Открыть оферту')}</button></article>}
  </>}
 </section>;
}
