import {useLanguage,intlLocale} from './i18n';
import type {Account} from './api';
import {haptic} from './api';
import {Icon} from './Icons';
import './referrals.css';

const stage:Record<string,{label:string;step:number}>={REGISTERED:{label:'Регистрация',step:1},OFFER_ACCEPTED:{label:'Оферта принята',step:2},TARIFF_SELECTED:{label:'Тариф выбран',step:3},ACTIVE:{label:'Активный Epoch',step:4}};
async function copy(value:string){try{await navigator.clipboard.writeText(value);return}catch{}const el=document.createElement('textarea');el.value=value;el.style.position='fixed';el.style.opacity='0';document.body.appendChild(el);el.select();const ok=document.execCommand('copy');el.remove();if(!ok)throw Error('copy failed')}

export default function Referrals({account,bot,onNotice,onError}:{account:Account;bot:string;onNotice:(s:string)=>void;onError:(s:string)=>void}){
 const {t,language}=useLanguage();
 const link=bot?`https://t.me/${bot}?start=r_${account.user.id}`:'';
 async function share(){haptic();const text=t('Присоединяйтесь к AetherMind — коммерческому DePIN-кластеру GPU.');try{if(navigator.share){await navigator.share({title:'AetherMind',text,url:link});return}const url=`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent(text)}`;if(window.Telegram?.WebApp.openTelegramLink)window.Telegram.WebApp.openTelegramLink(url);else location.href=url}catch(e){if((e as Error).name!=='AbortError')onError(t('Не удалось открыть меню отправки. Скопируйте ссылку.')) }}
 return <section className="referrals-page"><header className="referrals-heading"><span className="eyebrow">{t("AETHERMIND / PARTNER NETWORK")}</span><h1>{t("Партнёры")}</h1><p>{t("Приглашайте участников и отслеживайте их путь без доступа к личным данным.")}</p></header><article className="referral-hero panel"><div className="referral-orbit"><Icon name="users" size={34}/><i/><i/></div><div><span>{t("Всего приглашено")}</span><strong>{account.referrals.total}</strong><small>{t("Активных Epoch:")} {account.referrals.active}</small></div></article><div className="referral-disclosure"><Icon name="shield" size={18}/><p>{t("Оферта № 88/2026-AI не устанавливает реферальное денежное вознаграждение. Поэтому бонусы не начисляются и не показываются как обещанный доход.")}</p></div><article className="referral-link panel"><span>{t("Ваша персональная ссылка")}</span>{link?<><code>{link}</code><div><button className="secondary" onClick={()=>void copy(link).then(()=>onNotice(t('Ссылка скопирована.'))).catch(()=>onError(t('Не удалось скопировать ссылку.')))}><Icon name="copy" size={17}/> {t("Копировать")}</button><button className="primary" onClick={()=>void share()}><Icon name="arrow" size={17}/> {t("Отправить")}</button></div></>:<p>{t("Имя бота ещё не настроено.")}</p>}</article><div className="section-title"><h2>{t("Этапы партнёров")}</h2><span className="micro">{t("LIVE STATUS")}</span></div>{account.referrals.items.length?<div className="referral-list">{account.referrals.items.map(item=>{const s=stage[item.stage]||stage.REGISTERED;return <article className="referral-person panel" key={item.id}><div className="referral-person-head"><span>{item.label.startsWith('Участник ')?t('Участник ')+item.label.slice('Участник '.length):item.label}</span><small>{new Date(item.joinedAt).toLocaleDateString(intlLocale(language))}</small></div><div className="referral-progress" aria-label={`${t("Этап")} ${s.step} ${t("из")} 4`}><i style={{width:`${s.step*25}%`}}/></div><div><b>{t(s.label)}</b><span>{s.step}/4</span></div></article>})}</div>:<div className="empty panel"><Icon name="users" size={30}/><h3>{t("Пока без приглашений")}</h3><p>{t("Отправьте персональную ссылку. Новый участник появится здесь после регистрации.")}</p></div>}</section>
}
