import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import {useLanguage,intlLocale} from './i18n';
import {useAppBack} from './navigation';
import {shortHash,statusLabels,type Withdrawal} from './production-types';
import './production.css';

export default function Withdrawals({balance,lockedBase='0',lockedCompound='0',onBack,onRefresh,onSupport}:{balance:string;lockedBase?:string;lockedCompound?:string;onBack:()=>void;onRefresh:()=>Promise<void>;onSupport:(reference:{referenceType:'WITHDRAWAL';referenceId:string})=>void}){
 const {t,language}=useLanguage(),locale=intlLocale(language);
 const [rows,setRows]=useState<Withdrawal[]|null>(null),[address,setAddress]=useState(''),[amount,setAmount]=useState(''),[step,setStep]=useState<'FORM'|'REVIEW'|'LIST'>('LIST'),[selected,setSelected]=useState<Withdrawal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const key=useRef(crypto.randomUUID());
 async function load(){setRows((await api<{items:Withdrawal[]}>('/v1/withdrawals')).items)}
 useEffect(()=>{void load().catch(e=>setError((e as Error).message))},[]);
 useEffect(()=>{if(step==='LIST'||!address&&!amount)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[step,address,amount]);
 useAppBack(Boolean(selected)||step!=='LIST',()=>{if(selected)setSelected(null);else if(step==='REVIEW')setStep('FORM');else setStep('LIST')});
 async function create(){if(busy)return;setBusy(true);setError('');try{const row=await api<Withdrawal>('/v1/withdrawals',{asset:'USDT',network:'TON',destinationAddress:address.trim(),amount:amount.trim(),idempotencyKey:key.current});await load();setSelected(row);setStep('LIST');setAddress('');setAmount('');key.current=crypto.randomUUID();await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function cancel(id:string){setBusy(true);setError('');try{const row=await api<Withdrawal>('/v1/withdrawals/'+id+'/cancel',{});setSelected(row);await load();await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="production-page" aria-labelledby="withdraw-title"><button className="secondary" onClick={onBack}>← {t('Финансы')}</button><div className="production-heading"><h2 id="withdraw-title">{t('Вывести USDT')}</h2><span>TON Mainnet</span></div>
  {error&&<p role="alert" className="owner-error">{error}</p>}
  {step==='FORM'?<form className="panel production-form" onSubmit={e=>{e.preventDefault();setStep('REVIEW')}}><p>{t('Доступно')}: <strong>{balance} USDT</strong> · {t('Заблокировано в Base Epoch')}: {lockedBase} USDT · {t('Капитализировано внутри активного Epoch')}: {lockedCompound} USDT</p><label>{t('Сеть')}<input value="TON Mainnet" readOnly/></label><label>{t('Адрес TON')}<input required autoComplete="off" value={address} maxLength={70} onChange={e=>{setAddress(e.target.value);key.current=crypto.randomUUID()}} placeholder="UQ…"/></label><label>{t('Сумма, USDT')}<input required inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);key.current=crypto.randomUUID()}} placeholder="10.00"/></label><p className="fine">{t('Сумма резервируется в учётном балансе при создании заявки. Перевод оператор выполнит вручную.')}</p><button className="primary">{t('Продолжить')}</button></form>:step==='REVIEW'?<article className="panel production-form"><h3>{t('Проверьте заявку')}</h3><dl><div><dt>{t('Сумма')}</dt><dd>{amount} USDT</dd></div><div><dt>{t('Сеть')}</dt><dd>TON Mainnet</dd></div><div><dt>{t('Адрес TON')}</dt><dd>{address}</dd></div><div><dt>{t('Комиссия платформы')}</dt><dd>0 USDT</dd></div><div><dt>{t('Сетевой Gas Fee')}</dt><dd>{t('По фактической комиссии TON')}</dd></div></dl><p>{t('Сумма резервируется при создании заявки. Сетевой Gas Fee будет рассчитан при ручной обработке.')}</p><div className="production-actions"><button className="secondary" onClick={()=>setStep('FORM')}>{t('Назад')}</button><button className="primary" disabled={busy} onClick={()=>void create()}>{busy?t('Отправка…'):t('Создать заявку')}</button></div></article>:<><button className="primary" onClick={()=>setStep('FORM')}>{t('Создать заявку на вывод')}</button><div className="production-list" aria-live="polite">{rows===null?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/></div>:!rows.length?<p className="production-empty">{t('Заявок на вывод пока нет')}</p>:rows.map(row=><button className="production-row" key={row.id} aria-expanded={selected?.id===row.id} onClick={()=>setSelected(selected?.id===row.id?null:row)}><span><b>{row.amount} USDT</b><small>TON · {new Date(row.createdAt).toLocaleString(locale)}</small></span><span>{t(statusLabels[row.status]||row.status)}</span></button>)}</div></>}
  {selected&&step==='LIST'&&<article className="panel production-detail"><h3>{t('Детали заявки')}</h3><dl><div><dt>{t('Сумма')}</dt><dd>{selected.amount} USDT</dd></div><div><dt>{t('Сеть')}</dt><dd>TON</dd></div><div><dt>{t('Получатель')}</dt><dd>{selected.destinationAddress}</dd></div><div><dt>{t('Статус')}</dt><dd>{t(statusLabels[selected.status]||selected.status)}</dd></div><div><dt>{t('Создан')}</dt><dd>{new Date(selected.createdAt).toLocaleString(locale)}</dd></div><div><dt>{t('Комиссия платформы')}</dt><dd>{selected.platformFee===null?'—':selected.platformFee+' USDT'}</dd></div><div><dt>{t('Сетевой Gas Fee')}</dt><dd>{selected.networkFee===null?t('По фактической комиссии TON'):selected.networkFee+' USDT'}</dd></div>{selected.netAmount&&<div><dt>{t('К получению')}</dt><dd>{selected.netAmount} USDT</dd></div>}{selected.txHash&&<div><dt>Transaction hash</dt><dd><a href={'https://tonviewer.com/transaction/'+selected.txHash} target="_blank" rel="noopener noreferrer">{shortHash(selected.txHash)} ↗</a></dd></div>}{selected.rejectionReason&&<div><dt>{t('Причина отказа')}</dt><dd>{selected.rejectionReason}</dd></div>}</dl><div className="production-actions">{selected.status==='REQUESTED'&&<button className="secondary" disabled={busy} onClick={()=>void cancel(selected.id)}>{t('Отменить заявку')}</button>}<button className="secondary" onClick={()=>onSupport({referenceType:'WITHDRAWAL',referenceId:selected.id})}>{t('Сообщить о проблеме')}</button></div></article>}
 </section>;
}
