import {useEffect,useRef,useState} from 'react';
import {api,type Account} from './api';
import {useLanguage,intlLocale} from './i18n';
import {useAppBack} from './navigation';
import {shortHash,statusLabels,type Withdrawal} from './production-types';
import './production.css';

type Quote={leaseId:string;allowed:boolean;principal:string;cycleDay:number;feePercent:string;fee:string;netPrincipal:string;epochEndsAt:string;mode:string;reason:string|null;clause:string};
export default function Withdrawals({balance,lockedBase='0',lockedCompound='0',leases=[],onBack,onRefresh,onSupport}:{balance:string;lockedBase?:string;lockedCompound?:string;leases?:Account['activeNodes'];onBack:()=>void;onRefresh:()=>Promise<void>;onSupport:(reference:{referenceType:'WITHDRAWAL';referenceId:string})=>void}){
 const {t,language}=useLanguage(),locale=intlLocale(language);
 const [rows,setRows]=useState<Withdrawal[]|null>(null),[address,setAddress]=useState(''),[amount,setAmount]=useState(''),[step,setStep]=useState<'FORM'|'REVIEW'|'LIST'>('FORM'),[selected,setSelected]=useState<Withdrawal|null>(null),[quotes,setQuotes]=useState<Quote[]>([]),[unbondId,setUnbondId]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const key=useRef(crypto.randomUUID());
 async function load(){setRows((await api<{items:Withdrawal[]}>('/v1/withdrawals')).items)}
 useEffect(()=>{void load().catch(e=>setError((e as Error).message))},[]);
 useEffect(()=>{let live=true;const active=leases.filter(row=>row.status==='ACTIVE'&&row.offerVersion&&row.mode);void Promise.all(active.map(row=>api<Quote>(`/v1/leases/${row.id}/unbond/quote`).catch(()=>null))).then(results=>{if(live)setQuotes(results.filter((quote):quote is Quote=>Boolean(quote)))});return()=>{live=false}},[leases]);
 useEffect(()=>{if(step==='LIST'||!address&&!amount)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[step,address,amount]);
 useAppBack(Boolean(selected)||step!=='LIST',()=>{if(selected)setSelected(null);else if(step==='REVIEW')setStep('FORM');else setStep('LIST')});
 async function create(){if(busy)return;setBusy(true);setError('');try{const row=await api<Withdrawal>('/v1/withdrawals',{asset:'USDT',network:'TON',destinationAddress:address.trim(),amount:amount.trim(),idempotencyKey:key.current});await load();setSelected(row);setStep('LIST');setAddress('');setAmount('');key.current=crypto.randomUUID();await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function cancel(id:string){setBusy(true);setError('');try{const row=await api<Withdrawal>('/v1/withdrawals/'+id+'/cancel',{});setSelected(row);await load();await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function unbond(id:string){if(busy)return;setBusy(true);setError('');try{await api(`/v1/leases/${id}/unbond`,{idempotencyKey:crypto.randomUUID()});setUnbondId(null);await onRefresh();const quote=await api<Quote>(`/v1/leases/${id}/unbond/quote`).catch(()=>null);setQuotes(previous=>quote?previous.map(row=>row.leaseId===id?quote:row):previous.filter(row=>row.leaseId!==id))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="production-page withdrawal-dialog" aria-labelledby="withdraw-title"><button className="text-button" onClick={onBack}>← {t('Закрыть')}</button><div className="production-heading"><h2 id="withdraw-title">{t('Вывести USDT')}</h2><span>TON Mainnet</span></div>
  <article className="withdrawal-rules"><h3>{t('Условия вывода')}</h3><p>{t('Доступный баланс: от 10 USDT, комиссия платформы 0%. Сетевая комиссия TON определяется при обработке. Оператор рассматривает заявку от 15 минут до 24 часов (п. 5.3).')}</p><p>{t('Основной депозит активного Epoch заблокирован. Для его досрочного возврата действует отдельная комиссия с суммы депозита.')} <a href="#early-withdrawal-fees">{t('Комиссии платформы за преждевременный вывод')}</a>.</p></article>
  {quotes.length>0&&<div className="withdrawal-epochs"><h3>{t('Ваш текущий этап')}</h3>{quotes.map(quote=>{const lease=leases.find(row=>row.id===quote.leaseId);return <article className="panel withdrawal-epoch" key={quote.leaseId}><b>{lease?.node?.name||lease?.nodeId} · {t('День')} {quote.cycleDay}/{lease?.contractDays||'—'}</b>{quote.reason==='COMPOUND_LOCKED'?<p>{t('Compound Boost: досрочный возврат депозита и накопленной прибыли недоступен до завершения Epoch (п. 5.4).')}</p>:<><p>{t('Досрочный возврат основного депозита')}: {quote.principal} USDT · <a href="#early-withdrawal-fees">{quote.feePercent}%</a> = <strong>{quote.fee} USDT</strong> · {t('к возврату')} {quote.netPrincipal} USDT.</p>{quote.allowed&&(unbondId===quote.leaseId?<div className="production-actions"><button className="secondary" onClick={()=>setUnbondId(null)}>{t('Отмена')}</button><button className="primary" disabled={busy} onClick={()=>void unbond(quote.leaseId)}>{t('Подтвердить досрочное завершение Epoch')}</button></div>:<button className="secondary" onClick={()=>setUnbondId(quote.leaseId)}>{t('Досрочно завершить Epoch')}</button>)}{!quote.allowed&&<p className="fine">{t('Досрочное завершение этого Epoch сейчас недоступно; сумма комиссии показана для ознакомления.')}</p>}</>}</article>})}</div>}
  {error&&<p role="alert" className="owner-error">{error}</p>}
  {step==='FORM'?<form className="panel production-form" onSubmit={e=>{e.preventDefault();setStep('REVIEW')}}><p>{t('Доступно')}: <strong>{balance} USDT</strong> · {t('Заблокировано в Base Epoch')}: {lockedBase} USDT · {t('Капитализировано внутри активного Epoch')}: {lockedCompound} USDT</p><label>{t('Сеть')}<input value="TON Mainnet" readOnly/></label><label>{t('Адрес TON')}<input required autoComplete="off" value={address} maxLength={70} onChange={e=>{setAddress(e.target.value);key.current=crypto.randomUUID()}} placeholder="UQ…"/></label><label>{t('Сумма, USDT')}<input required inputMode="decimal" min="10" step="0.000001" value={amount} onChange={e=>{setAmount(e.target.value);key.current=crypto.randomUUID()}} placeholder="10.00"/></label><p className="fine">{t('Сумма резервируется в учётном балансе при создании заявки. Перевод оператор выполнит вручную.')}</p><button className="primary">{t('Продолжить')}</button><button type="button" className="text-button" onClick={()=>setStep('LIST')}>{t('Мои заявки на вывод')}</button></form>:step==='REVIEW'?<article className="panel production-form"><h3>{t('Проверьте заявку')}</h3><dl><div><dt>{t('Сумма')}</dt><dd>{amount} USDT</dd></div><div><dt>{t('Сеть')}</dt><dd>TON Mainnet</dd></div><div><dt>{t('Адрес TON')}</dt><dd>{address}</dd></div><div><dt>{t('Комиссия платформы')}</dt><dd>0 USDT</dd></div><div><dt>{t('Сетевой Gas Fee')}</dt><dd>{t('По фактической комиссии TON')}</dd></div></dl><p>{t('Сумма резервируется при создании заявки. Сетевой Gas Fee будет рассчитан при ручной обработке.')}</p><div className="production-actions"><button className="secondary" onClick={()=>setStep('FORM')}>{t('Назад')}</button><button className="primary" disabled={busy} onClick={()=>void create()}>{busy?t('Отправка…'):t('Создать заявку')}</button></div></article>:<><button className="primary" onClick={()=>setStep('FORM')}>{t('Создать заявку на вывод')}</button><div className="production-list" aria-live="polite">{rows===null?<div className="activity-skeleton" role="status" aria-label={t('Загрузка…')}><i/><i/></div>:!rows.length?<p className="production-empty">{t('Заявок на вывод пока нет')}</p>:rows.map(row=><button className="production-row" key={row.id} aria-expanded={selected?.id===row.id} onClick={()=>setSelected(selected?.id===row.id?null:row)}><span><b>{row.amount} USDT</b><small>TON · {new Date(row.createdAt).toLocaleString(locale)}</small></span><span>{t(statusLabels[row.status]||row.status)}</span></button>)}</div></>}
  <details className="withdrawal-fee-schedule" id="early-withdrawal-fees" open><summary>{t('Комиссии платформы за преждевременный вывод')}</summary><p>{t('Комиссия удерживается только при досрочном возврате основного депозита в режиме Base (п. 5.5):')}</p><ul><li>{t('Дни 1–14 — 15% от депозита')}</li><li>{t('Дни 15–29 — 7% от депозита')}</li><li>{t('Дни 30–59 — 3% для Cluster Beta и Enterprise POD')}</li><li>{t('Дни 60–89 — 1,5% для Enterprise POD')}</li><li>{t('После окончания Epoch — 0%')}</li></ul><p>{t('Последние неполные сутки Alpha и Beta до момента окончания Epoch рассчитываются по предыдущей ставке соответствующего тарифа.')}</p><p>{t('Compound Boost блокирует досрочный возврат до конца Epoch; стандартный вывод доступного баланса имеет комиссию платформы 0%.')}</p></details>
  {selected&&step==='LIST'&&<article className="panel production-detail"><h3>{t('Детали заявки')}</h3><dl><div><dt>{t('Сумма')}</dt><dd>{selected.amount} USDT</dd></div><div><dt>{t('Сеть')}</dt><dd>TON</dd></div><div><dt>{t('Получатель')}</dt><dd>{selected.destinationAddress}</dd></div><div><dt>{t('Статус')}</dt><dd>{t(statusLabels[selected.status]||selected.status)}</dd></div><div><dt>{t('Создан')}</dt><dd>{new Date(selected.createdAt).toLocaleString(locale)}</dd></div><div><dt>{t('Комиссия платформы')}</dt><dd>{selected.platformFee===null?'—':selected.platformFee+' USDT'}</dd></div><div><dt>{t('Сетевой Gas Fee')}</dt><dd>{selected.networkFee===null?t('По фактической комиссии TON'):selected.networkFee+' USDT'}</dd></div>{selected.netAmount&&<div><dt>{t('К получению')}</dt><dd>{selected.netAmount} USDT</dd></div>}{selected.txHash&&<div><dt>Transaction hash</dt><dd><a href={'https://tonviewer.com/transaction/'+selected.txHash} target="_blank" rel="noopener noreferrer">{shortHash(selected.txHash)} ↗</a></dd></div>}{selected.rejectionReason&&<div><dt>{t('Причина отказа')}</dt><dd>{selected.rejectionReason}</dd></div>}</dl><div className="production-actions">{selected.status==='REQUESTED'&&<button className="secondary" disabled={busy} onClick={()=>void cancel(selected.id)}>{t('Отменить заявку')}</button>}<button className="secondary" onClick={()=>onSupport({referenceType:'WITHDRAWAL',referenceId:selected.id})}>{t('Сообщить о проблеме')}</button></div></article>}
 </section>;
}
